In [1]:
#pip install pandas openpyxl
import sys
!{sys.executable} -m pip install openpyxl
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import numpy as np

Requirement already satisfied: openpyxl in c:\users\vm35884\appdata\local\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\vm35884\appdata\local\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [2]:
accidents2019_df1 = pd.read_excel('data/2019 Accident Report.xlsx',sheet_name = 'DRIVER FAULT', skiprows=1, skipfooter=5, engine='openpyxl')
accidents2019_df2 = pd.read_excel('data/2019 Accident Report.xlsx',sheet_name = 'THIRD PARTY FAULT', skiprows=1, skipfooter=4, engine='openpyxl')
accidents2019_df3 = pd.read_excel('data/2019 Accident Report.xlsx',sheet_name = 'MYSTERY DAMAGE',skipfooter=1, engine='openpyxl')
accidents2019_df4 = pd.read_excel('data/2019 Accident Report.xlsx',sheet_name = 'CLAIMS SUBMITTED',skipfooter=6, engine='openpyxl')

In [3]:
accidents2019_df1.columns

Index(['Claim #', 'Other Claim #', 'Driver', 'Dept.', 'Unit #', 'Date',
       'Description', 'GL Driver', 'NON GL Driver ', 'GL Employee',
       'NON GL Employee', 'Ins Notified?', 'In-House/Ins ', 'GL Repair Cost ',
       '3rd Party Cost', 'Ins Fees', 'Time', 'Location', 'Weather', 'Lighting',
       'Road Surface', 'Road Type', 'Control Device', 'Driver Experience',
       'Raduis', 'Police Report', 'DOT Recordable?', 'Drive Cam?',
       'Safety Committee Ruling', 'Status'],
      dtype='object')

In [4]:
acc2019renamed_df1 = accidents2019_df1.rename(columns = {'Claim #':'ClaimNo', 'Other Claim #':'InsClaimNo', 'Driver':'DriverName', \
                                                      'Dept.':'Department', 'Unit #':'UnitNo', 'Date':'AccidentDate', 'Description':'Description', \
                                                      'GL Driver':'GLDriverFault','NON GL Driver ':'NonGLDriverFault','GL Employee':'GLEmployeeInjury', \
                                                      'NON GL Employee':'NonGLEmployeeInjury', \
                                                      'Ins Notified?':'InsNotified', \
                                                      'In-House/Ins ':'ClaimType', 'GL Repair Cost ':'GLRepairCost', '3rd Party Cost':'3rdPartyCost',\
                                                      'Ins Fees':'InsFee', 'Road Surface':'RoadSurface', 'Road Type':'RoadType', 'Control Device':'ControlDevice', \
                                                      'Driver Experience':'DriverExperience', 'Radius':'Radius', 'Police Report':'PoliceReport', \
                                                      'DOT Recordable?':'DOT Recordable', 'Drive Cam?':'DriveCam', 'Safety Committee Ruling':'SafetyCommRuling', \
                                                      'Status':'ClaimStatus'})

In [5]:
acc2019renamed_df1['Year'] = 2019

In [6]:
acc2019renamed_df1.head()

,ClaimNo,InsClaimNo,DriverName,Department,UnitNo,AccidentDate,Description,GLDriverFault,NonGLDriverFault,GLEmployeeInjury,...,RoadType,ControlDevice,DriverExperience,Raduis,PoliceReport,DOT Recordable,DriveCam,SafetyCommRuling,ClaimStatus,Year
0,010719-003,NaN,Jerry Mischler,Shop,7,2019-01-07,GL Mechanic hit another vehicle in an intersec...,Y,N,N,...,Straight,Traffic Light,N,0-50,Y,Y,N,N,Open,2019
1,011719-616,NaN,Rawand Koyee,SB,616,2019-01-17,Backed into 565 front passenger window,Y,N,N,...,N,N,3-4 Years,N,N,N,N,N,N,2019
2,011719-1021,NaN,Shawn Yokley,C,1021,2019-01-17,hooked back bumper on a cement pole,Y,N,N,...,N,N,6-11 MThs,N,N,N,N,N,N,2019
3,012019-727,NaN,James Johnson,BC,4727,2019-01-20,Hit pole in garage on right side,Y,N,N,...,N,N,1-2 Yrs,N,N,N,N,N,N,2019
4,012719-1023,NaN,Sadie Demoss,SS,1023,2019-01-27,driver backed 1023 into 243 mirror,Y,N,N,...,N,N,5+ Yrs,N,N,N,N,N,N,2019

In [7]:
accidents2019_df2.columns

Index(['Claim #', 'Other Claim #', 'Employee Name', 'Dept.', 'Unit #', 'Date',
       'Description', 'GL Driver', 'NON GL Driver ', 'GL Employee',
       'NON GL Employee', 'Ins. Notified',
       'In-House, Protective, or Other Driver/Insuance ',
       'Jerry's $ GL Bus Repair ', 'Cost for other vehicle/property repair',
       'Ins Fees', 'Time', 'Location', 'Weather', 'Lighting', 'Road Surface',
       'Road Description', 'Control Device', 'Raduis', 'Driver Info',
       'Police Report', 'DOT Recordable?', 'Drive Cam?',
       'Safety Committee Ruling', 'Status'],
      dtype='object')

In [8]:
acc2019renamed_df2 = accidents2019_df2.rename(columns = {'Claim #':'ClaimNo', 'Other Claim #':'InsClaimNo', 'Employee Name':'DriverName', \
                                                      'Dept.':'Department', 'Unit #':'UnitNo', 'Date':'AccidentDate', 'Description':'Description', \
                                                      'GL Driver':'GLDriverFault','NON GL Driver ':'NonGLDriverFault','GL Employee':'GLEmployeeInjury', \
                                                      'NON GL Employee':'NonGLEmployeeInjury', \
                                                      'Ins. Notified':'InsNotified', \
                                                      'In-House, Protective, or Other Driver/Insuance ':'ClaimType', 'GL Repair Cost':'GLRepairCost', \
                                                      "Jerry's $ GL Bus Repair ":'JerrysGLBusRepair', 'Cost for other vehicle/property repair':'CostForOtherVehicleRepair', \
                                                      'Ins Fees':'InsFee', 'Road Surface':'RoadSurface', 'Road Description':'RoadType', 'Control Device':'ControlDevice', \
                                                      'Radius':'Radius', 'Driver Info':'DriverInfo', 'Police Report':'PoliceReport', \
                                                      'DOT Recordable?':'DOT Recordable', 'Drive Cam?':'DriveCam', 'Safety Committee Ruling':'SafetyCommRuling', \
                                                      'Status':'ClaimStatus'})

In [9]:
acc2019renamed_df2['Year'] = 2019

In [10]:
acc2019renamed_df2.head()

,ClaimNo,InsClaimNo,DriverName,Department,UnitNo,AccidentDate,Description,GLDriverFault,NonGLDriverFault,GLEmployeeInjury,...,RoadType,ControlDevice,Raduis,DriverInfo,PoliceReport,DOT Recordable,DriveCam,SafetyCommRuling,ClaimStatus,Year
0,010319-271,td,Lonnie McGee,RTA,271,2019-01-03,GL Driver smelled smoke pulled over immediatel...,N,N,N,...,Divided,NaN,NaN,0-50,Y,Y,N,NaN,Open,2019
1,012419-626,NaN,David Brown,SB,626,2019-01-24,GL driver was exiting off the I24 onto Harding...,N,Y,N,...,level,none,0-50,1-2 Years,Y,N,N,NaN,Open,2019
2,013119-549,NaN,Denandra Olanumi,SB,549,2019-01-31,GL driver was stopped at a light vehicle from ...,N,Y,N,...,Level,NaN,0-50,1-2 Years,Y,N,NaN,NaN,Open,2019
3,020119-249,NaN,Kathy Jacobs,C,249,2019-02-01,GL driver was rear ended by a truck minor rear...,N,NaN,N,...,Level,NaN,0-50,6-11 mths,Y,N,NaN,NaN,Open,2019
4,020619-624,NaN,Wendell Mason,SB,624,2019-02-06,GL driver making a turn Oncoming vehicle clipp...,N,Y,N,...,Level,NaN,0-50,3-4 Years,Y,N,NaN,NaN,Open,2019

In [11]:
accidents2019_df3.columns

Index(['Claim Number', 'Employee Name', 'Dept', 'Date Reported', 'Unit No.',
       'Description', 'GL Driver', 'NON GL Employee', 'Ins. Notified',
       'In-House, GL Insuance Claim or Other Driver/Insuance ', 'Quote',
       'Jerry's $ GL Bus Repair '],
      dtype='object')

In [12]:
acc2019renamed_df3 = accidents2019_df3.rename(columns = {'Claim Number':'ClaimNo', 'Employee Name':'DriverName', \
                                                      'Dept':'Department', 'Unit No.':'UnitNo', 'Date Reported':'AccidentDate', 'Description':'Description', \
                                                      'GL Driver':'GLDriverFault','NON GL Employee':'NonGLDriverFault',
                                                      'Ins. Notified':'InsNotified', \
                                                      'In-House, GL Insuance Claim or Other Driver/Insuance ':'ClaimType', 'GL Repair Cost':'GLRepairCost', 
                                                      'Quote':'Quote', "Jerry's $ GL Bus Repair ":'JerrysGLBusRepair'})

In [13]:
acc2019renamed_df3['Year'] = 2019

In [14]:
acc2019renamed_df3.head()

,ClaimNo,DriverName,Department,AccidentDate,UnitNo,Description,GLDriverFault,NonGLDriverFault,InsNotified,ClaimType,Quote,JerrysGLBusRepair,Year
0,012619-306,Mystery,C,2019-01-26,306,Shop reported hole on the passenger side at th...,Johnny Smith,NaN,NaN,NaN,1829.59,Closed,2019
1,012619-274,Mystery,RTA,2019-01-26,274,Shop reported damage to passenger mirror door ...,Tammy Matheson,NaN,NaN,NaN,130,Closed,2019
2,012819-1012,Mystery,C,2019-01-28,1012,Shop reported RT hinge of battery compartment ...,Shop reported that this is common,NaN,NaN,NaN,227.5,Closed,2019
3,020119-308,mystery,Charter,2019-02-01,308,GL driver parked the bus in the shop area and ...,Theodore Wiley,NaN,NaN,NaN,896,Closed,2019
4,021319-307,Mystery,Charter,2019-02-03,307,Scuffs from what looks like a mirror,Cannot determine because this was done by what...,NaN,NaN,NaN,130,Closed,2019

In [15]:
accidents2019_df4.columns

Index(['Claim #', 'Other Claim #', 'Employee Name', 'Dept.', 'Unit #', 'Date',
       'Description', 'GL Driver', 'NON GL Driver ', 'GL Employee',
       'NON GL Employee', 'Ins. Notified',
       'In-House, Protective, or Other Driver/Insuance ',
       'Jerry's $ GL Bus Repair ', 'Cost for other vehicle/property repair',
       'Ins Fees', 'Time', 'Location', 'Weather', 'Lighting', 'Road Surface',
       'Road Description', 'Control Device', 'Driver Info', 'Raduis',
       'Police Report', 'DOT Recordable?', 'Drive Cam?',
       'Safety Committee Ruling', 'Status'],
      dtype='object')

In [16]:
acc2019renamed_df4 = accidents2019_df4.rename(columns = {'Claim #':'ClaimNo', 'Other Claim #':'InsClaimNo', 'Employee Name':'DriverName', \
                                                      'Dept.':'Department', 'Unit #':'UnitNo', 'Date':'AccidentDate', 'Description':'Description', \
                                                      'GL Driver':'GLDriverFault','NON GL Driver ':'NonGLDriverFault','GL Employee':'GLEmployeeInjury', \
                                                      'NON GL Employee':'NonGLEmployeeInjury', \
                                                      'Ins. Notified':'InsNotified', \
                                                      'In-House, Protective, or Other Driver/Insuance ':'ClaimType', \
                                                      "Jerry's $ GL Bus Repair ":'JerrysGLBusRepair', 'Cost for other vehicle/property repair':'CostForOtherVehicleRepair', \
                                                      'Ins Fees':'InsFee', 'Road Surface':'RoadSurface', 'Road Description':'RoadType', 'Control Device':'ControlDevice', \
                                                      'Driver Info':'DriverInfo', 'Radius':'Radius', 'Police Report':'PoliceReport', \
                                                      'DOT Recordable?':'DOT Recordable', 'Drive Cam?':'DriveCam', 'Safety Committee Ruling':'SafetyCommRuling', \
                                                      'Status':'ClaimStatus'})

In [17]:
acc2019renamed_df4['Year'] = 2019

In [18]:
acc2019renamed_df4.head()

,ClaimNo,InsClaimNo,DriverName,Department,UnitNo,AccidentDate,Description,GLDriverFault,NonGLDriverFault,GLEmployeeInjury,...,RoadType,ControlDevice,DriverInfo,Raduis,PoliceReport,DOT Recordable,DriveCam,SafetyCommRuling,ClaimStatus,Year
0,012719-1023,NaN,Sadie Demoss,SS,1023,1902-10-19,driver backed 1023 into 243 mirror,Y,N,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,2019
1,010319-271,NaN,Lonnie McGee,RTA,271,2019-01-03,GL Driver smelled smoke pulled over immediatel...,N,N,N,...,Divided,NaN,NaN,0-50,Y,Y,N,NaN,Open,2019
2,010719-003,NaN,Jerry Mischler,Shop,7,2019-01-07,GL Mechanic hit another vehicle in an intersec...,Y,N,N,...,Straight,Traffic Light,NaN,0-50,Y,Y,N,NaN,Open,2019
3,011719-616,NaN,Rawand Koyee,SB,616,2019-01-17,Backed into 565 front passenger window,Y,N,N,...,NaN,NaN,3-4 Years,NaN,NaN,N,NaN,NaN,NaN,2019
4,012219-616,NaN,Rawand Koyee,SB,616,2019-01-20,GL got caught at the end of a Cul De Sac tried...,Y,N,N,...,Level,NaN,NaN,0-50,Y,N,N,NaN,Open,2019

In [19]:
consolidatedaccidents2019_df = pd.concat([acc2019renamed_df1, acc2019renamed_df2,acc2019renamed_df3,acc2019renamed_df4], ignore_index=True, axis=0)

In [20]:
consolidatedaccidents2019_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'Department', 'UnitNo',
       'AccidentDate', 'Description', 'GLDriverFault', 'NonGLDriverFault',
       'GLEmployeeInjury', 'NonGLEmployeeInjury', 'InsNotified', 'ClaimType',
       'GLRepairCost', '3rdPartyCost', 'InsFee', 'Time', 'Location', 'Weather',
       'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'PoliceReport', 'DOT Recordable',
       'DriveCam', 'SafetyCommRuling', 'ClaimStatus', 'Year',
       'JerrysGLBusRepair', 'CostForOtherVehicleRepair', 'DriverInfo',
       'Quote'],
      dtype='object')

In [21]:
consolidatedaccidents2019_df.head()

,ClaimNo,InsClaimNo,DriverName,Department,UnitNo,AccidentDate,Description,GLDriverFault,NonGLDriverFault,GLEmployeeInjury,...,PoliceReport,DOT Recordable,DriveCam,SafetyCommRuling,ClaimStatus,Year,JerrysGLBusRepair,CostForOtherVehicleRepair,DriverInfo,Quote
0,010719-003,NaN,Jerry Mischler,Shop,7,2019-01-07,GL Mechanic hit another vehicle in an intersec...,Y,N,N,...,Y,Y,N,N,Open,2019,NaN,NaN,NaN,NaN
1,011719-616,NaN,Rawand Koyee,SB,616,2019-01-17,Backed into 565 front passenger window,Y,N,N,...,N,N,N,N,N,2019,NaN,NaN,NaN,NaN
2,011719-1021,NaN,Shawn Yokley,C,1021,2019-01-17,hooked back bumper on a cement pole,Y,N,N,...,N,N,N,N,N,2019,NaN,NaN,NaN,NaN
3,012019-727,NaN,James Johnson,BC,4727,2019-01-20,Hit pole in garage on right side,Y,N,N,...,N,N,N,N,N,2019,NaN,NaN,NaN,NaN
4,012719-1023,NaN,Sadie Demoss,SS,1023,2019-01-27,driver backed 1023 into 243 mirror,Y,N,N,...,N,N,N,N,N,2019,NaN,NaN,NaN,NaN

In [22]:
consolidatedaccidents2019_df = consolidatedaccidents2019_df.groupby('ClaimNo', as_index=False).agg(lambda x: ' | '.join(map(str, x)))

In [24]:
def extract_first_valid_value(cell):
    if pd.isna(cell):
        return np.nan
    parts = [p.strip() for p in str(cell).split('|')]
    for part in parts:
        if part.lower() != 'nan' and part != '':
            return part
    return np.nan

# Apply to entire DataFrame
final2019_df = consolidatedaccidents2019_df.applymap(extract_first_valid_value)

# Optional: Drop fully empty columns
final2019_df = final2019_df.dropna(axis=1, how='all')

# Preview result
final2019_df.head()

,ClaimNo,InsClaimNo,DriverName,Department,UnitNo,AccidentDate,Description,GLDriverFault,NonGLDriverFault,GLEmployeeInjury,...,PoliceReport,DOT Recordable,DriveCam,SafetyCommRuling,ClaimStatus,Year,JerrysGLBusRepair,CostForOtherVehicleRepair,DriverInfo,Quote
0,010319-271,td,Lonnie McGee,RTA,271,2019-01-03 00:00:00,GL Driver smelled smoke pulled over immediatel...,N,N,N,...,Y,Y,N,NaN,Open,2019,184385.5,NaN,0-50,NaN
1,010719-003,NaN,Jerry Mischler,Shop,7,2019-01-07 00:00:00,GL Mechanic hit another vehicle in an intersec...,Y,N,N,...,Y,Y,N,N,Open,2019,NaN,3108.94,NaN,NaN
2,011719-1021,NaN,Shawn Yokley,C,1021,2019-01-17 00:00:00,hooked back bumper on a cement pole,Y,N,N,...,N,N,N,N,N,2019,NaN,NaN,NaN,NaN
3,011719-616,NaN,Rawand Koyee,SB,616,2019-01-17 00:00:00,Backed into 565 front passenger window,Y,N,N,...,N,N,N,N,N,2019,642.97,NaN,3-4 Years,NaN
4,012019-727,NaN,James Johnson,BC,4727,2019-01-20 00:00:00,Hit pole in garage on right side,Y,N,N,...,N,N,N,N,N,2019,NaN,NaN,NaN,NaN

In [25]:
final2019_df.to_excel('data/finaldaccidents2019.xlsx', index=False)