In [1]:
#pip install pandas openpyxl
import sys
!{sys.executable} -m pip install openpyxl
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: openpyxl in c:\users\malan\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\malan\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [2]:
import os
print(os.listdir('data'))

['2018 Accident Incident Report.xlsx', '2019 Accident Report.xlsx', '2020 Accident Report.xlsx', '2021 Accident Report.xlsx', 'accidents_2024.csv', 'accidents_2025.csv', 'accidents_2025_preventable_addition.csv', 'grayline_fleet_vehicles.csv']

In [3]:
accidents2018_df = pd.read_excel('data/2018 Accident Incident Report.xlsx', sheet_name = 'Sheet1',skiprows=2, engine='openpyxl')
accidents2019_df = pd.read_excel('data/2019 Accident Report.xlsx',sheet_name = 'DRIVER FAULT',skiprows=1, engine='openpyxl')
accidents2020_df = pd.read_excel('data/2020 Accident Report.xlsx', sheet_name = 'Master', engine='openpyxl')
accidents2021_df = pd.read_excel('data/2021 Accident Report.xlsx', sheet_name = 'Master', engine='openpyxl')
accidents2024_df = pd.read_csv('data/accidents_2024.csv')
accidents2025_df = pd.read_csv('data/accidents_2025.csv')
accidents2025prevent_df = pd.read_csv('data/accidents_2025_preventable_addition.csv')
graylinefleet_df = pd.read_csv('data/grayline_fleet_vehicles.csv')

In [4]:
accidents2018_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 22 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Claim #                                          128 non-null    object
 1   Employee Name                                    128 non-null    object
 2   Dept.                                            116 non-null    object
 3   Date Occurred                                    127 non-null    object
 4   Incident / Accident                              126 non-null    object
 5   DOT Recordable?                                  126 non-null    object
 6   Unit No.                                         120 non-null    object
 7   Description                                      123 non-null    object
 8   GL Driver                                        69 non-null     object
 9   NON GL Driver                                    33 non-null     object
 10  GL Employee                                      118 non-null    object
 11  NON GL Employee                                  114 non-null    object
 12  Ins. Notified                                    111 non-null    object
 13  In-House, Protective, or Other Driver/Insuance   100 non-null    object
 14  Jerry's $ GL Bus Repair                          11 non-null     object
 15  Quote                                            3 non-null      object
 16  Cost for other vehicle repair                    9 non-null      object
 17  Actual                                           1 non-null      object
 18  Police Report                                    65 non-null     object
 19  Drive Cam?                                       54 non-null     object
 20  Safety Committee Ruling                          62 non-null     object
 21  Status                                           67 non-null     object
dtypes: object(22)
memory usage: 22.6+ KB

In [5]:
acc2018renamed_df = accidents2018_df.rename(columns = {'Claim #':'ClaimNo', 'Employee Name':'DriverName', 'Dept.':'Department', 'Date Occurred ':'AccidentDate',\
                                                      'Incident / Accident':'IncidentAccident', 'DOT Recordable?' : 'DotRecordable', 'Unit No.':'UnitNo', 'GL Driver':'GLDriver', \
                                                      'NON GL Driver ':'NonGLdriver', 'GL Employee':'GLEmployee', 'NON GL Employee':'NonGLEmployee',  \
                                                      'Ins. Notified':'InsNotified', 'In-House, Protective, or Other Driver/Insuance ':'ClaimType', "Jerry's $ GL Bus Repair ":'JerrysBusRepair', \
                                                      'Actual':'Actual', 'Cost for other vehicle repair':'CostForOtherVehicleRepair', 'Police Report':'PoliceReport', \
                                                      'Drive Cam?':'DriveCam', 'Safety Committee Ruling':'SafetyCommRuling','DOT Recordable?':'Dot Recordable', \
                                                      'Status':'ClaimStatus'})

In [52]:
accidents2018_df['Year']=2018

In [48]:
accidents2018_df.columns

Index(['Claim #', 'Employee Name', 'Dept.', 'Date Occurred ',
       'Incident / Accident', 'DOT Recordable?', 'Unit No.', 'Description',
       'GL Driver', 'NON GL Driver ', 'GL Employee', 'NON GL Employee',
       'Ins. Notified', 'In-House, Protective, or Other Driver/Insuance ',
       'Jerry's $ GL Bus Repair ', 'Quote', 'Cost for other vehicle repair',
       'Actual', 'Police Report', 'Drive Cam?', 'Safety Committee Ruling',
       'Status', 'Year'],
      dtype='object')

In [54]:
acc2018renamed_df['Year']=2018

In [55]:
acc2018renamed_df.head()

,ClaimNo,DriverName,Department,AccidentDate,IncidentAccident,Dot Recordable,UnitNo,Description,GLDriver,NonGLdriver,...,ClaimType,JerrysBusRepair,Quote,CostForOtherVehicleRepair,Actual,PoliceReport,DriveCam,SafetyCommRuling,ClaimStatus,Year
0,010318-533,Brittney Patterson,School Bus,2018-01-04 00:00:00,Incident,Non-DOT,533,"Driver hit a sign, no damage reported",X,NaN,...,In-House,NaN,NaN,NaN,NaN,N,N,Preventable,Closed,2018
1,010718-1015,Scott Wangrud,Charter,2018-01-07 00:00:00,Incident,Non-DOT,1015,Supposedly hit an Anchor Bus' mirror,X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,N,Preventable,Closed,2018
2,011518-1021,Thomas House,Charter,2018-01-15 00:00:00,Accident,Non-DOT,1021,Driver hit a sign,X,NaN,...,In-House,3185.35,NaN,NaN,NaN,N,N,Preventable,Closed,2018
3,011618-1015,David Armstrong,Charter,2018-01-16 00:00:00,Accident,Non-DOT,1015,Bus slid into concrete light pole. Parking lot...,NaN,X,...,In-House,NaN,NaN,NaN,NaN,N,N,Non-Preventable,Closed,2018
4,011918-232,William Moncrief,Tour,2018-01-19 00:00:00,Accident,Non-DOT,232,Our bus was hit by Freeman Trucking. Right sid...,NaN,X,...,OP Ins,NaN,NaN,NaN,NaN,Y,N,Non-Preventable,Open,2018

In [8]:
accidents2019_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Claim #                  158 non-null    object
 1   Other Claim #            27 non-null     object
 2   Driver                   158 non-null    object
 3   Dept.                    154 non-null    object
 4   Unit #                   154 non-null    object
 5   Date                     154 non-null    datetime64[ns]
 6   Description              154 non-null    object
 7   GL Driver                154 non-null    object
 8   NON GL Driver            154 non-null    object
 9   GL Employee              154 non-null    object
 10  NON GL Employee          154 non-null    object
 11  Ins Notified?            154 non-null    object
 12  In-House/Ins             154 non-null    object
 13  GL Repair Cost           145 non-null    object
 14  3rd Party Cost           34 non-null     float64
 15  Ins Fees                 153 non-null    float64
 16  Time                     153 non-null    object
 17  Location                 153 non-null    object
 18  Weather                  154 non-null    object
 19  Lighting                 153 non-null    object
 20  Road Surface             154 non-null    object
 21  Road Type                153 non-null    object
 22  Control Device           55 non-null     object
 23  Driver Experience        153 non-null    object
 24  Raduis                   152 non-null    object
 25  Police Report            153 non-null    object
 26  DOT Recordable?          153 non-null    object
 27  Drive Cam?               153 non-null    object
 28  Safety Committee Ruling  153 non-null    object
 29  Status                   154 non-null    object
dtypes: datetime64[ns](1), float64(2), object(27)
memory usage: 37.4+ KB

In [9]:
accidents2019_df.columns

Index(['Claim #', 'Other Claim #', 'Driver', 'Dept.', 'Unit #', 'Date',
       'Description', 'GL Driver', 'NON GL Driver ', 'GL Employee',
       'NON GL Employee', 'Ins Notified?', 'In-House/Ins ', 'GL Repair Cost ',
       '3rd Party Cost', 'Ins Fees', 'Time', 'Location', 'Weather', 'Lighting',
       'Road Surface', 'Road Type', 'Control Device', 'Driver Experience',
       'Raduis', 'Police Report', 'DOT Recordable?', 'Drive Cam?',
       'Safety Committee Ruling', 'Status'],
      dtype='object')

In [50]:
accidents2019_df['Year']=2019

In [10]:
acc2019renamed_df = accidents2019_df.rename(columns = {'Claim #':'ClaimNo', 'Other Claim #':'InsClaimNo', 'Driver':'DriverName', \
                                                      'Dept.':'Department', 'Unit #':'UnitNo', 'Date':'AccidentDate',  \
                                                      'GL Driver':'GLDriver', 'NON GL Driver ':'NonGLDriver', 'GL Employee': 'GLEmployee',\
                                                       'NON GL Employee':'NonGLEmployee', 'Ins Notified?':'InsNotified', \
                                                      'In-House/Ins ':'ClaimType', 'GL Repair Cost ':'GLRepairCost', '3rd Party Cost':'3rdPartyCost',\
                                                      'Ins Fees':'Insfee', \
                                                      'Road Surface':'RoadSurface', 'Road Type':'RoadType', 'Control Device':'ControlDevice', \
                                                      'Driver Experience':'DriverExperience', 'Police Report':'PoliceReport', \
                                                      'DOT Recordable?':'DotRecordable', 'Drive Cam?':'DriveCam', 'Safety Committee Ruling':'SafetyCommRuling', \
                                                      'Status':'ClaimStatus',})

In [56]:
acc2019renamed_df['Year']=2019

In [57]:
acc2019renamed_df.head()

,ClaimNo,InsClaimNo,DriverName,Department,UnitNo,AccidentDate,Description,GLDriver,NonGLDriver,GLEmployee,...,RoadType,ControlDevice,DriverExperience,Raduis,PoliceReport,DotRecordable,DriveCam,SafetyCommRuling,ClaimStatus,Year
0,010719-003,NaN,Jerry Mischler,Shop,7,2019-01-07,GL Mechanic hit another vehicle in an intersec...,Y,N,N,...,Straight,Traffic Light,N,0-50,Y,Y,N,N,Open,2019
1,011719-616,NaN,Rawand Koyee,SB,616,2019-01-17,Backed into 565 front passenger window,Y,N,N,...,N,N,3-4 Years,N,N,N,N,N,N,2019
2,011719-1021,NaN,Shawn Yokley,C,1021,2019-01-17,hooked back bumper on a cement pole,Y,N,N,...,N,N,6-11 MThs,N,N,N,N,N,N,2019
3,012019-727,NaN,James Johnson,BC,4727,2019-01-20,Hit pole in garage on right side,Y,N,N,...,N,N,1-2 Yrs,N,N,N,N,N,N,2019
4,012719-1023,NaN,Sadie Demoss,SS,1023,2019-01-27,driver backed 1023 into 243 mirror,Y,N,N,...,N,N,5+ Yrs,N,N,N,N,N,N,2019

In [12]:
accidents2020_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CLAIM NUMBER          50 non-null     object
 1   CLAIM NUMBER2         50 non-null     int64
 2   DRIVER NAME           50 non-null     object
 3   EMPLOYEE ID           50 non-null     int64
 4   DEPARTMENT            50 non-null     object
 5   UNIT NO               50 non-null     int64
 6   ACC DATE              50 non-null     datetime64[ns]
 7   DESCRIPTION           50 non-null     object
 8   DRIVER INJURED        50 non-null     bool
 9   OP INJURED            50 non-null     bool
 10  CLAIM TYPE            49 non-null     object
 11  GL BUS ESTIMATE       50 non-null     float64
 12  GL BUS REPAIR         50 non-null     float64
 13  GL FINAL COST         50 non-null     float64
 14  OP REPAIR COST        50 non-null     float64
 15  INS FEE               50 non-null     int64
 16  OP INS PAID TO GL     50 non-null     float64
 17  INSURANCE DEDUCTIBLE  50 non-null     int64
 18  TOTAL                 50 non-null     float64
 19  TIME                  50 non-null     object
 20  LOCATION              50 non-null     object
 21  WEATHER               50 non-null     object
 22  LIGHTING              50 non-null     object
 23  ROAD SURFACE          50 non-null     object
 24  ROAD TYPE             50 non-null     object
 25  DRIVER ACTION         50 non-null     object
 26  DRIVER EXPERIENCE     50 non-null     float64
 27  RADIUS                50 non-null     object
 28  POLICE REPORT         50 non-null     bool
 29  DOT RECORDABLE        50 non-null     bool
 30  VIDEO                 50 non-null     bool
 31  PREVENTABLE?          50 non-null     bool
 32  STATUS                50 non-null     object
dtypes: bool(6), datetime64[ns](1), float64(7), int64(5), object(14)
memory usage: 11.0+ KB

In [13]:
accidents2020_df.columns

Index(['CLAIM NUMBER', 'CLAIM NUMBER2', 'DRIVER NAME', 'EMPLOYEE ID',
       'DEPARTMENT', 'UNIT NO', 'ACC DATE', 'DESCRIPTION', 'DRIVER INJURED',
       'OP INJURED', 'CLAIM TYPE', 'GL BUS ESTIMATE', 'GL BUS REPAIR',
       'GL FINAL COST', 'OP REPAIR COST', 'INS FEE', 'OP INS PAID TO GL',
       'INSURANCE DEDUCTIBLE', 'TOTAL', 'TIME', 'LOCATION', 'WEATHER',
       'LIGHTING', 'ROAD SURFACE', 'ROAD TYPE', 'DRIVER ACTION',
       'DRIVER EXPERIENCE', 'RADIUS', 'POLICE REPORT', 'DOT RECORDABLE',
       'VIDEO', 'PREVENTABLE?', 'STATUS'],
      dtype='object')

In [14]:
acc2020renamed_df = accidents2020_df.rename(columns = {'CLAIM NUMBER' : 'ClaimNo', 'CLAIM NUMBER2' : 'InsClaimNo', 'DRIVER NAME' : 'DriverName',\
                                                      'EMPLOYEE ID' : 'EmployeeId',  'DEPARTMENT' : 'Department', 'ACC DATE': 'AccidentDate', \
                                                      'DESCRIPTION' : 'Description', 'DRIVER INJURED' : 'DriverInjured', 'OP INJURED' : 'OpInjured', \
                                                      'CLAIM TYPE' : 'ClaimType', 'GL BUS ESTIMATE' : 'GLBusEstimate', 'GL BUS REPAIR' : 'GLBusRepair', \
                                                      'OP REPAIR COST' : 'OpRepairCost', 'INS FEE' : 'InsFee', 'OP INS PAID TO GL' : 'OpInsPaid', \
                                                      'INSURANCE DEDUCTIBLE' : 'InsDeductable', 'TOTAL' : 'Total', 'TIME' : 'Time', 'LOCATION' : 'Location', \
                                                      'WEATHER' : 'Weather', 'LIGHTING' : 'Lighting', 'ROAD SURFACE' : 'RoadSurface', 'ROAD TYPE' : 'RoadType', \
                                                      'DRIVER ACTION' : 'DriverAction','DRIVER EXPERIENCE' : 'DriverExperience', 'RADIUS' : 'Radius', 'POLICE REPORT' : 'PoliceReport', \
                                                      'DOT RECORDABLE' : 'DotRecordable', 'VIDEO' : 'Video', 'PREVENTABLE?' : 'Preventable', \
                                                      'STATUS' : 'ClaimStatus', 'UNIT NO' : 'UnitNo'})

In [58]:
acc2020renamed_df['Year']=2020

In [59]:
acc2020renamed_df.head()

,ClaimNo,InsClaimNo,DriverName,EmployeeId,Department,UnitNo,AccidentDate,Description,DriverInjured,OpInjured,...,RoadType,DriverAction,DriverExperience,Radius,PoliceReport,DotRecordable,Video,Preventable,ClaimStatus,Year
0,010620-246,0,Alesha Harney,11038,Charter,246,2020-01-06,car hit the front bumper of the bus - scuffed ...,False,False,...,Parking Lot,Stop Sign,7.0,0-50,False,False,False,False,CLOSED,2020
1,010820-214,0,Kelly Westerlund,10979,Sightseeing,214,2020-01-08,"driver hit a service truck turning right, bus ...",False,False,...,Residential Street,turning right,1.0,0-50,True,False,False,True,CLOSED,2020
2,010920-1019,767903,Robert Kimbrell,10346,Charter,1019,2020-01-09,driver clipped a college student when she drov...,False,False,...,Residential Street,N,30.0,0-50,True,False,False,True,CLOSED,2020
3,010920-1019,0,Robert Kimbrell,10346,Charter,1019,2020-01-09,driver failed to set brake and bus rolled into...,False,False,...,Parking Lot,stopped,30.0,0-50,False,False,True,True,CLOSED,2020
4,011020-721,767935,Michael Beattie,10039,RTA,721,2020-01-10,hit OP right rear fender turning left at Charl...,False,False,...,Intersection,turning left,33.0,0-50,True,False,False,True,CLOSED,2020

In [16]:
accidents2021_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ClaimNo          92 non-null     object
 1   InsClaimNo       91 non-null     float64
 2   DRIVERNAME       97 non-null     object
 3   EmployeeID       18 non-null     float64
 4   DEPT             96 non-null     object
 5   UnitNo           96 non-null     object
 6   AccidentDate     97 non-null     datetime64[ns]
 7   DESCRIPTION      97 non-null     object
 8   OPFAULT          87 non-null     float64
 9   INJURY           93 non-null     object
 10  ClaimType        37 non-null     object
 11  GLEstimate       18 non-null     float64
 12  Final            18 non-null     float64
 13  OPRepair         19 non-null     float64
 14  Total            97 non-null     float64
 15  TIME             95 non-null     object
 16  LOCATION         83 non-null     object
 17  CityState        43 non-null     object
 18  WEATHER          94 non-null     object
 19  LIGHTING         94 non-null     object
 20  RoadSurface      94 non-null     object
 21  RoadType         94 non-null     object
 22  DriverAction     94 non-null     object
 23  PoliceReport     82 non-null     object
 24  DOTRecordable    95 non-null     object
 25  VIDEO            14 non-null     object
 26  PREV             18 non-null     object
 27  STATUS           18 non-null     object
 28  ClaimAdj         2 non-null      object
 29  NOTES            20 non-null     object
 30  VMS Accident No  17 non-null     float64
dtypes: datetime64[ns](1), float64(8), object(22)
memory usage: 23.6+ KB

In [17]:
accidents2021_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DRIVERNAME', 'EmployeeID', 'DEPT', 'UnitNo',
       'AccidentDate', 'DESCRIPTION', 'OPFAULT', 'INJURY', 'ClaimType',
       'GLEstimate', 'Final', 'OPRepair', 'Total', 'TIME', 'LOCATION',
       'CityState', 'WEATHER', 'LIGHTING', 'RoadSurface', 'RoadType',
       'DriverAction', 'PoliceReport', 'DOTRecordable', 'VIDEO', 'PREV',
       'STATUS', 'ClaimAdj', 'NOTES', 'VMS Accident No'],
      dtype='object')

In [18]:
acc2021renamed_df = accidents2021_df.rename(columns = {'DRIVERNAME' : 'DriverName',\
                                                      'DEPT' : 'Department', 'DESCRIPTION' : 'Description', \
                                                      'OPFAULT' : 'OpFault', 'INJURY' : 'Injury', 'GL Estimate':'GLBusEstimate', 'OPRepair':'OpRepair',\
                                                      'TIME':'Time', 'LOCATION':'Location', 'WEATHER':'Weather', \
                                                      'LIGHTING':'Lighting', \
                                                      'DOTRecordable' : 'DotRecordable', 'VIDEO': 'Video', 'PREV':'Preventable', \
                                                      'Date Occured': 'AccidentDate',  'ClaimType' : 'ClaimType','STATUS' : 'ClaimStatus',\
                                                      'NOTES':'Notes', 'VMS Accident No':'VmsAccidentNo'})

In [60]:
acc2021renamed_df['Year']=2021

In [61]:
acc2021renamed_df.head(5)

,ClaimNo,InsClaimNo,DriverName,EmployeeID,Department,UnitNo,AccidentDate,Description,OpFault,Injury,...,DriverAction,PoliceReport,DotRecordable,Video,Preventable,ClaimStatus,ClaimAdj,Notes,VmsAccidentNo,Year
0,011321-715,110.0,Elizabeth Burton,10086.0,RTA,715,2021-01-13,Penske truck hit passenger side mirror of bus ...,1.0,False,...,"Stopped, Not Moving",FALSE,FALSE,False,False,Open,NaN,Unscheduled activity id78458,110.0,2021
1,011421-280,111.0,Robert Schneider,11016.0,RTA,280,2021-01-14,a bobcat truck pulling a 36' to 40' constructi...,1.0,False,...,"Stopped, Not Moving",FALSE,FALSE,False,False,Open,NaN,UnscheduledActivity id 78478,111.0,2021
2,011721-329,112.0,Anthony Wells,10914.0,Charter,329,2021-01-17,"driver backed into a pay booth, rear screen o...",0.0,False,...,Right Turn,FALSE,FALSE,False,True,Open,NaN,driver submitted defect with description that ...,112.0,2021
3,011721-4101,768974.0,Sameh Shaker,10566.0,School Bus,4101,2021-01-17,Our bus was parked on the side of the road whe...,1.0,TRUE,...,"Stopped, Not Moving",TRUE,TRUE,False,False,Open,Lisa Carey,State Farm Claim No. 4215V715T - reported to L...,113.0,2021
4,011921-000,235957.0,Jenniefer Stephens,10597.0,Charter,0,2021-01-19,IW was closing tire cover when the bumper clos...,0.0,TRUE,...,"Stopped, Not Moving",False,False,False,True,Open,Tracy Robinson,Work Comp,NaN,2021

In [20]:
accidents2024_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   claimno                  190 non-null    object
 1   insclaimno               190 non-null    object
 2   drivername               190 non-null    object
 3   employeeid               190 non-null    object
 4   dept                     190 non-null    object
 5   unitno                   190 non-null    object
 6   accidentdate             190 non-null    object
 7   description              190 non-null    object
 8   preventable?             190 non-null    object
 9   injury                   190 non-null    object
 10  loss_of_bonus_           190 non-null    object
 11  coaching                 190 non-null    object
 12  final___jerrys_estimate  190 non-null    object
 13  est                      190 non-null    object
 14  oprepair                 190 non-null    object
 15  total                    190 non-null    object
 16  time                     190 non-null    object
 17  address                  190 non-null    object
 18  citystate                190 non-null    object
 19  weather                  190 non-null    object
 20  lighting                 190 non-null    object
 21  roadsurface              190 non-null    object
 22  roadtype                 190 non-null    object
 23  driveraction             190 non-null    object
 24  policereport             190 non-null    object
 25  dotrecordable            190 non-null    object
 26  video                    190 non-null    object
 27  prev                     190 non-null    object
 28  status                   190 non-null    object
 29  claimadj                 190 non-null    object
 30  notes                    190 non-null    object
 31  vms_accident_no          190 non-null    object
dtypes: object(32)
memory usage: 47.6+ KB

In [21]:
accidents2024_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no'],
      dtype='object')

In [76]:
acc2024renamed_df = accidents2024_df.rename(columns = {'claimno':'ClaimNo', 'insclaimno':'InsClaimNo', 'drivername':'DriverName','employeeid':'EmployeeID', \
                                                       'dept' : 'Department', 'unitno' : 'UnitNo', 'accidentdate':'AccidentDate', 'description':'Description','preventable?':'Preventable', \
                                                      'injury':'Injury','loss_of_bonus_':'LossOfBonus', 'final___jerrys_estimate':'FinalJerrysEstimate','est':'Estimate','oprepair':'OpRepair', \
                                                      'total':'Total','time':'Time', 'address':'Address', 'citystate':'CityState', 'weather':'Weather',\
                                                       'lightning':'Lightning', 'roadsurface':'RoadSurface', 'roadtype':'RoadType', 'driveraction':'DriverAction', 'policereport':'PoliceReport',\
                                                       'dotrecordable' : 'DotRecordable', 'video':'Video','prev':'Preventable', 'status' : 'ClaimStatus', 'claimadj':'ClaimAdj', 'notes':'Notes', \
                                                      'vms_accident_no':'VmsAccidentNo'})

In [77]:
acc2024renamed_df['Year']=2024

In [78]:
acc2024renamed_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'EmployeeID', 'Department',
       'UnitNo', 'AccidentDate', 'Description', 'Preventable', 'Injury',
       'LossOfBonus', 'coaching', 'FinalJerrysEstimate', 'Estimate',
       'OpRepair', 'Total', 'Time', 'Address', 'CityState', 'Weather',
       'lighting', 'RoadSurface', 'RoadType', 'DriverAction', 'PoliceReport',
       'DotRecordable', 'Video', 'Preventable', 'ClaimStatus', 'ClaimAdj',
       'Notes', 'VmsAccidentNo', 'Year'],
      dtype='object')

In [63]:
acc2024renamed_df.head()

,ClaimNo,InsClaimNo,DriverName,EmployeeID,Department,UnitNo,AccidentDate,Description,Preventable,Injury,...,DriverAction,PoliceReport,DotRecordable,Video,Preventable,ClaimStatus,ClaimAdj,Notes,VmsAccidentNo,Year
0,010124-311,Not Registered,Douglas Bumpus,5,Charter,311,2024-01-01 00:00:00.000,Turning in parking lot of Buccees hit a car.,yes,no,...,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
1,010524-319,Not Registered,Devon Whitmore,0-1,Charter,319,2024-01-05 00:00:00.000,"Backing bus into slot,fatigue driving back got...",yes,no,...,Backing,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
2,011124-312,Not Registered,Troy Fontechia,1-2,Charter,312,2024-01-11 00:00:00.000,Car nearly crashed pick up truck while merging...,no,No,...,Driving Forward,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
3,Not Registered,Not Registered,DERRICK Lowe,Not Registered,RTA,722,2024-01-18 00:00:00.000,Thursday is my day to get my Bus wash when i...,yes,Not Registered,...,Driving Forward,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Marker light,Not Registered,2024
4,012524-336,Not Registered,Estus Owens,5,Charter,336,2024-01-25 00:00:00.000,I was backing up at the Embassy suites downtow...,yes,no,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024

In [24]:
accidents2025_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   claimno                  57 non-null     object
 1   insclaimno               57 non-null     object
 2   drivername               57 non-null     object
 3   employeeid               57 non-null     object
 4   dept                     57 non-null     object
 5   unitno                   57 non-null     int64
 6   accidentdate             57 non-null     object
 7   description              57 non-null     object
 8   preventable?             57 non-null     object
 9   injury                   57 non-null     object
 10  loss_of_bonus_           57 non-null     object
 11  coaching                 57 non-null     object
 12  final___jerrys_estimate  57 non-null     object
 13  est                      57 non-null     object
 14  oprepair                 57 non-null     object
 15  total                    57 non-null     object
 16  time                     57 non-null     object
 17  address                  57 non-null     object
 18  citystate                57 non-null     object
 19  weather                  57 non-null     object
 20  lighting                 57 non-null     object
 21  roadsurface              57 non-null     object
 22  roadtype                 57 non-null     object
 23  driveraction             57 non-null     object
 24  policereport             57 non-null     object
 25  dotrecordable            57 non-null     object
 26  video                    57 non-null     object
 27  prev                     57 non-null     object
 28  status                   57 non-null     object
 29  claimadj                 57 non-null     object
 30  notes                    57 non-null     object
 31  vms_accident_no          57 non-null     object
dtypes: int64(1), object(31)
memory usage: 14.4+ KB

In [25]:
accidents2025_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no'],
      dtype='object')

In [72]:
acc2025renamed_df = accidents2025_df.rename(columns = {'claimno':'ClaimNo', 'insclaimno':'InsClaimNo', 'drivername':'DriverName','employeeid':'EmployeeID', \
                                                       'dept' : 'Department', 'unitno' : 'UnitNo', 'accidentdate':'AccidentDate', 'description':'Description','preventable?':'Preventable', \
                                                      'injury':'Injury','loss_of_bonus_':'LossOfBonus', 'final___jerrys_estimate':'FinalJerrysEstimate','est':'Estimate','oprepair':'OpRepair', \
                                                      'total':'Total','time':'Time', 'address':'Address', 'citystate':'CityState', 'weather':'Weather',\
                                                       'lightning':'Lightning', 'roadsurface':'RoadSurface', 'roadtype':'RoadType', 'driveraction':'DriverAction', 'policereport':'PoliceReport',\
                                                       'dotrecordable' : 'DotRecordable', 'video':'Video','prev':'Preventable', 'status' : 'ClaimStatus', 'claimadj':'ClaimAdj', 'notes':'Notes', \
                                                      'vms_accident_no':'VmsAccidentNo'})

In [73]:
acc2025renamed_df['Year']=2025

In [74]:
acc2025renamed_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'EmployeeID', 'Department',
       'UnitNo', 'AccidentDate', 'Description', 'Preventable', 'Injury',
       'LossOfBonus', 'coaching', 'FinalJerrysEstimate', 'Estimate',
       'OpRepair', 'Total', 'Time', 'Address', 'CityState', 'Weather',
       'lighting', 'RoadSurface', 'RoadType', 'DriverAction', 'PoliceReport',
       'DotRecordable', 'Video', 'Preventable', 'ClaimStatus', 'ClaimAdj',
       'Notes', 'VmsAccidentNo', 'Year'],
      dtype='object')

In [65]:
acc2025renamed_df.head()

,ClaimNo,InsClaimNo,DriverName,EmployeeID,Department,UnitNo,AccidentDate,Description,Preventable,Injury,...,DriverAction,PoliceReport,DotRecordable,Video,Preventable,ClaimStatus,ClaimAdj,Notes,VmsAccidentNo,Year
0,Not Registered,Not Registered,Tashelia Murphy,Not Registered,School Bus,593,2025-01-08 00:00:00.000,I was stopped at the red light in a bit of tra...,no,No,...,"Stopped, Not Moving",Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
1,011825-331,Not Registered,Alesha Harney,Not Registered,Charter,331,2025-01-18 00:00:00.000,Cut to close to concrete barrier getting turne...,yes,No,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
2,012325-715,773848,Kimberly Perkins,Not Registered,RTA,715,2025-01-23 00:00:00.000,I was making a left turn on to Enterprise driv...,yes,Not Registered,...,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
3,012525-249,Not Registered,Dale Jaco,Not Registered,Charter,249,2025-01-25 00:00:00.000,I was parked on 21st Ave and a mini bus from ...,no,No,...,"Stopped, Not Moving",No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
4,012925-338,Not Registered,Lonnie McGee,Not Registered,Charter,338,2025-01-29 00:00:00.000,Murphy Athletic Center MTSU\n2650 Middle Tenne...,Yes,No,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025

In [28]:
accidents2025prevent_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   claimno                  35 non-null     object
 1   insclaimno               35 non-null     object
 2   drivername               35 non-null     object
 3   employeeid               35 non-null     object
 4   dept                     35 non-null     object
 5   unitno                   35 non-null     int64
 6   accidentdate             35 non-null     object
 7   description              35 non-null     object
 8   preventable?             35 non-null     object
 9   injury                   35 non-null     object
 10  loss_of_bonus_           35 non-null     object
 11  coaching                 35 non-null     object
 12  final___jerrys_estimate  35 non-null     object
 13  est                      35 non-null     object
 14  oprepair                 35 non-null     object
 15  total                    35 non-null     object
 16  time                     35 non-null     object
 17  address                  35 non-null     object
 18  citystate                35 non-null     object
 19  weather                  35 non-null     object
 20  lighting                 35 non-null     object
 21  roadsurface              35 non-null     object
 22  roadtype                 35 non-null     object
 23  driveraction             35 non-null     object
 24  policereport             35 non-null     object
 25  dotrecordable            35 non-null     object
 26  video                    35 non-null     object
 27  prev                     35 non-null     object
 28  status                   35 non-null     object
 29  claimadj                 35 non-null     object
 30  notes                    35 non-null     object
 31  vms_accident_no          35 non-null     object
dtypes: int64(1), object(31)
memory usage: 8.9+ KB

In [69]:
accidents2025_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no'],
      dtype='object')

In [39]:
acc2025prevrenamed_df = accidents2025_df.rename(columns = {'claimno':'ClaimNo', 'insclaimno':'InsClaimNo', 'drivername':'DriverName','employeeid':'EmployeeID', \
                                                       'dept' : 'Department', 'unitno' : 'UnitNo', 'accidentdate':'AccidentDate', 'description':'Description','preventable?':'Preventable', \
                                                      'injury':'Injury', 'loss_of_bonus_':'LossOfBonus', 'coaching':'Coaching', 'final___jerrys_estimate':'FinalJerrysEstimate','est':'Estimate','oprepair':'OpRepair', \
                                                      'total':'Total','time':'Time', 'address':'Address', 'citystate':'CityState', 'weather':'Weather',\
                                                       'lightning':'Lightning', 'roadsurface':'RoadSurface', 'roadtype':'RoadType', 'driveraction':'DriverAction', 'policereport':'PoliceReport',\
                                                       'dotrecordable' : 'DotRecordable', 'video':'Video','prev':'Preventable', 'status' : 'ClaimStatus', 'claimadj':'ClaimAdj', 'notes':'Notes', \
                                                      'vms_accident_no':'VmsAccidentNo'})

In [66]:
acc2025prevrenamed_df['Year']=2025

In [79]:
acc2025prevrenamed_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'EmployeeID', 'Department',
       'UnitNo', 'AccidentDate', 'Description', 'Preventable', 'Injury',
       'LossOfBonus', 'Coaching', 'FinalJerrysEstimate', 'Estimate',
       'OpRepair', 'Total', 'Time', 'Address', 'CityState', 'Weather',
       'lighting', 'RoadSurface', 'RoadType', 'DriverAction', 'PoliceReport',
       'DotRecordable', 'Video', 'Preventable', 'ClaimStatus', 'ClaimAdj',
       'Notes', 'VmsAccidentNo', 'Year'],
      dtype='object')

In [70]:
acc2025prevrenamed_df.head()

,ClaimNo,InsClaimNo,DriverName,EmployeeID,Department,UnitNo,AccidentDate,Description,Preventable,Injury,...,DriverAction,PoliceReport,DotRecordable,Video,Preventable,ClaimStatus,ClaimAdj,Notes,VmsAccidentNo,Year
0,Not Registered,Not Registered,Tashelia Murphy,Not Registered,School Bus,593,2025-01-08 00:00:00.000,I was stopped at the red light in a bit of tra...,no,No,...,"Stopped, Not Moving",Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
1,011825-331,Not Registered,Alesha Harney,Not Registered,Charter,331,2025-01-18 00:00:00.000,Cut to close to concrete barrier getting turne...,yes,No,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
2,012325-715,773848,Kimberly Perkins,Not Registered,RTA,715,2025-01-23 00:00:00.000,I was making a left turn on to Enterprise driv...,yes,Not Registered,...,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
3,012525-249,Not Registered,Dale Jaco,Not Registered,Charter,249,2025-01-25 00:00:00.000,I was parked on 21st Ave and a mini bus from ...,no,No,...,"Stopped, Not Moving",No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
4,012925-338,Not Registered,Lonnie McGee,Not Registered,Charter,338,2025-01-29 00:00:00.000,Murphy Athletic Center MTSU\n2650 Middle Tenne...,Yes,No,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025

In [68]:
acc2025prevrenamed_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'EmployeeID', 'Department',
       'UnitNo', 'AccidentDate', 'Description', 'Preventable', 'Injury',
       'LossOfBonus', 'Coaching', 'FinalJerrysEstimate', 'Estimate',
       'OpRepair', 'Total', 'Time', 'Address', 'CityState', 'Weather',
       'lighting', 'RoadSurface', 'RoadType', 'DriverAction', 'PoliceReport',
       'DotRecordable', 'Video', 'Preventable', 'ClaimStatus', 'ClaimAdj',
       'Notes', 'VmsAccidentNo', 'Year'],
      dtype='object')

In [32]:
graylinefleet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   vms-id                325 non-null    object
 1   fleetno               325 non-null    object
 2   vin                   325 non-null    object
 3   modelyear             325 non-null    object
 4   fleet_age             325 non-null    object
 5   fleet_age_sort        325 non-null    int64
 6   current_fleet_status  325 non-null    object
 7   license_plate         325 non-null    object
 8   vms_type              325 non-null    object
 9   dept                  325 non-null    object
 10  make                  325 non-null    object
 11  model                 325 non-null    object
 12  pax                   325 non-null    object
dtypes: int64(1), object(12)
memory usage: 33.1+ KB