In [1]:
#pip install pandas openpyxl
import sys
!{sys.executable} -m pip install openpyxl
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: openpyxl in c:\users\malan\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\malan\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [2]:
import os
print(os.listdir('data'))

['2018 Accident Incident Report.xlsx', '2019 Accident Report.xlsx', '2020 Accident Report.xlsx', '2021 Accident Report.xlsx', 'accidents_2024.csv', 'accidents_2025.csv', 'accidents_2025_preventable_addition.csv', 'finaloutput1.csv', 'grayline_fleet_vehicles.csv']

In [3]:
accidents2018_df = pd.read_excel('data/2018 Accident Incident Report.xlsx', sheet_name = 'Sheet1',skiprows=[0,1,116,117,118,119], engine='openpyxl')
accidents2019_df = pd.read_excel('data/2019 Accident Report.xlsx',sheet_name = 'DRIVER FAULT', skiprows=1, skipfooter=5, engine='openpyxl')
accidents2020_df = pd.read_excel('data/2020 Accident Report.xlsx', sheet_name = 'Master', engine='openpyxl')
accidents2021_df = pd.read_excel('data/2021 Accident Report.xlsx', sheet_name = 'Master', engine='openpyxl')
accidents2024_df = pd.read_csv('data/accidents_2024.csv')
accidents2025_df = pd.read_csv('data/accidents_2025.csv')
accidents2025prevent_df = pd.read_csv('data/accidents_2025_preventable_addition.csv')
graylinefleet_df = pd.read_csv('data/grayline_fleet_vehicles.csv')

In [4]:
accidents2018_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 22 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Claim #                                          126 non-null    object
 1   Employee Name                                    127 non-null    object
 2   Dept.                                            115 non-null    object
 3   Date Occurred                                    126 non-null    datetime64[ns]
 4   Incident / Accident                              125 non-null    object
 5   DOT Recordable?                                  125 non-null    object
 6   Unit No.                                         119 non-null    object
 7   Description                                      122 non-null    object
 8   GL Driver                                        68 non-null     object
 9   NON GL Driver                                    32 non-null     object
 10  GL Employee                                      117 non-null    object
 11  NON GL Employee                                  113 non-null    object
 12  Ins. Notified                                    110 non-null    object
 13  In-House, Protective, or Other Driver/Insuance   99 non-null     object
 14  Jerry's $ GL Bus Repair                          10 non-null     float64
 15  Quote                                            2 non-null      float64
 16  Cost for other vehicle repair                    8 non-null      float64
 17  Actual                                           0 non-null      float64
 18  Police Report                                    64 non-null     object
 19  Drive Cam?                                       53 non-null     object
 20  Safety Committee Ruling                          61 non-null     object
 21  Status                                           66 non-null     object
dtypes: datetime64[ns](1), float64(4), object(17)
memory usage: 22.0+ KB

In [5]:
accidents2018_df.columns

Index(['Claim #', 'Employee Name', 'Dept.', 'Date Occurred ',
       'Incident / Accident', 'DOT Recordable?', 'Unit No.', 'Description',
       'GL Driver', 'NON GL Driver ', 'GL Employee', 'NON GL Employee',
       'Ins. Notified', 'In-House, Protective, or Other Driver/Insuance ',
       'Jerry's $ GL Bus Repair ', 'Quote', 'Cost for other vehicle repair',
       'Actual', 'Police Report', 'Drive Cam?', 'Safety Committee Ruling',
       'Status'],
      dtype='object')

In [6]:
acc2018renamed_df = accidents2018_df.rename(columns = {'Claim #':'ClaimNo', 'Employee Name':'DriverName', 'Dept.':'Department', 'Date Occurred ':'AccidentDate', \
                                                      'Incident / Accident':'IncidentAccident','Description':'Description','Unit No.':'UnitNo', 'GL Driver':'GLDriver', \
                                                      'NON GL Driver ':'NonGLDriver', 'GL Employee':'GLEmployeeInjury', 'NON GL Employee':'NonGLEmployeeInjury', \
                                                      "Jerry's $ GL Bus Repair ":'JerrysGLBusRepair', \
                                                      'Ins. Notified':'InsNotified', 'In-House, Protective, or Other Driver/Insuance ':'ClaimType', 'Quote':'Quote', \
                                                     'Actual':'Actual', 'Cost for other vehicle repair':'CostForOtherVehicleRepoair', 'Police Report':'PoliceReport', \
                                                      'Drive Cam?':'DriveCam', 'Safety Committee Ruling':'SafetyCommRuling','DOT Recordable?':'DOT Recordable', \
                                                      'Status':'ClaimStatus'})

In [7]:
acc2018renamed_df['Year'] = 2018

In [8]:
acc2018renamed_df.head()

,ClaimNo,DriverName,Department,AccidentDate,IncidentAccident,DOT Recordable,UnitNo,Description,GLDriver,NonGLDriver,...,ClaimType,JerrysGLBusRepair,Quote,CostForOtherVehicleRepoair,Actual,PoliceReport,DriveCam,SafetyCommRuling,ClaimStatus,Year
0,010318-533,Brittney Patterson,School Bus,2018-01-04,Incident,Non-DOT,533,"Driver hit a sign, no damage reported",X,NaN,...,In-House,NaN,NaN,NaN,NaN,N,N,Preventable,Closed,2018
1,010718-1015,Scott Wangrud,Charter,2018-01-07,Incident,Non-DOT,1015,Supposedly hit an Anchor Bus' mirror,X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,N,Preventable,Closed,2018
2,011518-1021,Thomas House,Charter,2018-01-15,Accident,Non-DOT,1021,Driver hit a sign,X,NaN,...,In-House,3185.35,NaN,NaN,NaN,N,N,Preventable,Closed,2018
3,011618-1015,David Armstrong,Charter,2018-01-16,Accident,Non-DOT,1015,Bus slid into concrete light pole. Parking lot...,NaN,X,...,In-House,NaN,NaN,NaN,NaN,N,N,Non-Preventable,Closed,2018
4,011918-232,William Moncrief,Tour,2018-01-19,Accident,Non-DOT,232,Our bus was hit by Freeman Trucking. Right sid...,NaN,X,...,OP Ins,NaN,NaN,NaN,NaN,Y,N,Non-Preventable,Open,2018

In [9]:
acc2018renamed_df.columns

Index(['ClaimNo', 'DriverName', 'Department', 'AccidentDate',
       'IncidentAccident', 'DOT Recordable', 'UnitNo', 'Description',
       'GLDriver', 'NonGLDriver', 'GLEmployeeInjury', 'NonGLEmployeeInjury',
       'InsNotified', 'ClaimType', 'JerrysGLBusRepair', 'Quote',
       'CostForOtherVehicleRepoair', 'Actual', 'PoliceReport', 'DriveCam',
       'SafetyCommRuling', 'ClaimStatus', 'Year'],
      dtype='object')

In [10]:
accidents2019_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Claim #                  154 non-null    object
 1   Other Claim #            27 non-null     object
 2   Driver                   154 non-null    object
 3   Dept.                    154 non-null    object
 4   Unit #                   154 non-null    object
 5   Date                     154 non-null    datetime64[ns]
 6   Description              154 non-null    object
 7   GL Driver                154 non-null    object
 8   NON GL Driver            154 non-null    object
 9   GL Employee              154 non-null    object
 10  NON GL Employee          154 non-null    object
 11  Ins Notified?            154 non-null    object
 12  In-House/Ins             154 non-null    object
 13  GL Repair Cost           145 non-null    object
 14  3rd Party Cost           34 non-null     float64
 15  Ins Fees                 153 non-null    float64
 16  Time                     153 non-null    object
 17  Location                 153 non-null    object
 18  Weather                  154 non-null    object
 19  Lighting                 153 non-null    object
 20  Road Surface             154 non-null    object
 21  Road Type                153 non-null    object
 22  Control Device           55 non-null     object
 23  Driver Experience        153 non-null    object
 24  Raduis                   152 non-null    object
 25  Police Report            153 non-null    object
 26  DOT Recordable?          153 non-null    object
 27  Drive Cam?               153 non-null    object
 28  Safety Committee Ruling  153 non-null    object
 29  Status                   154 non-null    object
dtypes: datetime64[ns](1), float64(2), object(27)
memory usage: 36.2+ KB

In [11]:
accidents2019_df.columns

Index(['Claim #', 'Other Claim #', 'Driver', 'Dept.', 'Unit #', 'Date',
       'Description', 'GL Driver', 'NON GL Driver ', 'GL Employee',
       'NON GL Employee', 'Ins Notified?', 'In-House/Ins ', 'GL Repair Cost ',
       '3rd Party Cost', 'Ins Fees', 'Time', 'Location', 'Weather', 'Lighting',
       'Road Surface', 'Road Type', 'Control Device', 'Driver Experience',
       'Raduis', 'Police Report', 'DOT Recordable?', 'Drive Cam?',
       'Safety Committee Ruling', 'Status'],
      dtype='object')

In [12]:
acc2019renamed_df = accidents2019_df.rename(columns = {'Claim #':'ClaimNo', 'Other Claim #':'InsClaimNo', 'Driver':'DriverName', \
                                                      'Dept.':'Department', 'Unit #':'UnitNo', 'Date':'AccidentDate', 'Description':'Description', \
                                                      'GL Driver':'GLDriver','NON GL Driver ':'NonGLDriver','GL Employee':'GLEmployeeInjury', \
                                                      'NON GL Employee':'NonGLEmployeeInjury', \
                                                      'Ins Notified?':'InsNotified', \
                                                      'In-House/Ins ':'ClaimType', 'GL Repair Cost':'GLRepairCost', '3rd Party Cost':'3rdPartyCost',\
                                                      'INS Fees':'InsFee', 'Road Surface':'RoadSurface', 'Road Type':'RoadType', 'Control Device':'ControlDevice', \
                                                      'Driver Experience':'DriverExperience', 'Radius':'Radius', 'Police Report':'PoliceReport', \
                                                      'DOT Recordable?':'DOT Recordable', 'Drive Cam?':'DriveCam', 'Safety Committee Ruling':'SafetyCommRuling', \
                                                      'Status':'ClaimStatus'})

In [13]:
acc2019renamed_df['Year'] = 2019

In [14]:
acc2019renamed_df.head()

,ClaimNo,InsClaimNo,DriverName,Department,UnitNo,AccidentDate,Description,GLDriver,NonGLDriver,GLEmployeeInjury,...,RoadType,ControlDevice,DriverExperience,Raduis,PoliceReport,DOT Recordable,DriveCam,SafetyCommRuling,ClaimStatus,Year
0,010719-003,NaN,Jerry Mischler,Shop,7,2019-01-07,GL Mechanic hit another vehicle in an intersec...,Y,N,N,...,Straight,Traffic Light,N,0-50,Y,Y,N,N,Open,2019
1,011719-616,NaN,Rawand Koyee,SB,616,2019-01-17,Backed into 565 front passenger window,Y,N,N,...,N,N,3-4 Years,N,N,N,N,N,N,2019
2,011719-1021,NaN,Shawn Yokley,C,1021,2019-01-17,hooked back bumper on a cement pole,Y,N,N,...,N,N,6-11 MThs,N,N,N,N,N,N,2019
3,012019-727,NaN,James Johnson,BC,4727,2019-01-20,Hit pole in garage on right side,Y,N,N,...,N,N,1-2 Yrs,N,N,N,N,N,N,2019
4,012719-1023,NaN,Sadie Demoss,SS,1023,2019-01-27,driver backed 1023 into 243 mirror,Y,N,N,...,N,N,5+ Yrs,N,N,N,N,N,N,2019

In [15]:
acc2019renamed_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'Department', 'UnitNo',
       'AccidentDate', 'Description', 'GLDriver', 'NonGLDriver',
       'GLEmployeeInjury', 'NonGLEmployeeInjury', 'InsNotified', 'ClaimType',
       'GL Repair Cost ', '3rdPartyCost', 'Ins Fees', 'Time', 'Location',
       'Weather', 'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'PoliceReport', 'DOT Recordable',
       'DriveCam', 'SafetyCommRuling', 'ClaimStatus', 'Year'],
      dtype='object')

In [16]:
accidents2020_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CLAIM NUMBER          50 non-null     object
 1   CLAIM NUMBER2         50 non-null     int64
 2   DRIVER NAME           50 non-null     object
 3   EMPLOYEE ID           50 non-null     int64
 4   DEPARTMENT            50 non-null     object
 5   UNIT NO               50 non-null     int64
 6   ACC DATE              50 non-null     datetime64[ns]
 7   DESCRIPTION           50 non-null     object
 8   DRIVER INJURED        50 non-null     bool
 9   OP INJURED            50 non-null     bool
 10  CLAIM TYPE            49 non-null     object
 11  GL BUS ESTIMATE       50 non-null     float64
 12  GL BUS REPAIR         50 non-null     float64
 13  GL FINAL COST         50 non-null     float64
 14  OP REPAIR COST        50 non-null     float64
 15  INS FEE               50 non-null     int64
 16  OP INS PAID TO GL     50 non-null     float64
 17  INSURANCE DEDUCTIBLE  50 non-null     int64
 18  TOTAL                 50 non-null     float64
 19  TIME                  50 non-null     object
 20  LOCATION              50 non-null     object
 21  WEATHER               50 non-null     object
 22  LIGHTING              50 non-null     object
 23  ROAD SURFACE          50 non-null     object
 24  ROAD TYPE             50 non-null     object
 25  DRIVER ACTION         50 non-null     object
 26  DRIVER EXPERIENCE     50 non-null     float64
 27  RADIUS                50 non-null     object
 28  POLICE REPORT         50 non-null     bool
 29  DOT RECORDABLE        50 non-null     bool
 30  VIDEO                 50 non-null     bool
 31  PREVENTABLE?          50 non-null     bool
 32  STATUS                50 non-null     object
dtypes: bool(6), datetime64[ns](1), float64(7), int64(5), object(14)
memory usage: 11.0+ KB

In [17]:
accidents2020_df.columns

Index(['CLAIM NUMBER', 'CLAIM NUMBER2', 'DRIVER NAME', 'EMPLOYEE ID',
       'DEPARTMENT', 'UNIT NO', 'ACC DATE', 'DESCRIPTION', 'DRIVER INJURED',
       'OP INJURED', 'CLAIM TYPE', 'GL BUS ESTIMATE', 'GL BUS REPAIR',
       'GL FINAL COST', 'OP REPAIR COST', 'INS FEE', 'OP INS PAID TO GL',
       'INSURANCE DEDUCTIBLE', 'TOTAL', 'TIME', 'LOCATION', 'WEATHER',
       'LIGHTING', 'ROAD SURFACE', 'ROAD TYPE', 'DRIVER ACTION',
       'DRIVER EXPERIENCE', 'RADIUS', 'POLICE REPORT', 'DOT RECORDABLE',
       'VIDEO', 'PREVENTABLE?', 'STATUS'],
      dtype='object')

In [18]:
acc2020renamed_df = accidents2020_df.rename(columns = {'CLAIM NUMBER' : 'ClaimNo', 'CLAIM NUMBER2' : 'InsClaimNo', 'DRIVER NAME' : 'DriverName',\
                                                      'EMPLOYEE ID' : 'EmployeeId',  'DEPARTMENT' : 'Department', 'ACC DATE': 'AccidentDate', \
                                                      'DESCRIPTION' : 'Description', 'DRIVER INJURED' : 'DriverInjured', 'OP INJURED' : 'OpInjured', \
                                                      'CLAIM TYPE' : 'ClaimType', 'GL BUS ESTIMATE' : 'GLBusEstimate', 'GL BUS REPAIR' : 'GLBusRepair', \
                                                      'OP REPAIR COST' : 'OpRepairCost', 'INS FEE' : 'InsFee', 'OP INS PAID TO GL' : 'OpInsPaid', \
                                                      'INSURANCE DEDUCTIBLE' : 'InsDeductable', 'TOTAL' : 'Total', 'Time' : 'Time', 'LOCATION' : 'Location', \
                                                      'WEATHER' : 'Weather', 'LIGHTING' : 'Lighting', 'ROAD SURFACE' : 'RoadSurface', 'ROAD TYPE' : 'RoadType', \
                                                      'DRIVER ACTION' : 'DriverAction','DRIVER EXPERIENCE' : 'DriverExperience', 'RADIUS' : 'Radius', \
                                                      'POLICE REPORT' : 'PoliceReport', 'DOT RECORDABLE' : 'DOT Recordable', 'VIDEO' : 'Video',\
                                                      'PREVENTABLE?' : 'Preventable', 'STATUS' : 'ClaimStatus', 'UNIT NO' : 'UnitNo'})

In [19]:
acc2020renamed_df['Year'] = 2020

In [20]:
acc2020renamed_df.head()

,ClaimNo,InsClaimNo,DriverName,EmployeeId,Department,UnitNo,AccidentDate,Description,DriverInjured,OpInjured,...,RoadType,DriverAction,DriverExperience,Radius,PoliceReport,DOT Recordable,Video,Preventable,ClaimStatus,Year
0,010620-246,0,Alesha Harney,11038,Charter,246,2020-01-06,car hit the front bumper of the bus - scuffed ...,False,False,...,Parking Lot,Stop Sign,7.0,0-50,False,False,False,False,CLOSED,2020
1,010820-214,0,Kelly Westerlund,10979,Sightseeing,214,2020-01-08,"driver hit a service truck turning right, bus ...",False,False,...,Residential Street,turning right,1.0,0-50,True,False,False,True,CLOSED,2020
2,010920-1019,767903,Robert Kimbrell,10346,Charter,1019,2020-01-09,driver clipped a college student when she drov...,False,False,...,Residential Street,N,30.0,0-50,True,False,False,True,CLOSED,2020
3,010920-1019,0,Robert Kimbrell,10346,Charter,1019,2020-01-09,driver failed to set brake and bus rolled into...,False,False,...,Parking Lot,stopped,30.0,0-50,False,False,True,True,CLOSED,2020
4,011020-721,767935,Michael Beattie,10039,RTA,721,2020-01-10,hit OP right rear fender turning left at Charl...,False,False,...,Intersection,turning left,33.0,0-50,True,False,False,True,CLOSED,2020

In [21]:
acc2020renamed_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'EmployeeId', 'Department',
       'UnitNo', 'AccidentDate', 'Description', 'DriverInjured', 'OpInjured',
       'ClaimType', 'GLBusEstimate', 'GLBusRepair', 'GL FINAL COST',
       'OpRepairCost', 'InsFee', 'OpInsPaid', 'InsDeductable', 'Total', 'TIME',
       'Location', 'Weather', 'Lighting', 'RoadSurface', 'RoadType',
       'DriverAction', 'DriverExperience', 'Radius', 'PoliceReport',
       'DOT Recordable', 'Video', 'Preventable', 'ClaimStatus', 'Year'],
      dtype='object')

In [22]:
accidents2021_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ClaimNo          92 non-null     object
 1   InsClaimNo       91 non-null     float64
 2   DRIVERNAME       97 non-null     object
 3   EmployeeID       18 non-null     float64
 4   DEPT             96 non-null     object
 5   UnitNo           96 non-null     object
 6   AccidentDate     97 non-null     datetime64[ns]
 7   DESCRIPTION      97 non-null     object
 8   OPFAULT          87 non-null     float64
 9   INJURY           93 non-null     object
 10  ClaimType        37 non-null     object
 11  GLEstimate       18 non-null     float64
 12  Final            18 non-null     float64
 13  OPRepair         19 non-null     float64
 14  Total            97 non-null     float64
 15  TIME             95 non-null     object
 16  LOCATION         83 non-null     object
 17  CityState        43 non-null     object
 18  WEATHER          94 non-null     object
 19  LIGHTING         94 non-null     object
 20  RoadSurface      94 non-null     object
 21  RoadType         94 non-null     object
 22  DriverAction     94 non-null     object
 23  PoliceReport     82 non-null     object
 24  DOTRecordable    95 non-null     object
 25  VIDEO            14 non-null     object
 26  PREV             18 non-null     object
 27  STATUS           18 non-null     object
 28  ClaimAdj         2 non-null      object
 29  NOTES            20 non-null     object
 30  VMS Accident No  17 non-null     float64
dtypes: datetime64[ns](1), float64(8), object(22)
memory usage: 23.6+ KB

In [23]:
accidents2021_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DRIVERNAME', 'EmployeeID', 'DEPT', 'UnitNo',
       'AccidentDate', 'DESCRIPTION', 'OPFAULT', 'INJURY', 'ClaimType',
       'GLEstimate', 'Final', 'OPRepair', 'Total', 'TIME', 'LOCATION',
       'CityState', 'WEATHER', 'LIGHTING', 'RoadSurface', 'RoadType',
       'DriverAction', 'PoliceReport', 'DOTRecordable', 'VIDEO', 'PREV',
       'STATUS', 'ClaimAdj', 'NOTES', 'VMS Accident No'],
      dtype='object')

In [24]:
acc2021renamed_df = accidents2021_df.rename(columns = {'ClaimNo' : 'ClaimNo', 'InsClaimNo' : 'InsClaimNo', 'DRIVERNAME' : 'DriverName','EmployeeID' : 'EmployeeId', \
                                                      'DEPT' : 'Department', 'UnitNo' : 'UnitNo', 'DESCRIPTION' : 'Description', \
                                                      'OPFAULT' : 'OpFault', 'INJURY' : 'Injury', 'GL Estimate':'GLBusEstimate', 'OPRepair':'OpRepair',\
                                                      'TIME':'Time', 'LOCATION':'Location', 'WEATHER':'Weather', \
                                                      'LIGHTING':'Lighting', 'RoadSurface':'RoadSurface', 'RoadType':'RoadType', 'DriverAction':'DriverAction', \
                                                      'DOTRecordable' : 'DOT Recordable', 'VIDEO': 'Video', 'PREV':'Preventable', \
                                                      'Date Occured': 'AccidentDate', 'STATUS' : 'ClaimStatus', 'NOTES':'Notes', 'VMS Accident No':'VMSAccidentNo'})

In [25]:
acc2021renamed_df['Year'] = 2021

In [26]:
acc2021renamed_df.head(5)

,ClaimNo,InsClaimNo,DriverName,EmployeeId,Department,UnitNo,AccidentDate,Description,OpFault,Injury,...,DriverAction,PoliceReport,DOT Recordable,Video,Preventable,ClaimStatus,ClaimAdj,Notes,VMSAccidentNo,Year
0,011321-715,110.0,Elizabeth Burton,10086.0,RTA,715,2021-01-13,Penske truck hit passenger side mirror of bus ...,1.0,False,...,"Stopped, Not Moving",FALSE,FALSE,False,False,Open,NaN,Unscheduled activity id78458,110.0,2021
1,011421-280,111.0,Robert Schneider,11016.0,RTA,280,2021-01-14,a bobcat truck pulling a 36' to 40' constructi...,1.0,False,...,"Stopped, Not Moving",FALSE,FALSE,False,False,Open,NaN,UnscheduledActivity id 78478,111.0,2021
2,011721-329,112.0,Anthony Wells,10914.0,Charter,329,2021-01-17,"driver backed into a pay booth, rear screen o...",0.0,False,...,Right Turn,FALSE,FALSE,False,True,Open,NaN,driver submitted defect with description that ...,112.0,2021
3,011721-4101,768974.0,Sameh Shaker,10566.0,School Bus,4101,2021-01-17,Our bus was parked on the side of the road whe...,1.0,TRUE,...,"Stopped, Not Moving",TRUE,TRUE,False,False,Open,Lisa Carey,State Farm Claim No. 4215V715T - reported to L...,113.0,2021
4,011921-000,235957.0,Jenniefer Stephens,10597.0,Charter,0,2021-01-19,IW was closing tire cover when the bumper clos...,0.0,TRUE,...,"Stopped, Not Moving",False,False,False,True,Open,Tracy Robinson,Work Comp,NaN,2021

In [27]:
acc2021renamed_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'EmployeeId', 'Department',
       'UnitNo', 'AccidentDate', 'Description', 'OpFault', 'Injury',
       'ClaimType', 'GLEstimate', 'Final', 'OpRepair', 'Total', 'Time',
       'Location', 'CityState', 'Weather', 'Lighting', 'RoadSurface',
       'RoadType', 'DriverAction', 'PoliceReport', 'DOT Recordable', 'Video',
       'Preventable', 'ClaimStatus', 'ClaimAdj', 'Notes', 'VMSAccidentNo',
       'Year'],
      dtype='object')

In [28]:
accidents2024_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   claimno                  190 non-null    object
 1   insclaimno               190 non-null    object
 2   drivername               190 non-null    object
 3   employeeid               190 non-null    object
 4   dept                     190 non-null    object
 5   unitno                   190 non-null    object
 6   accidentdate             190 non-null    object
 7   description              190 non-null    object
 8   preventable?             190 non-null    object
 9   injury                   190 non-null    object
 10  loss_of_bonus_           190 non-null    object
 11  coaching                 190 non-null    object
 12  final___jerrys_estimate  190 non-null    object
 13  est                      190 non-null    object
 14  oprepair                 190 non-null    object
 15  total                    190 non-null    object
 16  time                     190 non-null    object
 17  address                  190 non-null    object
 18  citystate                190 non-null    object
 19  weather                  190 non-null    object
 20  lighting                 190 non-null    object
 21  roadsurface              190 non-null    object
 22  roadtype                 190 non-null    object
 23  driveraction             190 non-null    object
 24  policereport             190 non-null    object
 25  dotrecordable            190 non-null    object
 26  video                    190 non-null    object
 27  prev                     190 non-null    object
 28  status                   190 non-null    object
 29  claimadj                 190 non-null    object
 30  notes                    190 non-null    object
 31  vms_accident_no          190 non-null    object
dtypes: object(32)
memory usage: 47.6+ KB

In [29]:
accidents2024_df['Year'] = 2024

In [30]:
accidents2024_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no', 'Year'],
      dtype='object')

In [31]:
accidents2024_df.head()

,claimno,insclaimno,drivername,employeeid,dept,unitno,accidentdate,description,preventable?,injury,...,driveraction,policereport,dotrecordable,video,prev,status,claimadj,notes,vms_accident_no,Year
0,010124-311,Not Registered,Douglas Bumpus,5,Charter,311,2024-01-01 00:00:00.000,Turning in parking lot of Buccees hit a car.,yes,no,...,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
1,010524-319,Not Registered,Devon Whitmore,0-1,Charter,319,2024-01-05 00:00:00.000,"Backing bus into slot,fatigue driving back got...",yes,no,...,Backing,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
2,011124-312,Not Registered,Troy Fontechia,1-2,Charter,312,2024-01-11 00:00:00.000,Car nearly crashed pick up truck while merging...,no,No,...,Driving Forward,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
3,Not Registered,Not Registered,DERRICK Lowe,Not Registered,RTA,722,2024-01-18 00:00:00.000,Thursday is my day to get my Bus wash when i...,yes,Not Registered,...,Driving Forward,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Marker light,Not Registered,2024
4,012524-336,Not Registered,Estus Owens,5,Charter,336,2024-01-25 00:00:00.000,I was backing up at the Embassy suites downtow...,yes,no,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024

In [32]:
accidents2025_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   claimno                  57 non-null     object
 1   insclaimno               57 non-null     object
 2   drivername               57 non-null     object
 3   employeeid               57 non-null     object
 4   dept                     57 non-null     object
 5   unitno                   57 non-null     int64
 6   accidentdate             57 non-null     object
 7   description              57 non-null     object
 8   preventable?             57 non-null     object
 9   injury                   57 non-null     object
 10  loss_of_bonus_           57 non-null     object
 11  coaching                 57 non-null     object
 12  final___jerrys_estimate  57 non-null     object
 13  est                      57 non-null     object
 14  oprepair                 57 non-null     object
 15  total                    57 non-null     object
 16  time                     57 non-null     object
 17  address                  57 non-null     object
 18  citystate                57 non-null     object
 19  weather                  57 non-null     object
 20  lighting                 57 non-null     object
 21  roadsurface              57 non-null     object
 22  roadtype                 57 non-null     object
 23  driveraction             57 non-null     object
 24  policereport             57 non-null     object
 25  dotrecordable            57 non-null     object
 26  video                    57 non-null     object
 27  prev                     57 non-null     object
 28  status                   57 non-null     object
 29  claimadj                 57 non-null     object
 30  notes                    57 non-null     object
 31  vms_accident_no          57 non-null     object
dtypes: int64(1), object(31)
memory usage: 14.4+ KB

In [33]:
accidents2025_df['Year'] = 2025

In [34]:
accidents2025_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no', 'Year'],
      dtype='object')

In [35]:
accidents2025_df.head()

,claimno,insclaimno,drivername,employeeid,dept,unitno,accidentdate,description,preventable?,injury,...,driveraction,policereport,dotrecordable,video,prev,status,claimadj,notes,vms_accident_no,Year
0,Not Registered,Not Registered,Tashelia Murphy,Not Registered,School Bus,593,2025-01-08 00:00:00.000,I was stopped at the red light in a bit of tra...,no,No,...,"Stopped, Not Moving",Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
1,011825-331,Not Registered,Alesha Harney,Not Registered,Charter,331,2025-01-18 00:00:00.000,Cut to close to concrete barrier getting turne...,yes,No,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
2,012325-715,773848,Kimberly Perkins,Not Registered,RTA,715,2025-01-23 00:00:00.000,I was making a left turn on to Enterprise driv...,yes,Not Registered,...,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
3,012525-249,Not Registered,Dale Jaco,Not Registered,Charter,249,2025-01-25 00:00:00.000,I was parked on 21st Ave and a mini bus from ...,no,No,...,"Stopped, Not Moving",No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
4,012925-338,Not Registered,Lonnie McGee,Not Registered,Charter,338,2025-01-29 00:00:00.000,Murphy Athletic Center MTSU\n2650 Middle Tenne...,Yes,No,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025

In [36]:
accidents2025prevent_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   claimno                  35 non-null     object
 1   insclaimno               35 non-null     object
 2   drivername               35 non-null     object
 3   employeeid               35 non-null     object
 4   dept                     35 non-null     object
 5   unitno                   35 non-null     int64
 6   accidentdate             35 non-null     object
 7   description              35 non-null     object
 8   preventable?             35 non-null     object
 9   injury                   35 non-null     object
 10  loss_of_bonus_           35 non-null     object
 11  coaching                 35 non-null     object
 12  final___jerrys_estimate  35 non-null     object
 13  est                      35 non-null     object
 14  oprepair                 35 non-null     object
 15  total                    35 non-null     object
 16  time                     35 non-null     object
 17  address                  35 non-null     object
 18  citystate                35 non-null     object
 19  weather                  35 non-null     object
 20  lighting                 35 non-null     object
 21  roadsurface              35 non-null     object
 22  roadtype                 35 non-null     object
 23  driveraction             35 non-null     object
 24  policereport             35 non-null     object
 25  dotrecordable            35 non-null     object
 26  video                    35 non-null     object
 27  prev                     35 non-null     object
 28  status                   35 non-null     object
 29  claimadj                 35 non-null     object
 30  notes                    35 non-null     object
 31  vms_accident_no          35 non-null     object
dtypes: int64(1), object(31)
memory usage: 8.9+ KB

In [37]:
accidents2025prevent_df['Year'] = 2025

In [38]:
accidents2025prevent_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no', 'Year'],
      dtype='object')

In [39]:
accidents2025prevent_df.head()

,claimno,insclaimno,drivername,employeeid,dept,unitno,accidentdate,description,preventable?,injury,...,driveraction,policereport,dotrecordable,video,prev,status,claimadj,notes,vms_accident_no,Year
0,011825-331,Not Registered,Alesha Harney,Not Registered,Charter,331,2025-01-18 00:00:00.000,Cut to close to concrete barrier getting turne...,yes,No,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
1,012325-715,773848.0,Kimberly Perkins,Not Registered,RTA,715,2025-01-23 00:00:00.000,I was making a left turn on to Enterprise driv...,yes,Not Registered,...,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
2,012925-338,Not Registered,Lonnie McGee,Not Registered,Charter,338,2025-01-29 00:00:00.000,Murphy Athletic Center MTSU\n2650 Middle Tenne...,Yes,No,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
3,Not Registered,Not Registered,Lonnie McGee,Not Registered,Charter,338,2025-01-30 00:00:00.000,Got stuck in the mud. I was unable to turn bus...,yes,Not Registered,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
4,Not Registered,Not Registered,Thaddeus Nesby,Not Registered,RTA,727,2025-02-04 00:00:00.000,Coming around the corner of 21st Ave south and...,yes,No,...,Turning Right,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025

In [40]:
graylinefleet_df.columns

Index(['vms-id', 'fleetno', 'vin', 'modelyear', 'fleet_age', 'fleet_age_sort',
       'current_fleet_status', 'license_plate', 'vms_type', 'dept', 'make',
       'model', 'pax'],
      dtype='object')

In [41]:
graylinefleet_df.columns

Index(['vms-id', 'fleetno', 'vin', 'modelyear', 'fleet_age', 'fleet_age_sort',
       'current_fleet_status', 'license_plate', 'vms_type', 'dept', 'make',
       'model', 'pax'],
      dtype='object')

In [42]:
graylinefleetrenamed_df = graylinefleet_df.rename(columns = {'vms-id':'VMSId', 'fleetno':'FleetNo','vin':'VIN', 'modelyear':'ModelYear', 'fleet_age':'FleetAge', \
                                                                    'fleet_age_sort':'FleetAgeSort', 'current_fleet_status':'CurrenFleetStatus', \
                                                                    'license_plate':'LicensePlate', 'vms_type':'VMSType', 'dept':'Department', \
                                                                    'make':'Make', 'model':'Model', 'pax':'Pax'})

In [43]:
graylinefleetrenamed_df.head()

,VMSId,FleetNo,VIN,ModelYear,FleetAge,FleetAgeSort,CurrenFleetStatus,LicensePlate,VMSType,Department,Make,Model,Pax
0,1025,1025,1FDUF5GN8NEF91666,2023,2-7 Years Old,2,ACTIVE,CB61886,Mini-Coach 33 Pax,Charter,Glaval,Entourage,33.0
1,1026,1026,1FDUF5GNXNEF91670,2023,2-7 Years Old,2,ACTIVE,CB61887,Mini-Coach 33 Pax,Charter,Glaval,Entourage,33.0
2,1027,1027,1FDUF5GN1NEF91671,2023,2-7 Years Old,2,ACTIVE,CB61888,Mini-Coach 33 Pax,Charter,Glaval,Entourage,33.0
3,1028,1028,1FDUF5GN7NEF91674,2023,2-7 Years Old,2,ACTIVE,CB61889,Mini-Coach 33 Pax,Charter,Glaval,Entourage,33.0
4,1029,1029,1FDUF5GN9NDA26431,2023,2-7 Years Old,2,ACTIVE,CB61890,Mini-Coach 33 Pax,Charter,Glaval,Entourage,33.0

In [44]:
graylinefleetrenamed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   VMSId              325 non-null    object
 1   FleetNo            325 non-null    object
 2   VIN                325 non-null    object
 3   ModelYear          325 non-null    object
 4   FleetAge           325 non-null    object
 5   FleetAgeSort       325 non-null    int64
 6   CurrenFleetStatus  325 non-null    object
 7   LicensePlate       325 non-null    object
 8   VMSType            325 non-null    object
 9   Department         325 non-null    object
 10  Make               325 non-null    object
 11  Model              325 non-null    object
 12  Pax                325 non-null    object
dtypes: int64(1), object(12)
memory usage: 33.1+ KB

## Merging all 4 xlxs files into one file

In [45]:
merged_df = pd.concat([acc2018renamed_df, acc2019renamed_df,acc2020renamed_df,acc2021renamed_df], ignore_index=True, axis=0)

In [46]:
merged_df.columns

Index(['ClaimNo', 'DriverName', 'Department', 'AccidentDate',
       'IncidentAccident', 'DOT Recordable', 'UnitNo', 'Description',
       'GLDriver', 'NonGLDriver', 'GLEmployeeInjury', 'NonGLEmployeeInjury',
       'InsNotified', 'ClaimType', 'JerrysGLBusRepair', 'Quote',
       'CostForOtherVehicleRepoair', 'Actual', 'PoliceReport', 'DriveCam',
       'SafetyCommRuling', 'ClaimStatus', 'Year', 'InsClaimNo',
       'GL Repair Cost ', '3rdPartyCost', 'Ins Fees', 'Time', 'Location',
       'Weather', 'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'EmployeeId', 'DriverInjured',
       'OpInjured', 'GLBusEstimate', 'GLBusRepair', 'GL FINAL COST',
       'OpRepairCost', 'InsFee', 'OpInsPaid', 'InsDeductable', 'Total', 'TIME',
       'DriverAction', 'Radius', 'Video', 'Preventable', 'OpFault', 'Injury',
       'GLEstimate', 'Final', 'OpRepair', 'CityState', 'ClaimAdj', 'Notes',
       'VMSAccidentNo'],
      dtype='object')

In [47]:
merged_df.head()

,ClaimNo,DriverName,Department,AccidentDate,IncidentAccident,DOT Recordable,UnitNo,Description,GLDriver,NonGLDriver,...,Preventable,OpFault,Injury,GLEstimate,Final,OpRepair,CityState,ClaimAdj,Notes,VMSAccidentNo
0,010318-533,Brittney Patterson,School Bus,2018-01-04,Incident,Non-DOT,533,"Driver hit a sign, no damage reported",X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,010718-1015,Scott Wangrud,Charter,2018-01-07,Incident,Non-DOT,1015,Supposedly hit an Anchor Bus' mirror,X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,011518-1021,Thomas House,Charter,2018-01-15,Accident,Non-DOT,1021,Driver hit a sign,X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,011618-1015,David Armstrong,Charter,2018-01-16,Accident,Non-DOT,1015,Bus slid into concrete light pole. Parking lot...,NaN,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,011918-232,William Moncrief,Tour,2018-01-19,Accident,Non-DOT,232,Our bus was hit by Freeman Trucking. Right sid...,NaN,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
merged_df.columns

Index(['ClaimNo', 'DriverName', 'Department', 'AccidentDate',
       'IncidentAccident', 'DOT Recordable', 'UnitNo', 'Description',
       'GLDriver', 'NonGLDriver', 'GLEmployeeInjury', 'NonGLEmployeeInjury',
       'InsNotified', 'ClaimType', 'JerrysGLBusRepair', 'Quote',
       'CostForOtherVehicleRepoair', 'Actual', 'PoliceReport', 'DriveCam',
       'SafetyCommRuling', 'ClaimStatus', 'Year', 'InsClaimNo',
       'GL Repair Cost ', '3rdPartyCost', 'Ins Fees', 'Time', 'Location',
       'Weather', 'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'EmployeeId', 'DriverInjured',
       'OpInjured', 'GLBusEstimate', 'GLBusRepair', 'GL FINAL COST',
       'OpRepairCost', 'InsFee', 'OpInsPaid', 'InsDeductable', 'Total', 'TIME',
       'DriverAction', 'Radius', 'Video', 'Preventable', 'OpFault', 'Injury',
       'GLEstimate', 'Final', 'OpRepair', 'CityState', 'ClaimAdj', 'Notes',
       'VMSAccidentNo'],
      dtype='object')

In [49]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 61 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ClaimNo                     422 non-null    object
 1   DriverName                  428 non-null    object
 2   Department                  415 non-null    object
 3   AccidentDate                427 non-null    datetime64[ns]
 4   IncidentAccident            125 non-null    object
 5   DOT Recordable              423 non-null    object
 6   UnitNo                      419 non-null    object
 7   Description                 423 non-null    object
 8   GLDriver                    222 non-null    object
 9   NonGLDriver                 186 non-null    object
 10  GLEmployeeInjury            271 non-null    object
 11  NonGLEmployeeInjury         267 non-null    object
 12  InsNotified                 264 non-null    object
 13  ClaimType                   339 non-null    object
 14  JerrysGLBusRepair           10 non-null     float64
 15  Quote                       2 non-null      float64
 16  CostForOtherVehicleRepoair  8 non-null      float64
 17  Actual                      0 non-null      float64
 18  PoliceReport                349 non-null    object
 19  DriveCam                    206 non-null    object
 20  SafetyCommRuling            214 non-null    object
 21  ClaimStatus                 288 non-null    object
 22  Year                        428 non-null    int64
 23  InsClaimNo                  168 non-null    object
 24  GL Repair Cost              145 non-null    object
 25  3rdPartyCost                34 non-null     float64
 26  Ins Fees                    153 non-null    float64
 27  Time                        248 non-null    object
 28  Location                    286 non-null    object
 29  Weather                     298 non-null    object
 30  Lighting                    297 non-null    object
 31  RoadSurface                 298 non-null    object
 32  RoadType                    297 non-null    object
 33  ControlDevice               55 non-null     object
 34  DriverExperience            203 non-null    object
 35  Raduis                      152 non-null    object
 36  EmployeeId                  68 non-null     float64
 37  DriverInjured               50 non-null     object
 38  OpInjured                   50 non-null     object
 39  GLBusEstimate               50 non-null     float64
 40  GLBusRepair                 50 non-null     float64
 41  GL FINAL COST               50 non-null     float64
 42  OpRepairCost                50 non-null     float64
 43  InsFee                      50 non-null     float64
 44  OpInsPaid                   50 non-null     float64
 45  InsDeductable               50 non-null     float64
 46  Total                       147 non-null    float64
 47  TIME                        50 non-null     object
 48  DriverAction                144 non-null    object
 49  Radius                      50 non-null     object
 50  Video                       64 non-null     object
 51  Preventable                 68 non-null     object
 52  OpFault                     87 non-null     float64
 53  Injury                      93 non-null     object
 54  GLEstimate                  18 non-null     float64
 55  Final                       18 non-null     float64
 56  OpRepair                    19 non-null     float64
 57  CityState                   43 non-null     object
 58  ClaimAdj                    2 non-null      object
 59  Notes                       20 non-null     object
 60  VMSAccidentNo               17 non-null     float64
dtypes: datetime64[ns](1), float64(20), int64(1), object(39)
memory usage: 204.1+ KB

## Merging csv files into one file

In [50]:
#combined_df = pd.concat([df1, df2, df3], ignore_index=True, sort=False)
#merged1_df = pd.concat([acc2024renamed_df, acc2025renamed_df],ignore_index=True, sort=False)
merged1_df = pd.concat([accidents2024_df, accidents2025_df], ignore_index=True, axis=0)

In [51]:
merged1_df

,claimno,insclaimno,drivername,employeeid,dept,unitno,accidentdate,description,preventable?,injury,...,driveraction,policereport,dotrecordable,video,prev,status,claimadj,notes,vms_accident_no,Year
0,010124-311,Not Registered,Douglas Bumpus,5,Charter,311,2024-01-01 00:00:00.000,Turning in parking lot of Buccees hit a car.,yes,no,...,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
1,010524-319,Not Registered,Devon Whitmore,0-1,Charter,319,2024-01-05 00:00:00.000,"Backing bus into slot,fatigue driving back got...",yes,no,...,Backing,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
2,011124-312,Not Registered,Troy Fontechia,1-2,Charter,312,2024-01-11 00:00:00.000,Car nearly crashed pick up truck while merging...,no,No,...,Driving Forward,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
3,Not Registered,Not Registered,DERRICK Lowe,Not Registered,RTA,722,2024-01-18 00:00:00.000,Thursday is my day to get my Bus wash when i...,yes,Not Registered,...,Driving Forward,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Marker light,Not Registered,2024
4,012524-336,Not Registered,Estus Owens,5,Charter,336,2024-01-25 00:00:00.000,I was backing up at the Embassy suites downtow...,yes,no,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,Not Registered,Not Registered,Brian Grimes,Not Registered,Charter,726,2025-05-04 00:00:00.000,As I was driving thru a construction 🚧 I was ...,yes,No,...,Driving Forward,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
243,Not Registered,Not Registered,Jerome Asbury,Not Registered,Charter,327,2025-05-04 00:00:00.000,As I turned onto Junior Gilliam Way from Rep J...,yes,No,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
244,Not Registered,Not Registered,Todd Stevens,Not Registered,RTA,724,2025-05-07 00:00:00.000,Backed into parked bus,yes,Not Registered,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
245,Not Registered,Not Registered,Donald Hillaker,Not Registered,School Bus,505,2025-05-08 00:00:00.000,Vehicle hit the mirror of a parked truck,yes,No,...,Not Registered,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
246,Not Registered,Not Registered,Lonnie McGee,Not Registered,Charter,328,2025-05-11 00:00:00.000,A passenger was unconscious so I called 911 fo...,Not Registered,Yes,...,Not Registered,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025

In [52]:
merged1_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no', 'Year'],
      dtype='object')

In [53]:
finalcsv_df = merged1_df.rename(columns = {'claimno':'ClaimNo','insclaimno':'InsClaimNo','drivername':'DriverName', 'employeeid':'EmployeeId', \
                                                       'dept':'Department', 'unitno':'UnitNo', 'accidentdate':'AccidentDate', 'description':'Description', \
                                                       'preventable?':'Preventable', 'injury':'Injury','loss_of_bonus_':'LossOfBonus','coaching':'Coaching', \
                                                       'final___jerrys_estimate':'FinalJerrysEstimate', \
                                                       'est':'Estimate', 'oprepair':'OpRepair', 'total':'Total', 'time':'Time', 'address':'Address', 'citystate':'CityState', 'weather':'Weather', \
                                                       'lighting':'Lighting', 'roadsurface':'RoadSurface', 'roadtype':'RoadType', 'driveraction':'DriverAction','policereport':'PoliceReport', \
                                                      'dotrecordable' : 'DOT Recordable','video':'Video', 'prev':'Prev', 'status' : 'ClaimStatus', \
                                                      'claimadj':'ClaimAdj', 'notes':'Notes','vms_accident_no':'VMSAccidentNo'})

In [54]:
finalcsv_df

,ClaimNo,InsClaimNo,DriverName,EmployeeId,Department,UnitNo,AccidentDate,Description,Preventable,Injury,...,DriverAction,PoliceReport,DOT Recordable,Video,Prev,ClaimStatus,ClaimAdj,Notes,VMSAccidentNo,Year
0,010124-311,Not Registered,Douglas Bumpus,5,Charter,311,2024-01-01 00:00:00.000,Turning in parking lot of Buccees hit a car.,yes,no,...,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
1,010524-319,Not Registered,Devon Whitmore,0-1,Charter,319,2024-01-05 00:00:00.000,"Backing bus into slot,fatigue driving back got...",yes,no,...,Backing,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
2,011124-312,Not Registered,Troy Fontechia,1-2,Charter,312,2024-01-11 00:00:00.000,Car nearly crashed pick up truck while merging...,no,No,...,Driving Forward,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
3,Not Registered,Not Registered,DERRICK Lowe,Not Registered,RTA,722,2024-01-18 00:00:00.000,Thursday is my day to get my Bus wash when i...,yes,Not Registered,...,Driving Forward,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Marker light,Not Registered,2024
4,012524-336,Not Registered,Estus Owens,5,Charter,336,2024-01-25 00:00:00.000,I was backing up at the Embassy suites downtow...,yes,no,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,Not Registered,Not Registered,Brian Grimes,Not Registered,Charter,726,2025-05-04 00:00:00.000,As I was driving thru a construction 🚧 I was ...,yes,No,...,Driving Forward,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
243,Not Registered,Not Registered,Jerome Asbury,Not Registered,Charter,327,2025-05-04 00:00:00.000,As I turned onto Junior Gilliam Way from Rep J...,yes,No,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
244,Not Registered,Not Registered,Todd Stevens,Not Registered,RTA,724,2025-05-07 00:00:00.000,Backed into parked bus,yes,Not Registered,...,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
245,Not Registered,Not Registered,Donald Hillaker,Not Registered,School Bus,505,2025-05-08 00:00:00.000,Vehicle hit the mirror of a parked truck,yes,No,...,Not Registered,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
246,Not Registered,Not Registered,Lonnie McGee,Not Registered,Charter,328,2025-05-11 00:00:00.000,A passenger was unconscious so I called 911 fo...,Not Registered,Yes,...,Not Registered,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025

In [55]:
finalcsv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ClaimNo              247 non-null    object
 1   InsClaimNo           247 non-null    object
 2   DriverName           247 non-null    object
 3   EmployeeId           247 non-null    object
 4   Department           247 non-null    object
 5   UnitNo               247 non-null    object
 6   AccidentDate         247 non-null    object
 7   Description          247 non-null    object
 8   Preventable          247 non-null    object
 9   Injury               247 non-null    object
 10  LossOfBonus          247 non-null    object
 11  Coaching             247 non-null    object
 12  FinalJerrysEstimate  247 non-null    object
 13  Estimate             247 non-null    object
 14  OpRepair             247 non-null    object
 15  Total                247 non-null    object
 16  Time                 247 non-null    object
 17  Address              247 non-null    object
 18  CityState            247 non-null    object
 19  Weather              247 non-null    object
 20  Lighting             247 non-null    object
 21  RoadSurface          247 non-null    object
 22  RoadType             247 non-null    object
 23  DriverAction         247 non-null    object
 24  PoliceReport         247 non-null    object
 25  DOT Recordable       247 non-null    object
 26  Video                247 non-null    object
 27  Prev                 247 non-null    object
 28  ClaimStatus          247 non-null    object
 29  ClaimAdj             247 non-null    object
 30  Notes                247 non-null    object
 31  VMSAccidentNo        247 non-null    object
 32  Year                 247 non-null    int64
dtypes: int64(1), object(32)
memory usage: 63.8+ KB

## Merging both final Excel and final csv files

In [56]:
final_df = pd.concat([merged_df, finalcsv_df], ignore_index=True, axis=0)

In [57]:
final_df.columns

Index(['ClaimNo', 'DriverName', 'Department', 'AccidentDate',
       'IncidentAccident', 'DOT Recordable', 'UnitNo', 'Description',
       'GLDriver', 'NonGLDriver', 'GLEmployeeInjury', 'NonGLEmployeeInjury',
       'InsNotified', 'ClaimType', 'JerrysGLBusRepair', 'Quote',
       'CostForOtherVehicleRepoair', 'Actual', 'PoliceReport', 'DriveCam',
       'SafetyCommRuling', 'ClaimStatus', 'Year', 'InsClaimNo',
       'GL Repair Cost ', '3rdPartyCost', 'Ins Fees', 'Time', 'Location',
       'Weather', 'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'EmployeeId', 'DriverInjured',
       'OpInjured', 'GLBusEstimate', 'GLBusRepair', 'GL FINAL COST',
       'OpRepairCost', 'InsFee', 'OpInsPaid', 'InsDeductable', 'Total', 'TIME',
       'DriverAction', 'Radius', 'Video', 'Preventable', 'OpFault', 'Injury',
       'GLEstimate', 'Final', 'OpRepair', 'CityState', 'ClaimAdj', 'Notes',
       'VMSAccidentNo', 'LossOfBonus', 'Coaching', 'FinalJerrysEstimate',
       'Estimate', 'Address', 'Prev'],
      dtype='object')

In [58]:
final_df

,ClaimNo,DriverName,Department,AccidentDate,IncidentAccident,DOT Recordable,UnitNo,Description,GLDriver,NonGLDriver,...,CityState,ClaimAdj,Notes,VMSAccidentNo,LossOfBonus,Coaching,FinalJerrysEstimate,Estimate,Address,Prev
0,010318-533,Brittney Patterson,School Bus,2018-01-04 00:00:00,Incident,Non-DOT,533,"Driver hit a sign, no damage reported",X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,010718-1015,Scott Wangrud,Charter,2018-01-07 00:00:00,Incident,Non-DOT,1015,Supposedly hit an Anchor Bus' mirror,X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,011518-1021,Thomas House,Charter,2018-01-15 00:00:00,Accident,Non-DOT,1021,Driver hit a sign,X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,011618-1015,David Armstrong,Charter,2018-01-16 00:00:00,Accident,Non-DOT,1015,Bus slid into concrete light pole. Parking lot...,NaN,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,011918-232,William Moncrief,Tour,2018-01-19 00:00:00,Accident,Non-DOT,232,Our bus was hit by Freeman Trucking. Right sid...,NaN,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,Not Registered,Brian Grimes,Charter,2025-05-04 00:00:00.000,NaN,Not Registered,726,As I was driving thru a construction 🚧 I was ...,NaN,NaN,...,Meridian MS,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,0.0,Not Registered,Not on Gray Line TN Property I59 north and 31s...,Not Registered
671,Not Registered,Jerome Asbury,Charter,2025-05-04 00:00:00.000,NaN,Not Registered,327,As I turned onto Junior Gilliam Way from Rep J...,NaN,NaN,...,Nashville Tennessee,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,0.0,Not Registered,Not on Gray Line TN Property 19 Jr Gilliam Way,Not Registered
672,Not Registered,Todd Stevens,RTA,2025-05-07 00:00:00.000,NaN,Not Registered,724,Backed into parked bus,NaN,NaN,...,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Lebanon Pike Lot,Not Registered
673,Not Registered,Donald Hillaker,School Bus,2025-05-08 00:00:00.000,NaN,Not Registered,505,Vehicle hit the mirror of a parked truck,NaN,NaN,...,Nashville Tennessee,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not on Gray Line TN Property Meridian and Grace,Not Registered
674,Not Registered,Lonnie McGee,Charter,2025-05-11 00:00:00.000,NaN,Not Registered,328,A passenger was unconscious so I called 911 fo...,NaN,NaN,...,Marion Virginia,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not on Gray Line TN Property Staley St @ N Mai...,Not Registered

In [59]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 675 entries, 0 to 674
Data columns (total 67 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ClaimNo                     669 non-null    object
 1   DriverName                  675 non-null    object
 2   Department                  662 non-null    object
 3   AccidentDate                674 non-null    object
 4   IncidentAccident            125 non-null    object
 5   DOT Recordable              670 non-null    object
 6   UnitNo                      666 non-null    object
 7   Description                 670 non-null    object
 8   GLDriver                    222 non-null    object
 9   NonGLDriver                 186 non-null    object
 10  GLEmployeeInjury            271 non-null    object
 11  NonGLEmployeeInjury         267 non-null    object
 12  InsNotified                 264 non-null    object
 13  ClaimType                   339 non-null    object
 14  JerrysGLBusRepair           10 non-null     float64
 15  Quote                       2 non-null      float64
 16  CostForOtherVehicleRepoair  8 non-null      float64
 17  Actual                      0 non-null      float64
 18  PoliceReport                596 non-null    object
 19  DriveCam                    206 non-null    object
 20  SafetyCommRuling            214 non-null    object
 21  ClaimStatus                 535 non-null    object
 22  Year                        675 non-null    int64
 23  InsClaimNo                  415 non-null    object
 24  GL Repair Cost              145 non-null    object
 25  3rdPartyCost                34 non-null     float64
 26  Ins Fees                    153 non-null    float64
 27  Time                        495 non-null    object
 28  Location                    286 non-null    object
 29  Weather                     545 non-null    object
 30  Lighting                    544 non-null    object
 31  RoadSurface                 545 non-null    object
 32  RoadType                    544 non-null    object
 33  ControlDevice               55 non-null     object
 34  DriverExperience            203 non-null    object
 35  Raduis                      152 non-null    object
 36  EmployeeId                  315 non-null    object
 37  DriverInjured               50 non-null     object
 38  OpInjured                   50 non-null     object
 39  GLBusEstimate               50 non-null     float64
 40  GLBusRepair                 50 non-null     float64
 41  GL FINAL COST               50 non-null     float64
 42  OpRepairCost                50 non-null     float64
 43  InsFee                      50 non-null     float64
 44  OpInsPaid                   50 non-null     float64
 45  InsDeductable               50 non-null     float64
 46  Total                       394 non-null    object
 47  TIME                        50 non-null     object
 48  DriverAction                391 non-null    object
 49  Radius                      50 non-null     object
 50  Video                       311 non-null    object
 51  Preventable                 315 non-null    object
 52  OpFault                     87 non-null     float64
 53  Injury                      340 non-null    object
 54  GLEstimate                  18 non-null     float64
 55  Final                       18 non-null     float64
 56  OpRepair                    266 non-null    object
 57  CityState                   290 non-null    object
 58  ClaimAdj                    249 non-null    object
 59  Notes                       267 non-null    object
 60  VMSAccidentNo               264 non-null    object
 61  LossOfBonus                 247 non-null    object
 62  Coaching                    247 non-null    object
 63  FinalJerrysEstimate         247 non-null    object
 64  Estimate                    247 non-null    object
 65  Address                     247 non-null    object
 66  Prev                        247 non-null    object
dtypes: float64(16), int64(1), object(50)
memory usage: 353.4+ KB

## Cleaning the data

# Claim Number retrieval from Accident date and unit no
# Convert AccidentDate to datetime
final_df['AccidentDate'] = pd.to_datetime(final_df['AccidentDate'], errors='coerce')

# Format as MMDDYY (with leading zeros) and keep as string
final_df['AccidentDateFormatted'] = (
    final_df['AccidentDate'].dt.strftime('%m%d%y').where(final_df['AccidentDate'].notna())
)

# Combine into NewClaimNo
final_df['NewClaimNo'] = (
    final_df['AccidentDateFormatted'] + '-' + final_df['UnitNo'].astype('string')
)

# View the result
print(final_df[['AccidentDate', 'UnitNo', 'AccidentDateFormatted', 'NewClaimNo']])

In [60]:
# Clean the DriverName column
final_df['DriverName'] = (
    final_df['DriverName']
    .str.replace(',', '', regex=False)         # Remove commas
    .str.strip()                               # Remove leading/trailing whitespace
    .str.replace(r'\s+', ' ', regex=True)      # Collapse multiple spaces into one
)

# Converting date time to date only
final_df['AccidentDate'] = pd.to_datetime(final_df['AccidentDate'], errors='coerce')

#Fixing the multiple column values to 'Y' and 'N' for 'DOT Recordable'
final_df['DOT Recordable'] = final_df['DOT Recordable'].replace({'Non-DOT':'N', 
                                                                 'DOT':'Y', 
                                                                 'FALSE':'N',
                                                                 'TRUE':'Y',
                                                                 False:'N', 
                                                                 True: 'Y', 
                                                                 'non-DOT':'N', 
                                                                 'NON-DOT':'N', 
                                                                 'NON DOT': 'N', 
                                                                 '?':'Not Registered',
                                                                 'NON -DOT':'N'})

final_df['DOT Recordable'] = final_df['DOT Recordable'].fillna('Not Registered')

#Fixing the multiple column values of 'IncidentAccident' column
final_df['IncidentAccident'] = final_df['IncidentAccident'].replace({'?':'Not Registered',
                                                                     'Accicdent':'Accident',
                                                                     'Accidednt':'Accident',
                                                                     'Accident?':'Accident?',
                                                                     'Accidnet':'Accident',
                                                                     'INCIDENT':'Incident',
                                                                     'ACCIDENT':'Accident',
                                                                     'Incident / Accident':'Incident / Accident',
                                                                     'Mystery':'Mystery'})
final_df['IncidentAccident'] = final_df['IncidentAccident'].fillna('Not Registered')

#Fixing the multiple column values of 'PoliceReport' column
final_df['PoliceReport'] = final_df['PoliceReport'].replace({'No':'N',
                                                             'Yes':'Y',
                                                             'FALSE':'N',
                                                             'TRUE':'Y',
                                                             'Na':'Not Registered'})

##Fixing the multiple column values of 'SafetyCommRuling' column

final_df['Prevent'] = final_df['SafetyCommRuling'].combine_first(final_df['Preventable'])
final_df['Prevent'] = final_df['Prevent'].replace({'Non-Preventable':'N',
                                                   'Preventable':'Y',
                                                   'o-Prevetable':'N',
                                                   'Non-Preventable ':'N',
                                                   'no':'N',
                                                   'yes':'Y',
                                                   'Yes':'Y',
                                                   'True':'Y',
                                                   'No':'N',
                                                   'False':'N'})

final_df = final_df.drop(columns=['SafetyCommRuling', 'Preventable'])

In [61]:
final_df.head()

,ClaimNo,DriverName,Department,AccidentDate,IncidentAccident,DOT Recordable,UnitNo,Description,GLDriver,NonGLDriver,...,ClaimAdj,Notes,VMSAccidentNo,LossOfBonus,Coaching,FinalJerrysEstimate,Estimate,Address,Prev,Prevent
0,010318-533,Brittney Patterson,School Bus,2018-01-04,Incident,N,533,"Driver hit a sign, no damage reported",X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1,010718-1015,Scott Wangrud,Charter,2018-01-07,Incident,N,1015,Supposedly hit an Anchor Bus' mirror,X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
2,011518-1021,Thomas House,Charter,2018-01-15,Accident,N,1021,Driver hit a sign,X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
3,011618-1015,David Armstrong,Charter,2018-01-16,Accident,N,1015,Bus slid into concrete light pole. Parking lot...,NaN,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
4,011918-232,William Moncrief,Tour,2018-01-19,Accident,N,232,Our bus was hit by Freeman Trucking. Right sid...,NaN,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N

In [62]:
graylinefleetrenamed_df_selected = graylinefleetrenamed_df[['FleetNo', 'Department']]
#final_df = pd.concat([df1, graylinefleetrenamed_df_selected], ignore_index=True, axis=0)
final_df1 = final_df.merge(graylinefleetrenamed_df_selected, how='left', left_on='UnitNo', right_on='FleetNo')
#result = df1.merge(df2, how='left', left_on='id1', right_on='id2')

In [63]:
final_df1.columns

Index(['ClaimNo', 'DriverName', 'Department_x', 'AccidentDate',
       'IncidentAccident', 'DOT Recordable', 'UnitNo', 'Description',
       'GLDriver', 'NonGLDriver', 'GLEmployeeInjury', 'NonGLEmployeeInjury',
       'InsNotified', 'ClaimType', 'JerrysGLBusRepair', 'Quote',
       'CostForOtherVehicleRepoair', 'Actual', 'PoliceReport', 'DriveCam',
       'ClaimStatus', 'Year', 'InsClaimNo', 'GL Repair Cost ', '3rdPartyCost',
       'Ins Fees', 'Time', 'Location', 'Weather', 'Lighting', 'RoadSurface',
       'RoadType', 'ControlDevice', 'DriverExperience', 'Raduis', 'EmployeeId',
       'DriverInjured', 'OpInjured', 'GLBusEstimate', 'GLBusRepair',
       'GL FINAL COST', 'OpRepairCost', 'InsFee', 'OpInsPaid', 'InsDeductable',
       'Total', 'TIME', 'DriverAction', 'Radius', 'Video', 'OpFault', 'Injury',
       'GLEstimate', 'Final', 'OpRepair', 'CityState', 'ClaimAdj', 'Notes',
       'VMSAccidentNo', 'LossOfBonus', 'Coaching', 'FinalJerrysEstimate',
       'Estimate', 'Address', 'Prev', 'Prevent', 'FleetNo', 'Department_y'],
      dtype='object')

In [64]:
## Convert both to string, strip spaces
final_df['UnitNo'] = final_df['UnitNo'].astype(str).str.strip().str.lower()
graylinefleetrenamed_df_selected['FleetNo'] = graylinefleetrenamed_df_selected['FleetNo'].astype(str).str.strip().str.lower()

# Merge
final_df1 = final_df.merge(
    graylinefleetrenamed_df_selected,
    how='left',
    left_on='UnitNo',
    right_on='FleetNo'
)

In [65]:
last_df = final_df1.drop(columns=['Department_x', 'FleetNo']).rename(columns={'Department_y':'Department'})

In [66]:
last_df.columns

Index(['ClaimNo', 'DriverName', 'AccidentDate', 'IncidentAccident',
       'DOT Recordable', 'UnitNo', 'Description', 'GLDriver', 'NonGLDriver',
       'GLEmployeeInjury', 'NonGLEmployeeInjury', 'InsNotified', 'ClaimType',
       'JerrysGLBusRepair', 'Quote', 'CostForOtherVehicleRepoair', 'Actual',
       'PoliceReport', 'DriveCam', 'ClaimStatus', 'Year', 'InsClaimNo',
       'GL Repair Cost ', '3rdPartyCost', 'Ins Fees', 'Time', 'Location',
       'Weather', 'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'EmployeeId', 'DriverInjured',
       'OpInjured', 'GLBusEstimate', 'GLBusRepair', 'GL FINAL COST',
       'OpRepairCost', 'InsFee', 'OpInsPaid', 'InsDeductable', 'Total', 'TIME',
       'DriverAction', 'Radius', 'Video', 'OpFault', 'Injury', 'GLEstimate',
       'Final', 'OpRepair', 'CityState', 'ClaimAdj', 'Notes', 'VMSAccidentNo',
       'LossOfBonus', 'Coaching', 'FinalJerrysEstimate', 'Estimate', 'Address',
       'Prev', 'Prevent', 'Department'],
      dtype='object')

In [67]:
finalcols=['ClaimNo', 'DriverName', 'AccidentDate', 'IncidentAccident',
       'DOT Recordable', 'UnitNo', 'Description', 'GLDriver', 'NonGLDriver',
       'GLEmployeeInjury', 'NonGLEmployeeInjury', 'InsNotified', 'ClaimType',
       'JerrysGLBusRepair', 'Quote', 'CostForOtherVehicleRepoair', 'Actual',
       'PoliceReport', 'DriveCam', 'ClaimStatus', 'Year', 'InsClaimNo',
       'GL Repair Cost ', '3rdPartyCost', 'Ins Fees', 'Time', 'Location',
       'Weather', 'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'EmployeeId', 'DriverInjured',
       'OpInjured', 'GLBusEstimate', 'GLBusRepair', 'GL FINAL COST',
       'OpRepairCost', 'InsFee', 'OpInsPaid', 'InsDeductable', 'Total', 'TIME',
       'DriverAction', 'Radius', 'Video', 'OpFault', 'Injury', 'GLEstimate',
       'Final', 'OpRepair', 'CityState', 'ClaimAdj', 'Notes', 'VMSAccidentNo',
       'LossOfBonus', 'Coaching', 'FinalJerrysEstimate', 'Estimate', 'Address',
       'Prev', 'Prevent', 'Department']

last_df[finalcols] = last_df[finalcols].fillna("Not Registered")

In [68]:
last_df['JerrysGLBusRepair'] = last_df['JerrysGLBusRepair'].replace({'Not Registered': 0})
last_df['Quote'] = last_df['Quote'].replace({'Not Registered': 0})
last_df['CostForOtherVehicleRepoair'] = last_df['CostForOtherVehicleRepoair'].replace({'Not Registered': 0})
last_df['Actual'] = last_df['Actual'].replace({'Not Registered': 0})
last_df['GL Repair Cost '] = last_df['GL Repair Cost '].replace({'Not Registered': 0})
last_df['3rdPartyCost'] = last_df['3rdPartyCost'].replace({'Not Registered': 0})
last_df['Ins Fees'] = last_df['Ins Fees'].replace({'Not Registered': 0})
last_df['GLBusEstimate'] = last_df['GLBusEstimate'].replace({'Not Registered': 0})
last_df['GLBusRepair'] = last_df['GLBusRepair'].replace({'Not Registered': 0})
last_df['GL FINAL COST'] = last_df['GL FINAL COST'].replace({'Not Registered': 0})
last_df['OpRepairCost'] = last_df['OpRepairCost'].replace({'Not Registered': 0})
last_df['InsFee'] = last_df['InsFee'].replace({'Not Registered': 0})
last_df['OpInsPaid'] = last_df['OpInsPaid'].replace({'Not Registered': 0})
last_df['OpFault'] = last_df['OpFault'].replace({'Not Registered': 0})
last_df['GLEstimate'] = last_df['GLEstimate'].replace({'Not Registered': 0})
last_df['Final'] = last_df['Final'].replace({'Not Registered': 0})
last_df['InsDeductable'] = last_df['InsDeductable'].replace({'Not Registered': 0})
last_df['FinalJerrysEstimate'] = last_df['FinalJerrysEstimate'].replace({'Not Registered': 0})
last_df['Estimate'] = last_df['Estimate'].replace({'Not Registered': 0})

In [89]:
#styled_df = df.style.format({'Price': '${:,.2f}'})
#currency_string_format = "${:,.2f}".format(amount)
#last_df = last_df({'JerrysGLBusRepair', '${:,.2f}'}.format(amount))
# Set locale to US
#locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

# Format number as currency
#amount = 12345.678
#formatted_amount = locale.currency(amount, grouping=True)
#print(formatted_amount)  # Output: $12,345.68

#df['concat'] = '$' + df['amount'].astype(str)
#last_df['JerrysGLBusRepair'] = '$' + last_df['JerrysGLBusRepair'].astype(str)
#last_df['Quote'] = '$' + last_df['Quote'].astype(str)
#last_df['CostForOtherVehicleRepoair'] = '$' + last_df['CostForOtherVehicleRepoair'].astype(str)

#last_df['JerrysGLBusRepair'] = last_df['JerrysGLBusRepair'].map('${:,.2f}'.format)
#last_df['Quote'] = last_df['Quote'].map("${:,.2f}".format)
#last_df['CostForOtherVehicleRepoair'] = last_df['CostForOtherVehicleRepoair'].map("${:,.2f}".format)
#last_df['JerrysGLBusRepair'] = pd.to_numeric(last_df['JerrysGLBusRepair'], errors='coerce')
#last_df['Quote'] = pd.to_numeric(last_df['Quote'], errors='coerce')
#last_df['CostForOtherVehicleRepoair'] = pd.to_numeric(last_df['CostForOtherVehicleRepoair'], errors='coerce')
#last_df['JerrysGLBusRepair'] = last_df['JerrysGLBusRepair'].map(lambda x: "${:,.2f}".format(x) if pd.notnull(x) else "")#last_df['Quote'] = last_df['Quote'].map(lambda x: "${:,.2f}".format(x) if pd.notnull(x) else "")last_df['CostForOtherVehicleRepoair'] = last_df['CostForOtherVehicleRepoair'].map(lambda x: "${:,.2f}".format(x) if pd.notnull(x) else "")


# Convert to numeric 
last_df['JerrysGLBusRepair'] = pd.to_numeric(last_df['JerrysGLBusRepair'], errors='coerce')
last_df['Quote'] = pd.to_numeric(last_df['Quote'], errors='coerce')
last_df['CostForOtherVehicleRepoair'] = pd.to_numeric(last_df['CostForOtherVehicleRepoair'], errors='coerce')

#Format as currency strings 
last_df['JerrysGLBusRepair'] = last_df['JerrysGLBusRepair'].map(
    lambda x: "${:,.2f}".format(x) if pd.notnull(x) else ""
)
last_df['Quote'] = last_df['Quote'].map(
    lambda x: "${:,.2f}".format(x) if pd.notnull(x) else ""
)
last_df['CostForOtherVehicleRepoair'] = last_df['CostForOtherVehicleRepoair'].map(
    lambda x: "${:,.2f}".format(x) if pd.notnull(x) else ""
)

#last_df['GL Repair Cost '] = last_df['GL Repair Cost '].astype(str)  # ensure string
#last_df['GL Repair Cost '] = last_df['GL Repair Cost '].str.replace(r'[A-Za-z]+', '0', regex=True)
#last_df['GL Repair Cost '] = last_df['GL Repair Cost '].apply(lambda x: "${:,.2f}".format(x) if pd.notnull(x) else "")

# Replace alpha chars with 0
last_df['GL Repair Cost '] = last_df['GL Repair Cost '].astype(str).str.replace(r'[A-Za-z]+', '0', regex=True)

# Convert to numeric safely
last_df['GL Repair Cost '] = pd.to_numeric(last_df['GL Repair Cost '], errors='coerce').fillna(0)

# Format as currency
last_df['GL Repair Cost '] = last_df['GL Repair Cost '].apply(lambda x: f"${x:,.2f}")

In [90]:
last_df['GL Repair Cost '].head(150)

0          $0.00
1          $0.00
2          $0.00
3          $0.00
4          $0.00
         ...
145        $0.00
146    $1,169.00
147      $984.00
148    $2,765.00
149    $1,650.00
Name: GL Repair Cost , Length: 150, dtype: object

In [ ]:
pd.set_option('display.max_columns', None)

In [71]:
last_df.head(10)

,ClaimNo,DriverName,AccidentDate,IncidentAccident,DOT Recordable,UnitNo,Description,GLDriver,NonGLDriver,GLEmployeeInjury,...,Notes,VMSAccidentNo,LossOfBonus,Coaching,FinalJerrysEstimate,Estimate,Address,Prev,Prevent,Department
0,010318-533,Brittney Patterson,2018-01-04 00:00:00,Incident,N,533,"Driver hit a sign, no damage reported",X,Not Registered,N,...,Not Registered,Not Registered,Not Registered,Not Registered,0,0,Not Registered,Not Registered,Y,School Bus
1,010718-1015,Scott Wangrud,2018-01-07 00:00:00,Incident,N,1015,Supposedly hit an Anchor Bus' mirror,X,Not Registered,N,...,Not Registered,Not Registered,Not Registered,Not Registered,0,0,Not Registered,Not Registered,Y,Charter
2,011518-1021,Thomas House,2018-01-15 00:00:00,Accident,N,1021,Driver hit a sign,X,Not Registered,N,...,Not Registered,Not Registered,Not Registered,Not Registered,0,0,Not Registered,Not Registered,Y,Charter
3,011618-1015,David Armstrong,2018-01-16 00:00:00,Accident,N,1015,Bus slid into concrete light pole. Parking lot...,Not Registered,X,N,...,Not Registered,Not Registered,Not Registered,Not Registered,0,0,Not Registered,Not Registered,N,Charter
4,011918-232,William Moncrief,2018-01-19 00:00:00,Accident,N,232,Our bus was hit by Freeman Trucking. Right sid...,Not Registered,X,N,...,Not Registered,Not Registered,Not Registered,Not Registered,0,0,Not Registered,Not Registered,N,Charter
5,011918-249,Mike Birdsong,2018-01-19 00:00:00,Incident,N,249,Hit a rock in a parking lot,X,Not Registered,N,...,Not Registered,Not Registered,Not Registered,Not Registered,0,0,Not Registered,Not Registered,Y,Charter
6,012018-230,Lee Johnson,2018-01-20 00:00:00,Accident,N,230,Driver was side swiped by a gray SUV,Not Registered,X,N,...,Not Registered,Not Registered,Not Registered,Not Registered,0,0,Not Registered,Not Registered,N,Sightseeing
7,012118-711,Thomas Jackson,2018-01-21 00:00:00,Accident,N,711,Driver struck drivers side mirror of a parked ...,X,Not Registered,N,...,Not Registered,Not Registered,Not Registered,Not Registered,0,0,Not Registered,Not Registered,Y,Not Registered
8,012218-527,Rawand Koyee,2018-01-22 00:00:00,Incident,N,527,Driver was turning with the crossing arm exten...,X,Not Registered,N,...,Not Registered,Not Registered,Not Registered,Not Registered,0,0,Not Registered,Not Registered,Y,School Bus
9,012518 - 316,Moenig Jeff,2018-01-25 00:00:00,Accident,N,316,Driver hit a parked car (mirror) on the side o...,X,X,N,...,Not Registered,Not Registered,Not Registered,Not Registered,0,0,Not Registered,Not Registered,Y,Charter

In [80]:
last_df.to_csv('data/finaloutput.csv', index=False)