In [1]:
#pip install pandas openpyxl
import sys
!{sys.executable} -m pip install openpyxl
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: openpyxl in c:\users\vm35884\appdata\local\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\vm35884\appdata\local\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [2]:
import os
print(os.listdir('data'))

['2018 Accident Incident Report.xlsx', '2019 Accident Report.xlsx', '2020 Accident Report.xlsx', '2021 Accident Report.xlsx', 'accidents_2024.csv', 'accidents_2025.csv', 'accidents_2025_preventable_addition.csv', 'finaldaccidents2019.xlsx', 'grayline_fleet_vehicles.csv']

In [3]:
accidents2018_df = pd.read_excel('data/2018 Accident Incident Report.xlsx', sheet_name = 'Sheet1',skiprows=[0,1,116,117,118,119], engine='openpyxl')
consolidatedaccidents2019_df = pd.read_excel('data/finaldaccidents2019.xlsx', engine='openpyxl')
accidents2020_df = pd.read_excel('data/2020 Accident Report.xlsx', sheet_name = 'Master', engine='openpyxl')
accidents2021_df = pd.read_excel('data/2021 Accident Report.xlsx', sheet_name = 'Master', engine='openpyxl')
accidents2024_df = pd.read_csv('data/accidents_2024.csv')
accidents2025_df = pd.read_csv('data/accidents_2025.csv')
accidents2025prevent_df = pd.read_csv('data/accidents_2025_preventable_addition.csv')
graylinefleet_df = pd.read_csv('data/grayline_fleet_vehicles.csv')

In [4]:
accidents2018_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 22 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Claim #                                          126 non-null    object
 1   Employee Name                                    127 non-null    object
 2   Dept.                                            115 non-null    object
 3   Date Occurred                                    126 non-null    datetime64[ns]
 4   Incident / Accident                              125 non-null    object
 5   DOT Recordable?                                  125 non-null    object
 6   Unit No.                                         119 non-null    object
 7   Description                                      122 non-null    object
 8   GL Driver                                        68 non-null     object
 9   NON GL Driver                                    32 non-null     object
 10  GL Employee                                      117 non-null    object
 11  NON GL Employee                                  113 non-null    object
 12  Ins. Notified                                    110 non-null    object
 13  In-House, Protective, or Other Driver/Insuance   99 non-null     object
 14  Jerry's $ GL Bus Repair                          10 non-null     float64
 15  Quote                                            2 non-null      float64
 16  Cost for other vehicle repair                    8 non-null      float64
 17  Actual                                           0 non-null      float64
 18  Police Report                                    64 non-null     object
 19  Drive Cam?                                       53 non-null     object
 20  Safety Committee Ruling                          61 non-null     object
 21  Status                                           66 non-null     object
dtypes: datetime64[ns](1), float64(4), object(17)
memory usage: 22.0+ KB

In [5]:
accidents2018_df.columns

Index(['Claim #', 'Employee Name', 'Dept.', 'Date Occurred ',
       'Incident / Accident', 'DOT Recordable?', 'Unit No.', 'Description',
       'GL Driver', 'NON GL Driver ', 'GL Employee', 'NON GL Employee',
       'Ins. Notified', 'In-House, Protective, or Other Driver/Insuance ',
       'Jerry's $ GL Bus Repair ', 'Quote', 'Cost for other vehicle repair',
       'Actual', 'Police Report', 'Drive Cam?', 'Safety Committee Ruling',
       'Status'],
      dtype='object')

In [6]:
acc2018renamed_df = accidents2018_df.rename(columns = {'Claim #':'ClaimNo', 'Employee Name':'DriverName', 'Dept.':'Department', 'Date Occurred ':'AccidentDate', \
                                                      'Incident / Accident':'IncidentAccident','Description':'Description','Unit No.':'UnitNo', 'GL Driver':'GLDriverFault', \
                                                      'NON GL Driver ':'NonGLDriverFault', 'GL Employee':'GLEmployeeInjury', 'NON GL Employee':'NonGLEmployeeInjury', \
                                                      "Jerry's $ GL Bus Repair ":'JerrysGLBusRepair', \
                                                      'Ins. Notified':'InsNotified', 'In-House, Protective, or Other Driver/Insuance ':'ClaimType', 'Quote':'Quote', \
                                                     'Actual':'Actual', 'Cost for other vehicle repair':'CostForOtherVehicleRepair', 'Police Report':'PoliceReport', \
                                                      'Drive Cam?':'DriveCam', 'Safety Committee Ruling':'SafetyCommRuling','DOT Recordable?':'DOT Recordable', \
                                                      'Status':'ClaimStatus'})

In [7]:
acc2018renamed_df['Year'] = 2018

In [8]:
acc2018renamed_df.head()

,ClaimNo,DriverName,Department,AccidentDate,IncidentAccident,DOT Recordable,UnitNo,Description,GLDriverFault,NonGLDriverFault,...,ClaimType,JerrysGLBusRepair,Quote,CostForOtherVehicleRepair,Actual,PoliceReport,DriveCam,SafetyCommRuling,ClaimStatus,Year
0,010318-533,Brittney Patterson,School Bus,2018-01-04,Incident,Non-DOT,533,"Driver hit a sign, no damage reported",X,NaN,...,In-House,NaN,NaN,NaN,NaN,N,N,Preventable,Closed,2018
1,010718-1015,Scott Wangrud,Charter,2018-01-07,Incident,Non-DOT,1015,Supposedly hit an Anchor Bus' mirror,X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,N,Preventable,Closed,2018
2,011518-1021,Thomas House,Charter,2018-01-15,Accident,Non-DOT,1021,Driver hit a sign,X,NaN,...,In-House,3185.35,NaN,NaN,NaN,N,N,Preventable,Closed,2018
3,011618-1015,David Armstrong,Charter,2018-01-16,Accident,Non-DOT,1015,Bus slid into concrete light pole. Parking lot...,NaN,X,...,In-House,NaN,NaN,NaN,NaN,N,N,Non-Preventable,Closed,2018
4,011918-232,William Moncrief,Tour,2018-01-19,Accident,Non-DOT,232,Our bus was hit by Freeman Trucking. Right sid...,NaN,X,...,OP Ins,NaN,NaN,NaN,NaN,Y,N,Non-Preventable,Open,2018

In [9]:
acc2018renamed_df.columns

Index(['ClaimNo', 'DriverName', 'Department', 'AccidentDate',
       'IncidentAccident', 'DOT Recordable', 'UnitNo', 'Description',
       'GLDriverFault', 'NonGLDriverFault', 'GLEmployeeInjury',
       'NonGLEmployeeInjury', 'InsNotified', 'ClaimType', 'JerrysGLBusRepair',
       'Quote', 'CostForOtherVehicleRepair', 'Actual', 'PoliceReport',
       'DriveCam', 'SafetyCommRuling', 'ClaimStatus', 'Year'],
      dtype='object')

In [10]:
consolidatedaccidents2019_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 35 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ClaimNo                    252 non-null    object
 1   InsClaimNo                 35 non-null     object
 2   DriverName                 251 non-null    object
 3   Department                 252 non-null    object
 4   UnitNo                     252 non-null    object
 5   AccidentDate               252 non-null    object
 6   Description                252 non-null    object
 7   GLDriverFault              236 non-null    object
 8   NonGLDriverFault           207 non-null    object
 9   GLEmployeeInjury           206 non-null    object
 10  NonGLEmployeeInjury        206 non-null    object
 11  InsNotified                206 non-null    object
 12  ClaimType                  205 non-null    object
 13  GLRepairCost               145 non-null    object
 14  3rdPartyCost               34 non-null     float64
 15  InsFee                     156 non-null    float64
 16  Time                       191 non-null    object
 17  Location                   191 non-null    object
 18  Weather                    203 non-null    object
 19  Lighting                   202 non-null    object
 20  RoadSurface                203 non-null    object
 21  RoadType                   202 non-null    object
 22  ControlDevice              80 non-null     object
 23  DriverExperience           153 non-null    object
 24  Raduis                     202 non-null    object
 25  PoliceReport               192 non-null    object
 26  DOT Recordable             198 non-null    object
 27  DriveCam                   167 non-null    object
 28  SafetyCommRuling           152 non-null    object
 29  ClaimStatus                184 non-null    object
 30  Year                       252 non-null    int64
 31  JerrysGLBusRepair          127 non-null    object
 32  CostForOtherVehicleRepair  20 non-null     float64
 33  DriverInfo                 64 non-null     object
 34  Quote                      36 non-null     object
dtypes: float64(3), int64(1), object(31)
memory usage: 69.0+ KB

In [11]:
consolidatedaccidents2019_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'Department', 'UnitNo',
       'AccidentDate', 'Description', 'GLDriverFault', 'NonGLDriverFault',
       'GLEmployeeInjury', 'NonGLEmployeeInjury', 'InsNotified', 'ClaimType',
       'GLRepairCost', '3rdPartyCost', 'InsFee', 'Time', 'Location', 'Weather',
       'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'PoliceReport', 'DOT Recordable',
       'DriveCam', 'SafetyCommRuling', 'ClaimStatus', 'Year',
       'JerrysGLBusRepair', 'CostForOtherVehicleRepair', 'DriverInfo',
       'Quote'],
      dtype='object')

In [12]:
consolidatedaccidents2019_df.head()

,ClaimNo,InsClaimNo,DriverName,Department,UnitNo,AccidentDate,Description,GLDriverFault,NonGLDriverFault,GLEmployeeInjury,...,PoliceReport,DOT Recordable,DriveCam,SafetyCommRuling,ClaimStatus,Year,JerrysGLBusRepair,CostForOtherVehicleRepair,DriverInfo,Quote
0,010319-271,td,Lonnie McGee,RTA,271,2019-01-03 00:00:00,GL Driver smelled smoke pulled over immediatel...,N,N,N,...,Y,Y,N,NaN,Open,2019,184385.5,NaN,0-50,NaN
1,010719-003,NaN,Jerry Mischler,Shop,7,2019-01-07 00:00:00,GL Mechanic hit another vehicle in an intersec...,Y,N,N,...,Y,Y,N,N,Open,2019,NaN,3108.94,NaN,NaN
2,011719-1021,NaN,Shawn Yokley,C,1021,2019-01-17 00:00:00,hooked back bumper on a cement pole,Y,N,N,...,N,N,N,N,N,2019,NaN,NaN,NaN,NaN
3,011719-616,NaN,Rawand Koyee,SB,616,2019-01-17 00:00:00,Backed into 565 front passenger window,Y,N,N,...,N,N,N,N,N,2019,642.97,NaN,3-4 Years,NaN
4,012019-727,NaN,James Johnson,BC,4727,2019-01-20 00:00:00,Hit pole in garage on right side,Y,N,N,...,N,N,N,N,N,2019,NaN,NaN,NaN,NaN

In [13]:
accidents2020_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CLAIM NUMBER          50 non-null     object
 1   CLAIM NUMBER2         50 non-null     int64
 2   DRIVER NAME           50 non-null     object
 3   EMPLOYEE ID           50 non-null     int64
 4   DEPARTMENT            50 non-null     object
 5   UNIT NO               50 non-null     int64
 6   ACC DATE              50 non-null     datetime64[ns]
 7   DESCRIPTION           50 non-null     object
 8   DRIVER INJURED        50 non-null     bool
 9   OP INJURED            50 non-null     bool
 10  CLAIM TYPE            49 non-null     object
 11  GL BUS ESTIMATE       50 non-null     float64
 12  GL BUS REPAIR         50 non-null     float64
 13  GL FINAL COST         50 non-null     float64
 14  OP REPAIR COST        50 non-null     float64
 15  INS FEE               50 non-null     int64
 16  OP INS PAID TO GL     50 non-null     float64
 17  INSURANCE DEDUCTIBLE  50 non-null     int64
 18  TOTAL                 50 non-null     float64
 19  TIME                  50 non-null     object
 20  LOCATION              50 non-null     object
 21  WEATHER               50 non-null     object
 22  LIGHTING              50 non-null     object
 23  ROAD SURFACE          50 non-null     object
 24  ROAD TYPE             50 non-null     object
 25  DRIVER ACTION         50 non-null     object
 26  DRIVER EXPERIENCE     50 non-null     float64
 27  RADIUS                50 non-null     object
 28  POLICE REPORT         50 non-null     bool
 29  DOT RECORDABLE        50 non-null     bool
 30  VIDEO                 50 non-null     bool
 31  PREVENTABLE?          50 non-null     bool
 32  STATUS                50 non-null     object
dtypes: bool(6), datetime64[ns](1), float64(7), int64(5), object(14)
memory usage: 11.0+ KB

In [14]:
accidents2020_df.columns

Index(['CLAIM NUMBER', 'CLAIM NUMBER2', 'DRIVER NAME', 'EMPLOYEE ID',
       'DEPARTMENT', 'UNIT NO', 'ACC DATE', 'DESCRIPTION', 'DRIVER INJURED',
       'OP INJURED', 'CLAIM TYPE', 'GL BUS ESTIMATE', 'GL BUS REPAIR',
       'GL FINAL COST', 'OP REPAIR COST', 'INS FEE', 'OP INS PAID TO GL',
       'INSURANCE DEDUCTIBLE', 'TOTAL', 'TIME', 'LOCATION', 'WEATHER',
       'LIGHTING', 'ROAD SURFACE', 'ROAD TYPE', 'DRIVER ACTION',
       'DRIVER EXPERIENCE', 'RADIUS', 'POLICE REPORT', 'DOT RECORDABLE',
       'VIDEO', 'PREVENTABLE?', 'STATUS'],
      dtype='object')

In [15]:
acc2020renamed_df = accidents2020_df.rename(columns = {'CLAIM NUMBER' : 'ClaimNo', 'CLAIM NUMBER2' : 'InsClaimNo', 'DRIVER NAME' : 'DriverName',\
                                                      'EMPLOYEE ID' : 'EmployeeId',  'DEPARTMENT' : 'Department', 'ACC DATE': 'AccidentDate', \
                                                      'DESCRIPTION' : 'Description', 'DRIVER INJURED' : 'DriverInjured', 'OP INJURED' : 'OpInjured', \
                                                      'CLAIM TYPE' : 'ClaimType', 'GL BUS ESTIMATE' : 'GLBusEstimate', 'GL BUS REPAIR' : 'GLBusRepair', \
                                                      'OP REPAIR COST' : 'OpRepairCost', 'INS FEE' : 'InsFee', 'OP INS PAID TO GL' : 'OpInsPaid', \
                                                      'INSURANCE DEDUCTIBLE' : 'InsDeductable', 'TOTAL' : 'Total', 'TIME' : 'Time', 'LOCATION' : 'Location', \
                                                      'WEATHER' : 'Weather', 'LIGHTING' : 'Lighting', 'ROAD SURFACE' : 'RoadSurface', 'ROAD TYPE' : 'RoadType', \
                                                      'DRIVER ACTION' : 'DriverAction','DRIVER EXPERIENCE' : 'DriverExperience', 'RADIUS' : 'Radius', \
                                                      'POLICE REPORT' : 'PoliceReport', 'DOT RECORDABLE' : 'DOT Recordable', 'VIDEO' : 'Video',\
                                                      'PREVENTABLE?' : 'Preventable', 'STATUS' : 'ClaimStatus', 'UNIT NO' : 'UnitNo', \
                                                      'GL FINAL COST':'GLFinalCost'})

In [16]:
acc2020renamed_df['Year'] = 2020

In [17]:
acc2020renamed_df.head()

,ClaimNo,InsClaimNo,DriverName,EmployeeId,Department,UnitNo,AccidentDate,Description,DriverInjured,OpInjured,...,RoadType,DriverAction,DriverExperience,Radius,PoliceReport,DOT Recordable,Video,Preventable,ClaimStatus,Year
0,010620-246,0,Alesha Harney,11038,Charter,246,2020-01-06,car hit the front bumper of the bus - scuffed ...,False,False,...,Parking Lot,Stop Sign,7.0,0-50,False,False,False,False,CLOSED,2020
1,010820-214,0,Kelly Westerlund,10979,Sightseeing,214,2020-01-08,"driver hit a service truck turning right, bus ...",False,False,...,Residential Street,turning right,1.0,0-50,True,False,False,True,CLOSED,2020
2,010920-1019,767903,Robert Kimbrell,10346,Charter,1019,2020-01-09,driver clipped a college student when she drov...,False,False,...,Residential Street,N,30.0,0-50,True,False,False,True,CLOSED,2020
3,010920-1019,0,Robert Kimbrell,10346,Charter,1019,2020-01-09,driver failed to set brake and bus rolled into...,False,False,...,Parking Lot,stopped,30.0,0-50,False,False,True,True,CLOSED,2020
4,011020-721,767935,Michael Beattie,10039,RTA,721,2020-01-10,hit OP right rear fender turning left at Charl...,False,False,...,Intersection,turning left,33.0,0-50,True,False,False,True,CLOSED,2020

In [18]:
acc2020renamed_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'EmployeeId', 'Department',
       'UnitNo', 'AccidentDate', 'Description', 'DriverInjured', 'OpInjured',
       'ClaimType', 'GLBusEstimate', 'GLBusRepair', 'GLFinalCost',
       'OpRepairCost', 'InsFee', 'OpInsPaid', 'InsDeductable', 'Total', 'Time',
       'Location', 'Weather', 'Lighting', 'RoadSurface', 'RoadType',
       'DriverAction', 'DriverExperience', 'Radius', 'PoliceReport',
       'DOT Recordable', 'Video', 'Preventable', 'ClaimStatus', 'Year'],
      dtype='object')

In [19]:
accidents2021_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ClaimNo          92 non-null     object
 1   InsClaimNo       91 non-null     float64
 2   DRIVERNAME       97 non-null     object
 3   EmployeeID       18 non-null     float64
 4   DEPT             96 non-null     object
 5   UnitNo           96 non-null     object
 6   AccidentDate     97 non-null     datetime64[ns]
 7   DESCRIPTION      97 non-null     object
 8   OPFAULT          87 non-null     float64
 9   INJURY           93 non-null     object
 10  ClaimType        37 non-null     object
 11  GLEstimate       18 non-null     float64
 12  Final            18 non-null     float64
 13  OPRepair         19 non-null     float64
 14  Total            97 non-null     float64
 15  TIME             95 non-null     object
 16  LOCATION         83 non-null     object
 17  CityState        43 non-null     object
 18  WEATHER          94 non-null     object
 19  LIGHTING         94 non-null     object
 20  RoadSurface      94 non-null     object
 21  RoadType         94 non-null     object
 22  DriverAction     94 non-null     object
 23  PoliceReport     82 non-null     object
 24  DOTRecordable    95 non-null     object
 25  VIDEO            14 non-null     object
 26  PREV             18 non-null     object
 27  STATUS           18 non-null     object
 28  ClaimAdj         2 non-null      object
 29  NOTES            20 non-null     object
 30  VMS Accident No  17 non-null     float64
dtypes: datetime64[ns](1), float64(8), object(22)
memory usage: 23.6+ KB

In [20]:
accidents2021_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DRIVERNAME', 'EmployeeID', 'DEPT', 'UnitNo',
       'AccidentDate', 'DESCRIPTION', 'OPFAULT', 'INJURY', 'ClaimType',
       'GLEstimate', 'Final', 'OPRepair', 'Total', 'TIME', 'LOCATION',
       'CityState', 'WEATHER', 'LIGHTING', 'RoadSurface', 'RoadType',
       'DriverAction', 'PoliceReport', 'DOTRecordable', 'VIDEO', 'PREV',
       'STATUS', 'ClaimAdj', 'NOTES', 'VMS Accident No'],
      dtype='object')

In [21]:
acc2021renamed_df = accidents2021_df.rename(columns = {'ClaimNo' : 'ClaimNo', 'InsClaimNo' : 'InsClaimNo', 'DRIVERNAME' : 'DriverName','EmployeeID' : 'EmployeeId', \
                                                      'DEPT' : 'Department', 'UnitNo' : 'UnitNo', 'DESCRIPTION' : 'Description', \
                                                      'OPFAULT' : 'OpFault', 'INJURY' : 'Injury', 'GL Estimate':'GLBusEstimate', 'OPRepair':'OpRepairCost',\
                                                      'TIME':'Time', 'LOCATION':'Location', 'WEATHER':'Weather', \
                                                      'LIGHTING':'Lighting', 'RoadSurface':'RoadSurface', 'RoadType':'RoadType', 'DriverAction':'DriverAction', \
                                                      'DOTRecordable' : 'DOT Recordable', 'VIDEO': 'Video', 'PREV':'Preventable', \
                                                      'Date Occured': 'AccidentDate', 'STATUS' : 'ClaimStatus', 'NOTES':'Notes', 'VMS Accident No':'VMSAccidentNo'})

In [22]:
acc2021renamed_df['Year'] = 2021

In [23]:
acc2021renamed_df.head(5)

,ClaimNo,InsClaimNo,DriverName,EmployeeId,Department,UnitNo,AccidentDate,Description,OpFault,Injury,...,DriverAction,PoliceReport,DOT Recordable,Video,Preventable,ClaimStatus,ClaimAdj,Notes,VMSAccidentNo,Year
0,011321-715,110.0,Elizabeth Burton,10086.0,RTA,715,2021-01-13,Penske truck hit passenger side mirror of bus ...,1.0,False,...,"Stopped, Not Moving",FALSE,FALSE,False,False,Open,NaN,Unscheduled activity id78458,110.0,2021
1,011421-280,111.0,Robert Schneider,11016.0,RTA,280,2021-01-14,a bobcat truck pulling a 36' to 40' constructi...,1.0,False,...,"Stopped, Not Moving",FALSE,FALSE,False,False,Open,NaN,UnscheduledActivity id 78478,111.0,2021
2,011721-329,112.0,Anthony Wells,10914.0,Charter,329,2021-01-17,"driver backed into a pay booth, rear screen o...",0.0,False,...,Right Turn,FALSE,FALSE,False,True,Open,NaN,driver submitted defect with description that ...,112.0,2021
3,011721-4101,768974.0,Sameh Shaker,10566.0,School Bus,4101,2021-01-17,Our bus was parked on the side of the road whe...,1.0,TRUE,...,"Stopped, Not Moving",TRUE,TRUE,False,False,Open,Lisa Carey,State Farm Claim No. 4215V715T - reported to L...,113.0,2021
4,011921-000,235957.0,Jenniefer Stephens,10597.0,Charter,0,2021-01-19,IW was closing tire cover when the bumper clos...,0.0,TRUE,...,"Stopped, Not Moving",False,False,False,True,Open,Tracy Robinson,Work Comp,NaN,2021

In [24]:
acc2021renamed_df.columns

Index(['ClaimNo', 'InsClaimNo', 'DriverName', 'EmployeeId', 'Department',
       'UnitNo', 'AccidentDate', 'Description', 'OpFault', 'Injury',
       'ClaimType', 'GLEstimate', 'Final', 'OpRepairCost', 'Total', 'Time',
       'Location', 'CityState', 'Weather', 'Lighting', 'RoadSurface',
       'RoadType', 'DriverAction', 'PoliceReport', 'DOT Recordable', 'Video',
       'Preventable', 'ClaimStatus', 'ClaimAdj', 'Notes', 'VMSAccidentNo',
       'Year'],
      dtype='object')

In [25]:
accidents2024_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   claimno                  190 non-null    object
 1   insclaimno               190 non-null    object
 2   drivername               190 non-null    object
 3   employeeid               190 non-null    object
 4   dept                     190 non-null    object
 5   unitno                   190 non-null    object
 6   accidentdate             190 non-null    object
 7   description              190 non-null    object
 8   preventable?             190 non-null    object
 9   injury                   190 non-null    object
 10  loss_of_bonus_           190 non-null    object
 11  coaching                 190 non-null    object
 12  final___jerrys_estimate  190 non-null    object
 13  est                      190 non-null    object
 14  oprepair                 190 non-null    object
 15  total                    190 non-null    object
 16  time                     190 non-null    object
 17  address                  190 non-null    object
 18  citystate                190 non-null    object
 19  weather                  190 non-null    object
 20  lighting                 190 non-null    object
 21  roadsurface              190 non-null    object
 22  roadtype                 190 non-null    object
 23  driveraction             190 non-null    object
 24  policereport             190 non-null    object
 25  dotrecordable            190 non-null    object
 26  video                    190 non-null    object
 27  prev                     190 non-null    object
 28  status                   190 non-null    object
 29  claimadj                 190 non-null    object
 30  notes                    190 non-null    object
 31  vms_accident_no          190 non-null    object
dtypes: object(32)
memory usage: 47.6+ KB

In [26]:
accidents2024_df['Year'] = 2024

In [27]:
accidents2024_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no', 'Year'],
      dtype='object')

In [28]:
accidents2024_df = accidents2024_df.rename(columns= {'address':'Location'})

In [29]:
# To see all the columns
pd.set_option('display.max_columns', None)

In [30]:
accidents2024_df.head()

,claimno,insclaimno,drivername,employeeid,dept,unitno,accidentdate,description,preventable?,injury,loss_of_bonus_,coaching,final___jerrys_estimate,est,oprepair,total,time,Location,citystate,weather,lighting,roadsurface,roadtype,driveraction,policereport,dotrecordable,video,prev,status,claimadj,notes,vms_accident_no,Year
0,010124-311,Not Registered,Douglas Bumpus,5,Charter,311,2024-01-01 00:00:00.000,Turning in parking lot of Buccees hit a car.,yes,no,yes,JA,10173.02 EST,Not Registered,Not Registered,Not Registered,1904-03-10 00:00:00,Not Registered,Athens GA,Clear,Daylight,Dry,Parking Lot,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
1,010524-319,Not Registered,Devon Whitmore,0-1,Charter,319,2024-01-05 00:00:00.000,"Backing bus into slot,fatigue driving back got...",yes,no,yes,JA,2346.16,Not Registered,Not Registered,Not Registered,12:37:00,3009 Dickerson Pike,"Nashville,TN",Clear,Daylight,Dry,Lebanon Pike or Shop Parking Lot,Backing,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
2,011124-312,Not Registered,Troy Fontechia,1-2,Charter,312,2024-01-11 00:00:00.000,Car nearly crashed pick up truck while merging...,no,No,no,JA,4449.51 EST,0.0,Not Registered,Not Registered,12:20:00,Not Registered,"Southaven, MS",Clear,Daylight,Dry,Interstate/Highway,Driving Forward,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
3,Not Registered,Not Registered,DERRICK Lowe,Not Registered,RTA,722,2024-01-18 00:00:00.000,Thursday is my day to get my Bus wash when i...,yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,About 7:15,Not Registered,Not Registered,Clear,Daylight,Snowy,Dickerson pik shop,Driving Forward,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Marker light,Not Registered,2024
4,012524-336,Not Registered,Estus Owens,5,Charter,336,2024-01-25 00:00:00.000,I was backing up at the Embassy suites downtow...,yes,no,Not Registered,JA,3519.02,Not Registered,Not Registered,Not Registered,10:15:00,Not Registered,Nashville Tennessee,Rain,"Dark, No Street Light",Wet,Parking Lot,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024

In [31]:
accidents2025_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   claimno                  57 non-null     object
 1   insclaimno               57 non-null     object
 2   drivername               57 non-null     object
 3   employeeid               57 non-null     object
 4   dept                     57 non-null     object
 5   unitno                   57 non-null     int64
 6   accidentdate             57 non-null     object
 7   description              57 non-null     object
 8   preventable?             57 non-null     object
 9   injury                   57 non-null     object
 10  loss_of_bonus_           57 non-null     object
 11  coaching                 57 non-null     object
 12  final___jerrys_estimate  57 non-null     object
 13  est                      57 non-null     object
 14  oprepair                 57 non-null     object
 15  total                    57 non-null     object
 16  time                     57 non-null     object
 17  address                  57 non-null     object
 18  citystate                57 non-null     object
 19  weather                  57 non-null     object
 20  lighting                 57 non-null     object
 21  roadsurface              57 non-null     object
 22  roadtype                 57 non-null     object
 23  driveraction             57 non-null     object
 24  policereport             57 non-null     object
 25  dotrecordable            57 non-null     object
 26  video                    57 non-null     object
 27  prev                     57 non-null     object
 28  status                   57 non-null     object
 29  claimadj                 57 non-null     object
 30  notes                    57 non-null     object
 31  vms_accident_no          57 non-null     object
dtypes: int64(1), object(31)
memory usage: 14.4+ KB

In [32]:
accidents2025_df['Year'] = 2025

In [33]:
accidents2025_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no', 'Year'],
      dtype='object')

In [34]:
accidents2025_df = accidents2025_df.rename(columns= {'address':'Location'})

In [35]:
accidents2025_df.head()

,claimno,insclaimno,drivername,employeeid,dept,unitno,accidentdate,description,preventable?,injury,loss_of_bonus_,coaching,final___jerrys_estimate,est,oprepair,total,time,Location,citystate,weather,lighting,roadsurface,roadtype,driveraction,policereport,dotrecordable,video,prev,status,claimadj,notes,vms_accident_no,Year
0,Not Registered,Not Registered,Tashelia Murphy,Not Registered,School Bus,593,2025-01-08 00:00:00.000,I was stopped at the red light in a bit of tra...,no,No,Not Registered,Not Registered,0.0,Not Registered,Not Registered,Not Registered,07:05:00,Not Registered,"Antioch , Tn",Clear,Daylight,Dry,Intersection,"Stopped, Not Moving",Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
1,011825-331,Not Registered,Alesha Harney,Not Registered,Charter,331,2025-01-18 00:00:00.000,Cut to close to concrete barrier getting turne...,yes,No,Not Registered,Not Registered,Not Registered,525.67,Not Registered,Not Registered,Not Registered,Not Registered,Washington D.C.,Clear,"Dark, No Street Light",Dry,Residential or City Street,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
2,012325-715,773848,Kimberly Perkins,Not Registered,RTA,715,2025-01-23 00:00:00.000,I was making a left turn on to Enterprise driv...,yes,Not Registered,Not Registered,Not Registered,Not Registered,710.0,Not Registered,Not Registered,6:05am,Not Registered,"Gallatin, Tennessee",Clear,"Dark, Street Lights On",Dry,Intersection,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
3,012525-249,Not Registered,Dale Jaco,Not Registered,Charter,249,2025-01-25 00:00:00.000,I was parked on 21st Ave and a mini bus from ...,no,No,Not Registered,Not Registered,0.0,Not Registered,Not Registered,Not Registered,330pm,Not Registered,"Nashville, Tn",Clear,Daylight,Dry,Residential or City Street,"Stopped, Not Moving",No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
4,012925-338,Not Registered,Lonnie McGee,Not Registered,Charter,338,2025-01-29 00:00:00.000,Murphy Athletic Center MTSU\n2650 Middle Tenne...,Yes,No,Not Registered,Not Registered,65.0,Not Registered,Not Registered,Not Registered,6:15pm,Not Registered,Murfreesboro TN,Clear,"Dark, No Street Light",Dry,Parking Lot (NOT Gray Line TN),Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025

In [36]:
accidents2025prevent_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   claimno                  35 non-null     object
 1   insclaimno               35 non-null     object
 2   drivername               35 non-null     object
 3   employeeid               35 non-null     object
 4   dept                     35 non-null     object
 5   unitno                   35 non-null     int64
 6   accidentdate             35 non-null     object
 7   description              35 non-null     object
 8   preventable?             35 non-null     object
 9   injury                   35 non-null     object
 10  loss_of_bonus_           35 non-null     object
 11  coaching                 35 non-null     object
 12  final___jerrys_estimate  35 non-null     object
 13  est                      35 non-null     object
 14  oprepair                 35 non-null     object
 15  total                    35 non-null     object
 16  time                     35 non-null     object
 17  address                  35 non-null     object
 18  citystate                35 non-null     object
 19  weather                  35 non-null     object
 20  lighting                 35 non-null     object
 21  roadsurface              35 non-null     object
 22  roadtype                 35 non-null     object
 23  driveraction             35 non-null     object
 24  policereport             35 non-null     object
 25  dotrecordable            35 non-null     object
 26  video                    35 non-null     object
 27  prev                     35 non-null     object
 28  status                   35 non-null     object
 29  claimadj                 35 non-null     object
 30  notes                    35 non-null     object
 31  vms_accident_no          35 non-null     object
dtypes: int64(1), object(31)
memory usage: 8.9+ KB

In [37]:
accidents2025prevent_df['Year'] = 2025

In [38]:
accidents2025prevent_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'address', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no', 'Year'],
      dtype='object')

In [39]:
accidents2025prevent_df.head()

,claimno,insclaimno,drivername,employeeid,dept,unitno,accidentdate,description,preventable?,injury,loss_of_bonus_,coaching,final___jerrys_estimate,est,oprepair,total,time,address,citystate,weather,lighting,roadsurface,roadtype,driveraction,policereport,dotrecordable,video,prev,status,claimadj,notes,vms_accident_no,Year
0,011825-331,Not Registered,Alesha Harney,Not Registered,Charter,331,2025-01-18 00:00:00.000,Cut to close to concrete barrier getting turne...,yes,No,Not Registered,Not Registered,Not Registered,525.67,Not Registered,Not Registered,Not Registered,Not Registered,Washington D.C.,Clear,"Dark, No Street Light",Dry,Residential or City Street,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
1,012325-715,773848.0,Kimberly Perkins,Not Registered,RTA,715,2025-01-23 00:00:00.000,I was making a left turn on to Enterprise driv...,yes,Not Registered,Not Registered,Not Registered,Not Registered,710.0,Not Registered,Not Registered,6:05am,Not Registered,"Gallatin, Tennessee",Clear,"Dark, Street Lights On",Dry,Intersection,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
2,012925-338,Not Registered,Lonnie McGee,Not Registered,Charter,338,2025-01-29 00:00:00.000,Murphy Athletic Center MTSU\n2650 Middle Tenne...,Yes,No,Not Registered,Not Registered,65.0,Not Registered,Not Registered,Not Registered,6:15pm,Not Registered,Murfreesboro TN,Clear,"Dark, No Street Light",Dry,Parking Lot (NOT Gray Line TN),Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
3,Not Registered,Not Registered,Lonnie McGee,Not Registered,Charter,338,2025-01-30 00:00:00.000,Got stuck in the mud. I was unable to turn bus...,yes,Not Registered,Not Registered,Not Registered,700.0,Not Registered,Not Registered,Not Registered,5:15pm,Not Registered,Murphy Athletic Center MTSU,Rain,Dusk,Muddy,Parking Lot (NOT Gray Line TN),Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
4,Not Registered,Not Registered,Thaddeus Nesby,Not Registered,RTA,727,2025-02-04 00:00:00.000,Coming around the corner of 21st Ave south and...,yes,No,Not Registered,Not Registered,754.12,Not Registered,Not Registered,Not Registered,16:09:00,Not on Gray Line TN Property 21st ave s and br...,"Nashville, TN",Cloudy,Dusk,Dry,Residential or City Street,Turning Right,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025

In [40]:
graylinefleet_df.columns

Index(['vms-id', 'fleetno', 'vin', 'modelyear', 'fleet_age', 'fleet_age_sort',
       'current_fleet_status', 'license_plate', 'vms_type', 'dept', 'make',
       'model', 'pax'],
      dtype='object')

In [41]:
graylinefleet_df.columns

Index(['vms-id', 'fleetno', 'vin', 'modelyear', 'fleet_age', 'fleet_age_sort',
       'current_fleet_status', 'license_plate', 'vms_type', 'dept', 'make',
       'model', 'pax'],
      dtype='object')

In [42]:
graylinefleetrenamed_df = graylinefleet_df.rename(columns = {'vms-id':'VMSId', 'fleetno':'FleetNo','vin':'VIN', 'modelyear':'ModelYear', 'fleet_age':'FleetAge', \
                                                                    'fleet_age_sort':'FleetAgeSort', 'current_fleet_status':'CurrenFleetStatus', \
                                                                    'license_plate':'LicensePlate', 'vms_type':'VMSType', 'dept':'Department', \
                                                                    'make':'Make', 'model':'Model', 'pax':'Pax'})

In [43]:
graylinefleetrenamed_df.head()

,VMSId,FleetNo,VIN,ModelYear,FleetAge,FleetAgeSort,CurrenFleetStatus,LicensePlate,VMSType,Department,Make,Model,Pax
0,1025,1025,1FDUF5GN8NEF91666,2023,2-7 Years Old,2,ACTIVE,CB61886,Mini-Coach 33 Pax,Charter,Glaval,Entourage,33.0
1,1026,1026,1FDUF5GNXNEF91670,2023,2-7 Years Old,2,ACTIVE,CB61887,Mini-Coach 33 Pax,Charter,Glaval,Entourage,33.0
2,1027,1027,1FDUF5GN1NEF91671,2023,2-7 Years Old,2,ACTIVE,CB61888,Mini-Coach 33 Pax,Charter,Glaval,Entourage,33.0
3,1028,1028,1FDUF5GN7NEF91674,2023,2-7 Years Old,2,ACTIVE,CB61889,Mini-Coach 33 Pax,Charter,Glaval,Entourage,33.0
4,1029,1029,1FDUF5GN9NDA26431,2023,2-7 Years Old,2,ACTIVE,CB61890,Mini-Coach 33 Pax,Charter,Glaval,Entourage,33.0

In [44]:
graylinefleetrenamed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   VMSId              325 non-null    object
 1   FleetNo            325 non-null    object
 2   VIN                325 non-null    object
 3   ModelYear          325 non-null    object
 4   FleetAge           325 non-null    object
 5   FleetAgeSort       325 non-null    int64
 6   CurrenFleetStatus  325 non-null    object
 7   LicensePlate       325 non-null    object
 8   VMSType            325 non-null    object
 9   Department         325 non-null    object
 10  Make               325 non-null    object
 11  Model              325 non-null    object
 12  Pax                325 non-null    object
dtypes: int64(1), object(12)
memory usage: 33.1+ KB

## Merging all 4 xlxs files into one file

In [45]:
merged_df = pd.concat([acc2018renamed_df, consolidatedaccidents2019_df,acc2020renamed_df,acc2021renamed_df], ignore_index=True, axis=0)

In [46]:
merged_df.columns

Index(['ClaimNo', 'DriverName', 'Department', 'AccidentDate',
       'IncidentAccident', 'DOT Recordable', 'UnitNo', 'Description',
       'GLDriverFault', 'NonGLDriverFault', 'GLEmployeeInjury',
       'NonGLEmployeeInjury', 'InsNotified', 'ClaimType', 'JerrysGLBusRepair',
       'Quote', 'CostForOtherVehicleRepair', 'Actual', 'PoliceReport',
       'DriveCam', 'SafetyCommRuling', 'ClaimStatus', 'Year', 'InsClaimNo',
       'GLRepairCost', '3rdPartyCost', 'InsFee', 'Time', 'Location', 'Weather',
       'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'DriverInfo', 'EmployeeId',
       'DriverInjured', 'OpInjured', 'GLBusEstimate', 'GLBusRepair',
       'GLFinalCost', 'OpRepairCost', 'OpInsPaid', 'InsDeductable', 'Total',
       'DriverAction', 'Radius', 'Video', 'Preventable', 'OpFault', 'Injury',
       'GLEstimate', 'Final', 'CityState', 'ClaimAdj', 'Notes',
       'VMSAccidentNo'],
      dtype='object')

In [47]:
merged_df.head()

,ClaimNo,DriverName,Department,AccidentDate,IncidentAccident,DOT Recordable,UnitNo,Description,GLDriverFault,NonGLDriverFault,GLEmployeeInjury,NonGLEmployeeInjury,InsNotified,ClaimType,JerrysGLBusRepair,Quote,CostForOtherVehicleRepair,Actual,PoliceReport,DriveCam,SafetyCommRuling,ClaimStatus,Year,InsClaimNo,GLRepairCost,3rdPartyCost,InsFee,Time,Location,Weather,Lighting,RoadSurface,RoadType,ControlDevice,DriverExperience,Raduis,DriverInfo,EmployeeId,DriverInjured,OpInjured,GLBusEstimate,GLBusRepair,GLFinalCost,OpRepairCost,OpInsPaid,InsDeductable,Total,DriverAction,Radius,Video,Preventable,OpFault,Injury,GLEstimate,Final,CityState,ClaimAdj,Notes,VMSAccidentNo
0,010318-533,Brittney Patterson,School Bus,2018-01-04 00:00:00,Incident,Non-DOT,533,"Driver hit a sign, no damage reported",X,NaN,N,N,N,In-House,NaN,NaN,NaN,NaN,N,N,Preventable,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,010718-1015,Scott Wangrud,Charter,2018-01-07 00:00:00,Incident,Non-DOT,1015,Supposedly hit an Anchor Bus' mirror,X,NaN,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,N,Preventable,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,011518-1021,Thomas House,Charter,2018-01-15 00:00:00,Accident,Non-DOT,1021,Driver hit a sign,X,NaN,N,N,N,In-House,3185.35,NaN,NaN,NaN,N,N,Preventable,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,011618-1015,David Armstrong,Charter,2018-01-16 00:00:00,Accident,Non-DOT,1015,Bus slid into concrete light pole. Parking lot...,NaN,X,N,N,N,In-House,NaN,NaN,NaN,NaN,N,N,Non-Preventable,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,011918-232,William Moncrief,Tour,2018-01-19 00:00:00,Accident,Non-DOT,232,Our bus was hit by Freeman Trucking. Right sid...,NaN,X,N,N,N,OP Ins,NaN,NaN,NaN,NaN,Y,N,Non-Preventable,Open,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
merged_df.columns

Index(['ClaimNo', 'DriverName', 'Department', 'AccidentDate',
       'IncidentAccident', 'DOT Recordable', 'UnitNo', 'Description',
       'GLDriverFault', 'NonGLDriverFault', 'GLEmployeeInjury',
       'NonGLEmployeeInjury', 'InsNotified', 'ClaimType', 'JerrysGLBusRepair',
       'Quote', 'CostForOtherVehicleRepair', 'Actual', 'PoliceReport',
       'DriveCam', 'SafetyCommRuling', 'ClaimStatus', 'Year', 'InsClaimNo',
       'GLRepairCost', '3rdPartyCost', 'InsFee', 'Time', 'Location', 'Weather',
       'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'DriverInfo', 'EmployeeId',
       'DriverInjured', 'OpInjured', 'GLBusEstimate', 'GLBusRepair',
       'GLFinalCost', 'OpRepairCost', 'OpInsPaid', 'InsDeductable', 'Total',
       'DriverAction', 'Radius', 'Video', 'Preventable', 'OpFault', 'Injury',
       'GLEstimate', 'Final', 'CityState', 'ClaimAdj', 'Notes',
       'VMSAccidentNo'],
      dtype='object')

In [49]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 59 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ClaimNo                    520 non-null    object
 1   DriverName                 525 non-null    object
 2   Department                 513 non-null    object
 3   AccidentDate               525 non-null    object
 4   IncidentAccident           125 non-null    object
 5   DOT Recordable             468 non-null    object
 6   UnitNo                     517 non-null    object
 7   Description                521 non-null    object
 8   GLDriverFault              304 non-null    object
 9   NonGLDriverFault           239 non-null    object
 10  GLEmployeeInjury           323 non-null    object
 11  NonGLEmployeeInjury        319 non-null    object
 12  InsNotified                316 non-null    object
 13  ClaimType                  390 non-null    object
 14  JerrysGLBusRepair          137 non-null    object
 15  Quote                      38 non-null     object
 16  CostForOtherVehicleRepair  28 non-null     float64
 17  Actual                     0 non-null      float64
 18  PoliceReport               388 non-null    object
 19  DriveCam                   220 non-null    object
 20  SafetyCommRuling           213 non-null    object
 21  ClaimStatus                318 non-null    object
 22  Year                       526 non-null    int64
 23  InsClaimNo                 176 non-null    object
 24  GLRepairCost               145 non-null    object
 25  3rdPartyCost               34 non-null     float64
 26  InsFee                     206 non-null    float64
 27  Time                       336 non-null    object
 28  Location                   324 non-null    object
 29  Weather                    347 non-null    object
 30  Lighting                   346 non-null    object
 31  RoadSurface                347 non-null    object
 32  RoadType                   346 non-null    object
 33  ControlDevice              80 non-null     object
 34  DriverExperience           203 non-null    object
 35  Raduis                     202 non-null    object
 36  DriverInfo                 64 non-null     object
 37  EmployeeId                 68 non-null     float64
 38  DriverInjured              50 non-null     object
 39  OpInjured                  50 non-null     object
 40  GLBusEstimate              50 non-null     float64
 41  GLBusRepair                50 non-null     float64
 42  GLFinalCost                50 non-null     float64
 43  OpRepairCost               69 non-null     float64
 44  OpInsPaid                  50 non-null     float64
 45  InsDeductable              50 non-null     float64
 46  Total                      147 non-null    float64
 47  DriverAction               144 non-null    object
 48  Radius                     50 non-null     object
 49  Video                      64 non-null     object
 50  Preventable                68 non-null     object
 51  OpFault                    87 non-null     float64
 52  Injury                     93 non-null     object
 53  GLEstimate                 18 non-null     float64
 54  Final                      18 non-null     float64
 55  CityState                  43 non-null     object
 56  ClaimAdj                   2 non-null      object
 57  Notes                      20 non-null     object
 58  VMSAccidentNo              17 non-null     float64
dtypes: float64(16), int64(1), object(42)
memory usage: 242.6+ KB

## Merging csv files into one file

In [50]:
#combined_df = pd.concat([df1, df2, df3], ignore_index=True, sort=False)
#merged1_df = pd.concat([acc2024renamed_df, acc2025renamed_df],ignore_index=True, sort=False)
merged1_df = pd.concat([accidents2024_df, accidents2025_df], ignore_index=True, axis=0)

In [51]:
merged1_df.head()

,claimno,insclaimno,drivername,employeeid,dept,unitno,accidentdate,description,preventable?,injury,loss_of_bonus_,coaching,final___jerrys_estimate,est,oprepair,total,time,Location,citystate,weather,lighting,roadsurface,roadtype,driveraction,policereport,dotrecordable,video,prev,status,claimadj,notes,vms_accident_no,Year
0,010124-311,Not Registered,Douglas Bumpus,5,Charter,311,2024-01-01 00:00:00.000,Turning in parking lot of Buccees hit a car.,yes,no,yes,JA,10173.02 EST,Not Registered,Not Registered,Not Registered,1904-03-10 00:00:00,Not Registered,Athens GA,Clear,Daylight,Dry,Parking Lot,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
1,010524-319,Not Registered,Devon Whitmore,0-1,Charter,319,2024-01-05 00:00:00.000,"Backing bus into slot,fatigue driving back got...",yes,no,yes,JA,2346.16,Not Registered,Not Registered,Not Registered,12:37:00,3009 Dickerson Pike,"Nashville,TN",Clear,Daylight,Dry,Lebanon Pike or Shop Parking Lot,Backing,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
2,011124-312,Not Registered,Troy Fontechia,1-2,Charter,312,2024-01-11 00:00:00.000,Car nearly crashed pick up truck while merging...,no,No,no,JA,4449.51 EST,0.0,Not Registered,Not Registered,12:20:00,Not Registered,"Southaven, MS",Clear,Daylight,Dry,Interstate/Highway,Driving Forward,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
3,Not Registered,Not Registered,DERRICK Lowe,Not Registered,RTA,722,2024-01-18 00:00:00.000,Thursday is my day to get my Bus wash when i...,yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,About 7:15,Not Registered,Not Registered,Clear,Daylight,Snowy,Dickerson pik shop,Driving Forward,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Marker light,Not Registered,2024
4,012524-336,Not Registered,Estus Owens,5,Charter,336,2024-01-25 00:00:00.000,I was backing up at the Embassy suites downtow...,yes,no,Not Registered,JA,3519.02,Not Registered,Not Registered,Not Registered,10:15:00,Not Registered,Nashville Tennessee,Rain,"Dark, No Street Light",Wet,Parking Lot,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024

In [52]:
merged1_df.columns

Index(['claimno', 'insclaimno', 'drivername', 'employeeid', 'dept', 'unitno',
       'accidentdate', 'description', 'preventable?', 'injury',
       'loss_of_bonus_', 'coaching', 'final___jerrys_estimate', 'est',
       'oprepair', 'total', 'time', 'Location', 'citystate', 'weather',
       'lighting', 'roadsurface', 'roadtype', 'driveraction', 'policereport',
       'dotrecordable', 'video', 'prev', 'status', 'claimadj', 'notes',
       'vms_accident_no', 'Year'],
      dtype='object')

In [53]:
finalcsv_df = merged1_df.rename(columns = {'claimno':'ClaimNo','insclaimno':'InsClaimNo','drivername':'DriverName', 'employeeid':'EmployeeId', \
                                                       'dept':'Department', 'unitno':'UnitNo', 'accidentdate':'AccidentDate', 'description':'Description', \
                                                       'preventable?':'Preventable', 'injury':'Injury','loss_of_bonus_':'LossOfBonus','coaching':'Coaching', \
                                                       'final___jerrys_estimate':'FinalJerrysEstimate', \
                                                       'est':'Estimate', 'oprepair':'OpRepairCost', 'total':'Total', 'time':'Time', 'citystate':'CityState', 'weather':'Weather', \
                                                       'lighting':'Lighting', 'roadsurface':'RoadSurface', 'roadtype':'RoadType', 'driveraction':'DriverAction','policereport':'PoliceReport', \
                                                      'dotrecordable' : 'DOT Recordable','video':'Video', 'prev':'Prev', 'status' : 'ClaimStatus', \
                                                      'claimadj':'ClaimAdj', 'notes':'Notes','vms_accident_no':'VMSAccidentNo'})

In [54]:
finalcsv_df

,ClaimNo,InsClaimNo,DriverName,EmployeeId,Department,UnitNo,AccidentDate,Description,Preventable,Injury,LossOfBonus,Coaching,FinalJerrysEstimate,Estimate,OpRepairCost,Total,Time,Location,CityState,Weather,Lighting,RoadSurface,RoadType,DriverAction,PoliceReport,DOT Recordable,Video,Prev,ClaimStatus,ClaimAdj,Notes,VMSAccidentNo,Year
0,010124-311,Not Registered,Douglas Bumpus,5,Charter,311,2024-01-01 00:00:00.000,Turning in parking lot of Buccees hit a car.,yes,no,yes,JA,10173.02 EST,Not Registered,Not Registered,Not Registered,1904-03-10 00:00:00,Not Registered,Athens GA,Clear,Daylight,Dry,Parking Lot,Turning Left,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
1,010524-319,Not Registered,Devon Whitmore,0-1,Charter,319,2024-01-05 00:00:00.000,"Backing bus into slot,fatigue driving back got...",yes,no,yes,JA,2346.16,Not Registered,Not Registered,Not Registered,12:37:00,3009 Dickerson Pike,"Nashville,TN",Clear,Daylight,Dry,Lebanon Pike or Shop Parking Lot,Backing,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
2,011124-312,Not Registered,Troy Fontechia,1-2,Charter,312,2024-01-11 00:00:00.000,Car nearly crashed pick up truck while merging...,no,No,no,JA,4449.51 EST,0.0,Not Registered,Not Registered,12:20:00,Not Registered,"Southaven, MS",Clear,Daylight,Dry,Interstate/Highway,Driving Forward,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
3,Not Registered,Not Registered,DERRICK Lowe,Not Registered,RTA,722,2024-01-18 00:00:00.000,Thursday is my day to get my Bus wash when i...,yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,About 7:15,Not Registered,Not Registered,Clear,Daylight,Snowy,Dickerson pik shop,Driving Forward,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Marker light,Not Registered,2024
4,012524-336,Not Registered,Estus Owens,5,Charter,336,2024-01-25 00:00:00.000,I was backing up at the Embassy suites downtow...,yes,no,Not Registered,JA,3519.02,Not Registered,Not Registered,Not Registered,10:15:00,Not Registered,Nashville Tennessee,Rain,"Dark, No Street Light",Wet,Parking Lot,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,Not Registered,Not Registered,Brian Grimes,Not Registered,Charter,726,2025-05-04 00:00:00.000,As I was driving thru a construction 🚧 I was ...,yes,No,Not Registered,Not Registered,0.0,Not Registered,Not Registered,Not Registered,11:45:00,Not on Gray Line TN Property I59 north and 31s...,Meridian MS,Windy,Daylight,Dry,Interstate/Highway,Driving Forward,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
243,Not Registered,Not Registered,Jerome Asbury,Not Registered,Charter,327,2025-05-04 00:00:00.000,As I turned onto Junior Gilliam Way from Rep J...,yes,No,Not Registered,Not Registered,0.0,Not Registered,Not Registered,Not Registered,1905-07-22 00:00:00,Not on Gray Line TN Property 19 Jr Gilliam Way,Nashville Tennessee,Rain,"Dark, Street Lights On",Wet,Downtown - Nashville,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
244,Not Registered,Not Registered,Todd Stevens,Not Registered,RTA,724,2025-05-07 00:00:00.000,Backed into parked bus,yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,1905-01-18 00:00:00,Lebanon Pike Lot,Not Registered,Cloudy,Dusk,Dry,Lebanon Pike or Shop Parking Lot,Backing,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
245,Not Registered,Not Registered,Donald Hillaker,Not Registered,School Bus,505,2025-05-08 00:00:00.000,Vehicle hit the mirror of a parked truck,yes,No,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,06:48:00,Not on Gray Line TN Property Meridian and Grace,Nashville Tennessee,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025
246,Not Registered,Not Registered,Lonnie McGee,Not Registered,Charter,328,2025-05-11 00:00:00.000,A passenger was unconscious so I called 911 fo...,Not Registered,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,12:25pm,Not on Gray Line TN Property Staley St @ N Mai...,Marion Virginia,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Yes,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,2025

In [55]:
finalcsv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ClaimNo              247 non-null    object
 1   InsClaimNo           247 non-null    object
 2   DriverName           247 non-null    object
 3   EmployeeId           247 non-null    object
 4   Department           247 non-null    object
 5   UnitNo               247 non-null    object
 6   AccidentDate         247 non-null    object
 7   Description          247 non-null    object
 8   Preventable          247 non-null    object
 9   Injury               247 non-null    object
 10  LossOfBonus          247 non-null    object
 11  Coaching             247 non-null    object
 12  FinalJerrysEstimate  247 non-null    object
 13  Estimate             247 non-null    object
 14  OpRepairCost         247 non-null    object
 15  Total                247 non-null    object
 16  Time                 247 non-null    object
 17  Location             247 non-null    object
 18  CityState            247 non-null    object
 19  Weather              247 non-null    object
 20  Lighting             247 non-null    object
 21  RoadSurface          247 non-null    object
 22  RoadType             247 non-null    object
 23  DriverAction         247 non-null    object
 24  PoliceReport         247 non-null    object
 25  DOT Recordable       247 non-null    object
 26  Video                247 non-null    object
 27  Prev                 247 non-null    object
 28  ClaimStatus          247 non-null    object
 29  ClaimAdj             247 non-null    object
 30  Notes                247 non-null    object
 31  VMSAccidentNo        247 non-null    object
 32  Year                 247 non-null    int64
dtypes: int64(1), object(32)
memory usage: 63.8+ KB

## Merging both final Excel and final csv files

In [56]:
final_df = pd.concat([merged_df, finalcsv_df], ignore_index=True, axis=0)

In [57]:
final_df.columns

Index(['ClaimNo', 'DriverName', 'Department', 'AccidentDate',
       'IncidentAccident', 'DOT Recordable', 'UnitNo', 'Description',
       'GLDriverFault', 'NonGLDriverFault', 'GLEmployeeInjury',
       'NonGLEmployeeInjury', 'InsNotified', 'ClaimType', 'JerrysGLBusRepair',
       'Quote', 'CostForOtherVehicleRepair', 'Actual', 'PoliceReport',
       'DriveCam', 'SafetyCommRuling', 'ClaimStatus', 'Year', 'InsClaimNo',
       'GLRepairCost', '3rdPartyCost', 'InsFee', 'Time', 'Location', 'Weather',
       'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'DriverInfo', 'EmployeeId',
       'DriverInjured', 'OpInjured', 'GLBusEstimate', 'GLBusRepair',
       'GLFinalCost', 'OpRepairCost', 'OpInsPaid', 'InsDeductable', 'Total',
       'DriverAction', 'Radius', 'Video', 'Preventable', 'OpFault', 'Injury',
       'GLEstimate', 'Final', 'CityState', 'ClaimAdj', 'Notes',
       'VMSAccidentNo', 'LossOfBonus', 'Coaching', 'FinalJerrysEstimate',
       'Estimate', 'Prev'],
      dtype='object')

In [58]:
final_df

,ClaimNo,DriverName,Department,AccidentDate,IncidentAccident,DOT Recordable,UnitNo,Description,GLDriverFault,NonGLDriverFault,GLEmployeeInjury,NonGLEmployeeInjury,InsNotified,ClaimType,JerrysGLBusRepair,Quote,CostForOtherVehicleRepair,Actual,PoliceReport,DriveCam,SafetyCommRuling,ClaimStatus,Year,InsClaimNo,GLRepairCost,3rdPartyCost,InsFee,Time,Location,Weather,Lighting,RoadSurface,RoadType,ControlDevice,DriverExperience,Raduis,DriverInfo,EmployeeId,DriverInjured,OpInjured,GLBusEstimate,GLBusRepair,GLFinalCost,OpRepairCost,OpInsPaid,InsDeductable,Total,DriverAction,Radius,Video,Preventable,OpFault,Injury,GLEstimate,Final,CityState,ClaimAdj,Notes,VMSAccidentNo,LossOfBonus,Coaching,FinalJerrysEstimate,Estimate,Prev
0,010318-533,Brittney Patterson,School Bus,2018-01-04 00:00:00,Incident,Non-DOT,533,"Driver hit a sign, no damage reported",X,NaN,N,N,N,In-House,NaN,NaN,NaN,NaN,N,N,Preventable,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,010718-1015,Scott Wangrud,Charter,2018-01-07 00:00:00,Incident,Non-DOT,1015,Supposedly hit an Anchor Bus' mirror,X,NaN,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,N,Preventable,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,011518-1021,Thomas House,Charter,2018-01-15 00:00:00,Accident,Non-DOT,1021,Driver hit a sign,X,NaN,N,N,N,In-House,3185.35,NaN,NaN,NaN,N,N,Preventable,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,011618-1015,David Armstrong,Charter,2018-01-16 00:00:00,Accident,Non-DOT,1015,Bus slid into concrete light pole. Parking lot...,NaN,X,N,N,N,In-House,NaN,NaN,NaN,NaN,N,N,Non-Preventable,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,011918-232,William Moncrief,Tour,2018-01-19 00:00:00,Accident,Non-DOT,232,Our bus was hit by Freeman Trucking. Right sid...,NaN,X,N,N,N,OP Ins,NaN,NaN,NaN,NaN,Y,N,Non-Preventable,Open,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,Not Registered,Brian Grimes,Charter,2025-05-04 00:00:00.000,NaN,Not Registered,726,As I was driving thru a construction 🚧 I was ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Not Registered,2025,Not Registered,NaN,NaN,NaN,11:45:00,Not on Gray Line TN Property I59 north and 31s...,Windy,Daylight,Dry,Interstate/Highway,NaN,NaN,NaN,NaN,Not Registered,NaN,NaN,NaN,NaN,NaN,Not Registered,NaN,NaN,Not Registered,Driving Forward,NaN,Not Registered,yes,NaN,No,NaN,NaN,Meridian MS,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,0.0,Not Registered,Not Registered
769,Not Registered,Jerome Asbury,Charter,2025-05-04 00:00:00.000,NaN,Not Registered,327,As I turned onto Junior Gilliam Way from Rep J...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Not Registered,2025,Not Registered,NaN,NaN,NaN,1905-07-22 00:00:00,Not on Gray Line TN Property 19 Jr Gilliam Way,Rain,"Dark, Street Lights On",Wet,Downtown - Nashville,NaN,NaN,NaN,NaN,Not Registered,NaN,NaN,NaN,NaN,NaN,Not Registered,NaN,NaN,Not Registered,Backing,NaN,Not Registered,yes,NaN,No,NaN,NaN,Nashville Tennessee,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,0.0,Not Registered,Not Registered
770,Not Registered,Todd Stevens,RTA,2025-05-07 00:00:00.000,NaN,Not Registered,724,Backed into parked bus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Not Registered,2025,Not Registered,NaN,NaN,NaN,1905-01-18 00:00:00,Lebanon Pike Lot,Cloudy,Dusk,Dry,Lebanon Pike or Shop Parking Lot,NaN,NaN,NaN,NaN,Not Registered,NaN,NaN,NaN,NaN,NaN,Not Registered,NaN,NaN,Not Registered,Backing,NaN,Not Registered,yes,NaN,Not Registered,NaN,NaN,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
771,Not Registered,Donald Hillaker,School Bus,2025-05-08 00:00:00.000,NaN,Not Registered,505,Vehicle hit the mirror of a parked truck,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,Not Registered,2025,Not Registered,NaN,NaN,NaN,06:48:00,Not on Gray Line TN Property Meridian and Grace,Not Registered,Not Registered,Not Registered,Not Registered,NaN,NaN,NaN,NaN,Not Registered,NaN,NaN,NaN,NaN,NaN,Not Registered,NaN,NaN,Not Registered,Not Registered,NaN,Not Registered,yes,NaN,No,NaN,NaN,Nashville Tennessee,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered
772,Not Registered,Lonnie McGee,Charter,2025-05-11 00:00:00.000,NaN,Not Registered,328,A passenger was unconscious so I called 911 fo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,Not Registered,2025,Not Registered,NaN,NaN,NaN,12:25pm,Not on Gray Line TN Property Staley St @ N Mai...,Not Registered,Not Registered,Not Registered,Not Registered,NaN,NaN,NaN,NaN,Not Registered,NaN,NaN,NaN,NaN,NaN,Not Registered,NaN,NaN,Not Registered,Not Registered,NaN,Not Registered,Not Registered,NaN,Yes,NaN,NaN,Marion Virginia,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered,Not Registered

In [59]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773 entries, 0 to 772
Data columns (total 64 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ClaimNo                    767 non-null    object
 1   DriverName                 772 non-null    object
 2   Department                 760 non-null    object
 3   AccidentDate               772 non-null    object
 4   IncidentAccident           125 non-null    object
 5   DOT Recordable             715 non-null    object
 6   UnitNo                     764 non-null    object
 7   Description                768 non-null    object
 8   GLDriverFault              304 non-null    object
 9   NonGLDriverFault           239 non-null    object
 10  GLEmployeeInjury           323 non-null    object
 11  NonGLEmployeeInjury        319 non-null    object
 12  InsNotified                316 non-null    object
 13  ClaimType                  390 non-null    object
 14  JerrysGLBusRepair          137 non-null    object
 15  Quote                      38 non-null     object
 16  CostForOtherVehicleRepair  28 non-null     float64
 17  Actual                     0 non-null      float64
 18  PoliceReport               635 non-null    object
 19  DriveCam                   220 non-null    object
 20  SafetyCommRuling           213 non-null    object
 21  ClaimStatus                565 non-null    object
 22  Year                       773 non-null    int64
 23  InsClaimNo                 423 non-null    object
 24  GLRepairCost               145 non-null    object
 25  3rdPartyCost               34 non-null     float64
 26  InsFee                     206 non-null    float64
 27  Time                       583 non-null    object
 28  Location                   571 non-null    object
 29  Weather                    594 non-null    object
 30  Lighting                   593 non-null    object
 31  RoadSurface                594 non-null    object
 32  RoadType                   593 non-null    object
 33  ControlDevice              80 non-null     object
 34  DriverExperience           203 non-null    object
 35  Raduis                     202 non-null    object
 36  DriverInfo                 64 non-null     object
 37  EmployeeId                 315 non-null    object
 38  DriverInjured              50 non-null     object
 39  OpInjured                  50 non-null     object
 40  GLBusEstimate              50 non-null     float64
 41  GLBusRepair                50 non-null     float64
 42  GLFinalCost                50 non-null     float64
 43  OpRepairCost               316 non-null    object
 44  OpInsPaid                  50 non-null     float64
 45  InsDeductable              50 non-null     float64
 46  Total                      394 non-null    object
 47  DriverAction               391 non-null    object
 48  Radius                     50 non-null     object
 49  Video                      311 non-null    object
 50  Preventable                315 non-null    object
 51  OpFault                    87 non-null     float64
 52  Injury                     340 non-null    object
 53  GLEstimate                 18 non-null     float64
 54  Final                      18 non-null     float64
 55  CityState                  290 non-null    object
 56  ClaimAdj                   249 non-null    object
 57  Notes                      267 non-null    object
 58  VMSAccidentNo              264 non-null    object
 59  LossOfBonus                247 non-null    object
 60  Coaching                   247 non-null    object
 61  FinalJerrysEstimate        247 non-null    object
 62  Estimate                   247 non-null    object
 63  Prev                       247 non-null    object
dtypes: float64(12), int64(1), object(51)
memory usage: 386.6+ KB

## Cleaning the data

In [60]:
# Claim Number retrieval from Accident date and unit no
# Convert AccidentDate to datetime
final_df['AccidentDate'] = pd.to_datetime(final_df['AccidentDate'], errors='coerce')

# Format as MMDDYY (with leading zeros) and keep as string
final_df['AccidentDateFormatted'] = (
    final_df['AccidentDate'].dt.strftime('%m%d%y').where(final_df['AccidentDate'].notna())
)

# Combine into NewClaimNo
final_df['NewClaimNo'] = (
    final_df['AccidentDateFormatted'] + '-' + final_df['UnitNo'].astype('string')
)

# View the result
print(final_df[['AccidentDate', 'UnitNo', 'AccidentDateFormatted', 'NewClaimNo']])

    AccidentDate UnitNo AccidentDateFormatted   NewClaimNo
0     2018-01-04    533                010418   010418-533
1     2018-01-07   1015                010718  010718-1015
2     2018-01-15   1021                011518  011518-1021
3     2018-01-16   1015                011618  011618-1015
4     2018-01-19    232                011918   011918-232
..           ...    ...                   ...          ...
768   2025-05-04    726                050425   050425-726
769   2025-05-04    327                050425   050425-327
770   2025-05-07    724                050725   050725-724
771   2025-05-08    505                050825   050825-505
772   2025-05-11    328                051125   051125-328

[773 rows x 4 columns]

In [61]:
# Clean the DriverName column
final_df['DriverName'] = (
    final_df['DriverName']
    .str.replace(',', '', regex=False)         # Remove commas
    .str.strip()                               # Remove leading/trailing whitespace
    .str.replace(r'\s+', ' ', regex=True)      # Collapse multiple spaces into one
)

# Converting date time to date only
final_df['AccidentDate'] = pd.to_datetime(final_df['AccidentDate'], errors='coerce')

#Fixing the multiple column values to 'Y' and 'N' for 'DOT Recordable'
final_df['DOT Recordable'] = final_df['DOT Recordable'].replace({'Non-DOT':'N', 
                                                                 'DOT':'Y', 
                                                                 'FALSE':'N',
                                                                 'TRUE':'Y',
                                                                 False:'N', 
                                                                 True: 'Y', 
                                                                 'non-DOT':'N', 
                                                                 'NON-DOT':'N', 
                                                                 'NON DOT': 'N', 
                                                                 '?':'Not Registered',
                                                                 'NON -DOT':'N'})

final_df['DOT Recordable'] = final_df['DOT Recordable'].fillna('NA')



#Fixing the multiple column values of 'IncidentAccident' column
final_df['IncidentAccident'] = final_df['IncidentAccident'].replace({'?':'Not Registered',
                                                                     'Accident ':'Accident',
                                                                     'Accidednt ':'Accident',
                                                                     'Accident?':'Accident?',
                                                                     'Accidnet':'Accident',
                                                                     'accident':'Accident',
                                                                     'accident ':'Accident',
                                                                     'INCIDENT':'Incident',
                                                                     'Incident ':'Incident',
                                                                     'ACCIDENT':'Accident',
                                                                     'Accicdent ':'Accident',
                                                                     'Accidednt':'Accident',
                                                                     'Incident / Accident':'Incident / Accident',
                                                                     'Mystery ':'Mystery'})
final_df['IncidentAccident'] = final_df['IncidentAccident'].fillna('NA')

#Fixing the multiple column values of 'PoliceReport' column
final_df['PoliceReport'] = final_df['PoliceReport'].replace({'No':'N',
                                                             'Yes':'Y',
                                                             'FALSE':'N',
                                                             'TRUE':'Y',
                                                             False:'N',
                                                             True:'Y',
                                                             'Na':'Not Registered'})

##Fixing the multiple column values of 'DriverInjured' column
final_df['DriverInjured'] = final_df['DriverInjured'].replace({'FALSE':'N',
                                                               'TRUE' : 'Y',
                                                                False:'N',
                                                                True:'Y'
                                                               })

##Fixing the multiple column values of 'OpInjury' column
final_df['OpInjured'] = final_df['OpInjured'].replace({'FALSE':'N',
                                                       'TRUE' : 'Y',
                                                        False:'N',
                                                        True:'Y'
                                                       })

##Fixing the multiple column values of 'Injury' column
final_df['Injury'] = final_df['Injury'].replace({'No':'N',
                                                 'NO':'N',
                                                 'No ':'N',
                                                 'no':'N',
                                                 'Yes':'Y',
                                                 'FALSE':'N',
                                                 'TRUE':'Y',
                                                  False:'N'
                                                })





final_df['Weather'] = final_df['Weather'].replace({'Cler':'Clear and Sunny',
                                                   'clear':'Clear and Sunny',
                                                   'CLear':'Clear and Sunny',
                                                   'Clear':'Clear and Sunny',
                                                   'Windy':'Clear and Sunny',
                                                   'cloudy':'Cloudy',
                                                   'Dreary':'Cloudy',
                                                   'Overcast':'Cloudy',
                                                   'Dry': 'Clear and Sunny',
                                                   'dry':'Clear and Sunny',
                                                   'Mostly sunny':'Clear and Sunny',
                                                   'It had just started to rain after the accident ':'Cloudy',
                                                   'Although weather was clear but it happen either over night or next day ':'Clear and Sunny',
                                                   'Heavy rain and fog':'Rain',
                                                   'rain':'Rain',
                                                   'Sprinkle ':'Rain',  
                                                   'Icy roads':'Snow and Icy',
                                                   'Sleet': 'Snow and Icy',
                                                   'Snow': 'Snow and Icy',
                                                   '?': 'Not Registered',
                                                   'Notclear':'Not Registered',
                                                   'N':'Not Registered'
                                               })



final_df['Lighting'] = final_df['Lighting'].replace({'dark':'Night',
                                                     'Dark':'Night',
                                                 'Dark no street lights':'Night',
                                                 'Dark, no street lights on':'Night',
                                                 'Dark, No Street Light':'Night',
                                                 'Dark, Street Lights On':'Night',
                                                 'Dawn':'Morning',
                                                 'dawn':'Morning',
                                                 'morning':'Morning',
                                                 'dusk':'Evening',
                                                 'Dusk':'Evening',
                                                 'evening':'Evening',
                                                 'Daylight': 'Daytime',
                                                 'daylight':'Daytime',
                                                 'light':'Daytime',
                                                 'cloudy':'Daytime',
                                                 'Cloudy':'Daytime',
                                                 'night':'Night',
                                                  })


##Fixing the multiple column values of 'SafetyCommRuling' column

final_df['Prevent'] = final_df['SafetyCommRuling'].combine_first(final_df['Preventable'])
final_df['Prevent'] = final_df['Prevent'].replace({'Non-Preventable':'N',
                                                   'Preventable':'Y',
                                                   'o-Prevetable':'N',
                                                   'Non-Preventable ':'N',
                                                   'no':'N',
                                                   'no ':'N',
                                                   'yes':'Y',
                                                   'Yes':'Y',
                                                   'True':'Y',
                                                   'No':'N',
                                                    False:'N',
                                                    True:'Y'
                                                  })


final_df = final_df.drop(columns=['SafetyCommRuling', 'Preventable'])


final_df['RoadSurface'] = final_df['RoadSurface'].replace({'Dry':'Dry',
                                                           'DRY':'Dry',
                                                   'Wet':'Wet',
                                                   'dry':'Dry',
                                                   'muddy':'Muddy',
                                                   'Muddy':'Muddy',
                                                   'gravel':'Gravel',
                                                   'Gravel/Dirt':'Gravel',
                                                   'Gravel':'Gravel',
                                                   "It didn't start to rain until after the accident ":'Dry',
                                                   'Icy':'Icy',
                                                   'Snowy':'Snow',
                                                   'paved':'Paved',
                                                   'Parking Lot':'Parking Lot'
                                                  })

In [62]:
final_df['CityState'] = final_df['CityState'].replace({'Bolling Green, KY':'Bowling Green,KY',
                                                       'Athens GA':'Athens,GA',
                                                       'Nashville, TN':'Nashville,TN',
                                                       'Nashville Tennessee':'Nashville,TN',
                                                       'Nashville, TN ':'Nashville,TN',
                                                       'Nashville TN ':'Nashville,TN',
                                                       'Nashville TN ':'Nashville,TN',
                                                       'Nashville Tn ':'Nashville,TN',
                                                       'Nashville, Tn':'Nashville,TN',
                                                       'Nashville':'Nashville,TN',
                                                       'Nashville Tn':'Nashville,TN',
                                                       'Nashville. Tn':'Nashville,TN',
                                                       'Nashville TN':'Nashville,TN',
                                                       'Lebanon tn':'Lebanon,tn',
                                                       'Atlanta Georgia ':'Atlanta,GA',
                                                       'Atlanta GA':'Atlanta,GA',
                                                       'Carbondale, IL':'Carbondale,IL',
                                                       'Nashville  Tennessee ':'Nashville,TN',
                                                       'Elizabeth town kentucky':'Elizabeth Town,KY',
                                                       'Boston Massachusetts':'Boston,MA',
                                                       'Chattanooga, TN':'Chattanooga,TN',
                                                       'Nashville tn bna airport':'Nashville,TN',
                                                       'Nashville ':'Nashville,TN',
                                                       'Nashville,TN ':'Nashville,TN',
                                                       'Nashville, Tn.':'Nashville,TN',
                                                       'Nashville Tennessee ':'Nashville,TN',
                                                       'Nashville, Tennessee ':'Nashville,TN',
                                                       'Nashville tn ':'Nashville,TN',
                                                       'Nashville,Tn':'Nashville,TN',
                                                       '2200 Elm Hill Pike':'Nashville,TN',
                                                       'Nashville BNA DROP OFF departures':'Nashville,TN',
                                                       'Nashville , Tn':'Nashville,TN',
                                                       'Near Pelham TN':'Pelham,TN',
                                                       'Chicago Ill':'Chicago,Ill',
                                                       'Between  Louisville and Cincinnati ':'Louisville,KY',
                                                       'Bowling Green Kentucky ':'Bowling Green,KY',
                                                       'Dahlonea GA1':'Dahlonea,GA',
                                                       'Revere, Massachusetts ':'Revere,MA ',
                                                       'Boston, MA':'Boston,MA',
                                                       'Alexandria Va':'Alexandria,VA',
                                                       'Washington DC.':'Washington DC,DC',
                                                       'Washington DC':'Washington DC,DC',
                                                       'Washington D.C.':'Washington DC,DC',
                                                       'Tupelo Ms.':'Tupelo,MS',
                                                       'Belvedere Tennessee ':'Belvedere,TN',
                                                       'NashvilleTn ':'Nashville,TN',
                                                       'Nashville ,TN':'Nashville,TN',
                                                       'Madison Tn ':'Madison,TN',
                                                       'Mackinaw City, Michigan. ':'Mackinaw City,MI',
                                                       'Hendersonville Tennessee':'Hendersonville,TN',
                                                       'Chester NY':'Chester,NY',
                                                       'Shelbyville, TN':'Shelbyville,TN',
                                                       'West Frankfurt,  IL ':'West Frankfurt,IL',
                                                       'Missouri entering Illinois (approximately)':'St.Louis,MO',
                                                       'Outter Limits Ashville NC Mile Marker 43 I-40W':'Ashville,NC',
                                                       'Nashville TN Lipscomb university ':'Nashville,TN',
                                                       'Whites Creek, TN':'Whites Creek,TN',
                                                       'Nashville  TN ':'Nashville,TN',
                                                       'Nasshville Tn':'Nashville,TN',
                                                       'Ft. Campbell, KY.':'Ft.Campbell,KY',
                                                       'Birmingham AL':'Birmingham,AL',
                                                       'Antioch, TN':'Antioch,TN',
                                                       'Nashville,  TN':'Nashville,TN',
                                                       'Nashville tN':'Nashville,TN',
                                                       'Nashville tn':'Nashville,TN',
                                                       'Nashville,Tennessee ':'Nashville,TN',
                                                       'Clinton, MS':'Clinton,MS',
                                                       'Nashville, Tennessee':'Nashville,TN',
                                                       'Lebanon Lot Nashville, TN':'Lebanon,TN',
                                                       'Nashville, Tn ':'Nashville,TN',
                                                       'Atlanta ga':'Atlanta,GA',
                                                       'Antioch TN':'Antioch,TN',
                                                       'Lynchburg TN.':'Lynchburg,TN',
                                                       'Warenton Virginia':'Warenton,VA',
                                                       'Near Joelton, TN':'Joelton,TN',
                                                       'Branson Mo.':'Branson,MO',
                                                       'Courtyard Green Hills 3800 Bedford Ave':'Green Hills,TN',
                                                       'Franklin, TN':'Franklin,TN',
                                                       'Boston mass...mass ave by Harvard ':'Boston,MA',
                                                       'Boston, Massachusetts':'Boston,MA',
                                                       'Nashville  Tn':'Nashville,TN',
                                                       'Cornelia':'Cornelia,GA',
                                                       'Jacksonville Alabama ':'Jacksonville,AL',
                                                       'Jacksonville, Alabama ':'Jacksonville,AL',
                                                       'Hopkinsville Ky':'Hopkinsville,Ky',
                                                       'Nashville Tn.':'Nashville,TN',
                                                       'Antioch , Tn':'Antioch,TN',
                                                       'Gallatin, Tennessee':'Gallatin,TN',
                                                       'Murfreesboro TN':'Murfreesboro,TN',
                                                       'Murphy Athletic Center MTSU':'Murfreesboro,TN',
                                                       'Jackson, TN ': 'Jackson,TN',
                                                       'Jackson TN':'Jackson,TN',
                                                       'Antioch tn':'Antioch,TN',
                                                       'Nashville tennessee':'Nashville,TN',
                                                       'Nashville, TN.':'Nashville,TN',
                                                       'Nashville,  Tennessee ':'Nashville,TN',
                                                       'Tn nashville':'Nashville,TN',
                                                       'Nashville  TN':'Nashville,TN',
                                                       'Nashville aTN':'Nashville,TN',
                                                       'Spring lake  NC':'Spring lake,NC',
                                                       'Antioch Tennessee ':'Antioch,TN',
                                                       'Marietta Georgia':'Marietta,GA',
                                                       'Birmingham Alabama ':'Birmingham,AL',
                                                       'Cookeville TN':'Cookeville,TN',
                                                       'I-40 east bound Sevir County  near exit 407':'Gatlinburg,TN',
                                                       'Coopertown tn':'Coopertown,TN',
                                                       'Antioch, TN ':'Antioch,TN',
                                                       'Bowling Green, KY':'Bowling Green,KY',
                                                       'Meridian MS':'Meridian,MS',
                                                       'Marion Virginia ':'Marion,VA'
       
                                                       })

In [63]:
final_df['City'] = final_df['CityState'].str.split(',').str[0]
final_df['City'].unique()

array([nan, 'Nashville', 'Fort Bragg', 'Bowling Green', 'Ferriday', 'No',
       'Yes', 'Athens', 'Southaven', 'Not Registered', 'Atlanta',
       'Carbondale', 'Elizabeth Town', 'Boston', 'Chattanooga', 'Lebanon',
       'Chicago', 'Louisville', 'Dahlonea', 'Pelham', 'Revere',
       'Alexandria', 'Washington DC', 'Tupelo', 'Belvedere', 'Madison',
       'Mackinaw City', 'Hendersonville', 'Chester', 'Shelbyville',
       'West Frankfurt', 'St.Louis', 'Ashville', 'Whites Creek',
       'Ft.Campbell', 'Birmingham', 'Antioch', 'Clinton', 'Lynchburg',
       'Warenton', 'Joelton', 'Branson', 'Green Hills', 'Franklin',
       'Cornelia', 'Jacksonville', 'Hopkinsville', 'Gallatin',
       'Murfreesboro', 'Jackson', 'Spring lake', 'Marietta', 'Cookeville',
       'Gatlinburg', 'Coopertown', 'Meridian', 'Marion'], dtype=object)

In [64]:
final_df['State'] = final_df['CityState'].str.split(',').str[1]
final_df['State'].unique()

array([nan, 'TN', ' NC', 'KY', ' LA', 'GA', ' MS', 'IL', 'MA', 'tn',
       'Ill', 'MA ', 'VA', 'DC', 'MS', 'MI', 'NY', 'MO', 'NC', 'AL', 'Ky'],
      dtype=object)

In [65]:
name_typos = {
    'Bobby Richie': 'Bobby Richey',
    'William Dickersoff': 'William Dickerhoff',
    'Bill Dickerhoff': 'William Dickerhoff',
    'Bill Dickersoff': 'William Dickerhoff',
    'Austin Zumbrogrel': 'Austin Zumbrogel',
    'Bryan Espinoza': 'Bryan Espinosa',
    'Dave Armstrong': 'David Armstrong',
    'Don Thomas': 'Donald Thomas',
    'Danisha Vazquez': 'Denisha Vazquez',
    'Denisah Vazquez': 'Denisha Vazquez',
    'Douglas Bumpas': 'Douglas Bumpus',
    'Doug Bumpas': 'Douglas Bumpus',
    'Doug Bumpus': 'Douglas Bumpus',
    'Duane Alan Whitt': 'Duane Whitt',
    'Duane Allan Whitt': 'Duane Whitt',
    'Duane Alan Whit': 'Duane Whitt',
    'Duane Allan Whit': 'Duane Whitt',
    'Dwayne Alan Whitt': 'Duane Whitt',
    'Dwayne Allan Whitt': 'Duane Whitt',
    'Dwayne Whitt': 'Duane Whitt',
    'Frank Dirr': 'Francis Dirr',
    'RichardShoulders': 'Richard Shoulders',
    'Sameh shaker':'Sameh Shaker',
    'shop (R.Clark)':'Shop (R.Clark)',
    'PaulaMilligan':'Paula Milligan',
    'Trumell HaY':'Trumell Haynes',
    'Trumell Haynes?':'Trumell Haynes',
    'Mytery':'Mystery',
    'Rob Schneider':'Robert Schneider',
    'SHARON JUSTICE':'Sharon Justice',
    'jackie briggs':'Jackie Briggs',
    'Adrienne Reagan':'Adrienne Reagon',
    'Jackson Thomas': 'Thomas Jackson',
    'Jennifer Stephens': 'Jenniefer Stephens',
    'Jennifer stephens': 'Jenniefer Stephens',
    'Jennifer Stevens': 'Jenniefer Stephens',
    'Jenniefer Stevens': 'Jenniefer Stephens',
    'Jermaine McKissak': 'Jermaine McKissack',
    'Jermaine Mckissack': 'Jermaine McKissack',
    'Jermaine Mckissak': 'Jermaine McKissack',
    'John DeBose': 'John Dubose',
    'John Debose': 'John Dubose',
    'John DuBose': 'John Dubose',
    'John Tom Dubose': 'John Dubose',
    'John Tom DuBose': 'John Dubose',
    'John Tom Debose': 'John Dubose',
    'John Tom DeBose': 'John Dubose',
    'Tom Dubose': 'John Dubose',
    'Tom DuBose': 'John Dubose',
    'Tom DeBose': 'John Dubose',
    'Tome Debose': 'John Dubose',
    'Kathy Jaccobs': 'Kathy Jacobs',
    'Keela Fleming': 'Keela Fleeming',
    'Ken Dillon': 'Kenneth Dillon',
    'Lannell Mcgee': 'Lannell McGee',
    'Lannel McGee': 'Lannell McGee',
    'Lannel Mcgee': 'Lannell McGee',
     'Lugene Love Jr.': 'Lugene Love',
    'Lugene Love Jr': 'Lugene Love',
    'Lugene Love Junior': 'Lugene Love',
    'Ware Marshall': 'Marshall Ware',
    'Ware, Marshall': 'Marshall Ware',
    'Ware Marshel': 'Marshall Ware',
    'Marshall, Ware': 'Marshall Ware',
    'Marshel Ware': 'Marshall Ware',
    'Mike Beattie': 'Michael Beattie',
    'Ron King': 'Ronald King',
    'Ron King?': 'Ronald King',
    'Shawn Yorkley': 'Shawn Yokley',
    'Vicky Wooten': 'Vicky Wootton',
    'Wayne Dominquez': 'Wayne Dominguez',
    'Bill Champion': 'William Champion',
    'Bill Moncrief': 'William Moncrief',
    'Bill Schulz': 'William Schulz',
    'OWENS':'Owens'
}
final_df['DriverName'] = final_df['DriverName'].map(name_typos).fillna(final_df['DriverName'])

In [66]:
# Creating a unique ID for drivername
def assign_sequential_ids(DriverName):
    assigned_ids = {}
    counter = 1
    for entry in DriverName:
        if entry not in assigned_ids:
            assigned_ids[entry] = f"{counter:04d}"
            counter += 1
    return assigned_ids

DriverId = assign_sequential_ids(final_df['DriverName'])

final_df['DriverId'] = final_df['DriverName'].map(DriverId)
print(DriverId)

{'Brittney Patterson': '0001', 'Scott Wangrud': '0002', 'Thomas House': '0003', 'David Armstrong': '0004', 'William Moncrief': '0005', 'Mike Birdsong': '0006', 'Lee Johnson': '0007', 'Thomas Jackson': '0008', 'Rawand Koyee': '0009', 'Moenig Jeff': '0010', 'Kim Sandman': '0011', 'Steve Billingslea': '0012', 'Robert Norman': '0013', 'Jane Robeck': '0014', 'Lonnell Wright': '0015', 'Marshall Ware': '0016', 'Robert Oliver': '0017', 'Jenniefer Stephens': '0018', 'Keela Fleeming': '0019', 'Paul Duncan': '0020', 'Michael Transley': '0021', 'Robert Kimbrell': '0022', 'Diane Bolden': '0023', 'Lee McClendon': '0024', 'Jerry Lay': '0025', 'Cindy Myers': '0026', 'David Hill': '0027', 'Richard Wordlaw': '0028', 'James Bradford': '0029', 'Will': '0030', 'Justin Liss': '0031', 'Gregory Yopp': '0032', 'Max Wallace': '0033', 'Shelena Shaw': '0034', 'William Champion': '0035', 'Corwyn Hodge': '0036', 'John Dubose': '0037', 'Merita Abernathy': '0038', 'Gary Kenny': '0039', 'Michael Kirkwood': '0040', 'Douglas Bumpus': '0041', 'Gianikas Green': '0042', 'Terrence Bailey': '0043', 'Landis Menzie': '0044', 'Dale Jefferies': '0045', 'William Schulz': '0046', 'Reported by David Hill': '0047', 'Fred Vaughn': '0048', 'Janina Crotzer': '0049', 'Lannell McGee': '0050', 'Tammy Matheson': '0051', 'Shana Vaughn': '0052', 'Robert Anderson': '0053', 'Melissa Eauclaire': '0054', 'Iben Batey': '0055', 'Ronald King': '0056', 'Lopez (Mechanic)': '0057', 'Lashawanda Nevels': '0058', 'Lugene Love': '0059', 'Dimple Womack': '0060', 'Stu Barr': '0061', 'William Woods': '0062', 'Tonya Johnson': '0063', 'Carl Washington': '0064', 'Tammy Cannon': '0065', 'Richard Shoulders': '0066', 'Jane Wilson': '0067', 'Suzann Stanford': '0068', 'Zachary Cobb': '0069', 'Letisha Ewing': '0070', 'Valerie Pointer': '0071', 'Arnitra Horne': '0072', 'Fred Dixon': '0073', 'Lee Greer': '0074', 'Mary Papastefanou': '0075', 'John Bowden': '0076', 'Ed Hill': '0077', 'Orville Cox': '0078', 'Kierra Thompson': '0079', 'Michel Makangara': '0080', 'Estus Owens': '0081', 'Owens': '0082', 'Clyde Harris': '0083', 'Crystal Barnosky': '0084', 'Randell Robertson': '0085', 'Martin Johnson': '0086', 'Mystery': '0087', 'Unknown Reported by Steve': '0088', 'Reported by Tara': '0089', 'Reported by Bill Wallace': '0090', 'Terry Cherry': '0091', 'Rodney Boehm': '0092', 'Cedric Hatchett': '0093', 'Lonnie McGee': '0094', 'Jerry Mischler': '0095', 'Shawn Yokley': '0096', 'James Johnson': '0097', 'David Brown': '0098', 'Sadie Demoss': '0099', 'Johnny Smith': '0100', 'Denandra Olanumi': '0101', 'Kathy Jacobs': '0102', 'mystery': '0103', 'larry pennington': '0104', 'Angela Whitman': '0105', 'William Dickerhoff': '0106', 'Bryan Espinosa': '0107', 'Wendell Mason': '0108', 'Jimmy Glenn': '0109', 'Mystery/Johnny Smith reported': '0110', 'Bobby Richey': '0111', 'Constance Lee': '0112', 'Lisa Murray': '0113', 'Greg Hankins': '0114', 'Christine Leak': '0115', 'Robert Shaw': '0116', 'Anthony Wells': '0117', 'Jochen Weirich': '0118', 'Garry Phanor': '0119', 'Pat Schoen': '0120', 'Sameh Shaker': '0121', 'Glenn Brannen': '0122', 'Shop (R.Clark)': '0123', 'Paula Milligan': '0124', 'Cierra Monley': '0125', 'Derrick Lowe': '0126', 'Dawn McFarland': '0127', 'Raul Galarza': '0128', 'James Woods': '0129', 'Cheryl swett': '0130', 'Tammy Bolling': '0131', 'William Parrett': '0132', 'Farazdaq Almasyabi': '0133', 'Tony at the shop': '0134', 'Tanisha Morrow': '0135', 'Trumell Haynes': '0136', 'Adrienne Reagon': '0137', 'Lisa Cotton': '0138', 'Steve Waldrop': '0139', 'Parked Bus': '0140', 'Constance Collins': '0141', 'Michael Beattie': '0142', 'Chadwick Jeffery': '0143', 'Thomas Northern': '0144', 'Regina Lawrence': '0145', 'Dale Jaco': '0146', 'Kelly Westerlund': '0147', 'Duane Whitt': '0148', 'Gerald Gooch': '0149', 'Danelle Stephens': '0150', 'Linda Pratt-Thompson': '0151', 'Jermaine McKissack': '0152', "L'Tanya Bolden": '0153', 'James Wiedemeirer': '0154', 'Denisha Vazquez': '0155', 'Bobby Pruett': '0156', 'JD Wilson': '0157', 'Mystery/Tangie Curtis': '0158', 'Austin Zumbrogel': '0159', 'Steve Papai': '0160', 'Terrence Dowlen': '0161', 'Raymond Holman': '0162', 'Syed Shariff': '0163', 'Christopher Bay': '0164', 'Jerry Randolph': '0165', 'Jose Anders': '0166', 'Wayne Dominguez': '0167', 'James King': '0168', 'Quantas Hicks': '0169', 'Ted Chesnut': '0170', 'Debbie Lening': '0171', 'Joyce Harrison': '0172', 'Todd Eaton': '0173', 'Xavier Peoples': '0174', 'Dasia Eason': '0175', 'David Stovall': '0176', 'Theo Wiley': '0177', 'Antionette Givens': '0178', 'Lisa Wright': '0179', 'Linda Walker': '0180', 'Sadie DeMoss': '0181', 'Jamario Baugh': '0182', 'Vicky Wootton': '0183', 'Steve Jones': '0184', 'Eric Cartwright': '0185', 'Jerry Rex': '0186', 'Clifton Hammock': '0187', 'Keith Hall': '0188', 'MIchelle Gustafson': '0189', 'Jimmy Johnson': '0190', 'Cynthia Crueter': '0191', 'David Tucker': '0192', 'David Wood': '0193', 'Devika Reed': '0194', 'Terry Arnold': '0195', 'Sherena Lee': '0196', 'Ana Torres': '0197', 'James Hyman': '0198', nan: '0199', 'Shelena Idom': '0200', 'Robert Schneider': '0201', 'Narkeater Smith': '0202', 'Robert Clark': '0203', 'Kimberly Perkins': '0204', 'Al Simmons': '0205', 'Donald Thomas': '0206', 'Kenneth Kiel': '0207', 'Alesha Harney': '0208', 'Antonio Summers': '0209', 'William Greer': '0210', 'Edward McFeders': '0211', 'Lewayne Jackson': '0212', 'Arnitha Wiley': '0213', 'Michael Birdsong': '0214', 'Karen Proteau': '0215', 'Patrick Shoen': '0216', 'Michael Hales': '0217', 'Cathy Martin': '0218', 'Eric Izzo': '0219', 'Elizabeth Burton': '0220', 'Francis Dirr': '0221', 'Franklin Jackson': '0222', 'Jenniefer stephens': '0223', 'DeYoung Dirk': '0224', 'James Ridley': '0225', 'Richard Stults': '0226', 'Aaron McLaughlin': '0227', 'Christian Collazos': '0228', 'Phillip Reding': '0229', 'Deon Thomas': '0230', 'Tangie Curtis': '0231', 'Steven Rempis': '0232', 'John Harman': '0233', 'John Dubberly': '0234', 'Joseph Richey': '0235', 'Yajaira Diaz': '0236', 'James Ringenberg': '0237', 'Daryl Braden': '0238', 'Roger Trimble': '0239', 'Heather Gray': '0240', 'Ronda Crowne': '0241', 'Michael Porter': '0242', 'Austin Anderson': '0243', 'Jaclyn Slaughter': '0244', 'Herbert Grant': '0245', 'Hafizah Shamsiddeen': '0246', 'Randall Ambrose': '0247', 'Mary Finley': '0248', 'Justin Jones': '0249', 'Terrence Anthony': '0250', 'Chanty Claybrooks': '0251', 'Charles Leavitt': '0252', 'Ken Kiel': '0253', 'Chad Hudgins': '0254', 'John Flatt': '0255', 'Tammy Hisle': '0256', 'Dannie Collins': '0257', 'Devon Whitmore': '0258', 'Troy Fontechia': '0259', 'DERRICK Lowe': '0260', 'Donald Hillaker': '0261', 'Derron Gray': '0262', 'Cathy Fields': '0263', 'Kiarra Walker': '0264', 'Brenda Boyd': '0265', 'David Suddeth': '0266', 'Wendy Lymas': '0267', 'Antoinette Thompson': '0268', 'Natasha Vaughn': '0269', 'Cynthia Horner': '0270', 'Frank Westmoreland': '0271', 'Gary Downey': '0272', 'Joshua Grimmage': '0273', 'Elvira Beaudu': '0274', 'Vicki Lawrence': '0275', 'Ketoya Dobbins': '0276', 'Donald Harp': '0277', 'Weldon Cannon': '0278', 'Dyana Gantt': '0279', 'Dominique Burnett': '0280', 'Vince Booker': '0281', 'martin johnson': '0282', 'Anthony Tucker': '0283', 'CJ Leavitt': '0284', 'Carmara Shaw': '0285', 'Maria Modica': '0286', 'Shirgul Aryobi': '0287', 'Gregory Grubbs': '0288', 'Tashelia Murphy': '0289', 'Cherita Boyd': '0290', 'Kevonye Bennett': '0291', 'Tyree Hayes': '0292', 'Keyosha Blair': '0293', 'Terry Jones': '0294', 'Kabres Chism': '0295', 'Charlay Hill': '0296', 'Anthony Jaco': '0297', 'Shirley Thompson': '0298', 'Steve Crino': '0299', 'Sharon Justice': '0300', 'Michael Cotter Sr': '0301', 'Shondrea Carney': '0302', 'Gabriel Rupert': '0303', 'Kenneth Dillon': '0304', 'Kamisha Jefferson': '0305', 'Lillian Cain': '0306', 'Rodolfo Delgadillo': '0307', 'Brent Jenson': '0308', 'Jackie Briggs': '0309', 'Zach Luetters': '0310', 'Marlies Parent': '0311', 'Shamecka Hypolite': '0312', 'John Malone': '0313', 'Oswald Osse': '0314', 'Jennifer Williams': '0315', 'Denise Asbury': '0316', 'Jeffery Beaty': '0317', 'Anthony Thomas': '0318', 'Austin Clark': '0319', 'Russell Harris': '0320', 'Sam Hanson': '0321', 'Varisha Ramey': '0322', 'Brian Grimes': '0323', 'Sharetha Hughes': '0324', 'Tara Olsen': '0325', 'Chaz Lillard': '0326', 'Michael Mastin': '0327', 'Natasha Thompson': '0328', 'David King': '0329', 'Veronica Omar': '0330', 'William Brannen': '0331', 'William Taylor': '0332', 'Richard Griffin': '0333', 'Bradley Buck': '0334', 'Kentey Harris': '0335', 'Reginald Laing': '0336', 'April Martin': '0337', 'Mieocha Hughes': '0338', 'Jennifer Tate': '0339', 'Lynne McClelland': '0340', 'Rosheka Douglas': '0341', 'Thaddeus Nesby': '0342', 'Greg Duncan': '0343', 'Devvin Adcox': '0344', 'Cj Leavitt': '0345', 'Misty Payne': '0346', 'Joyce Questelles': '0347', 'Pan’Ehyeh-Khemdaw Ehyeh': '0348', 'Mashondra Driver': '0349', 'Lauralee C Zavorski': '0350', 'Ehron Nay': '0351', 'Lynette Madry': '0352', 'Isaac Bland': '0353', 'Nick Eugene': '0354', 'Randy Canter': '0355', 'Andre Alexander': '0356', 'Donna Allen': '0357', 'Jeff Moenig': '0358', 'Mike Jordan': '0359', 'Gordon Ferrell': '0360', 'Jerome Asbury': '0361', 'Emilio Valdez': '0362', 'Joshua Moffitt': '0363', 'Nabeel Sameen': '0364', 'Lakeishane Crawford': '0365', 'Crystal Smith': '0366', 'Derrick Horton': '0367', 'Patricia Schmidt': '0368', 'Eloise Gunn': '0369', 'Tim Hodges': '0370', 'Gregory Duncan': '0371', 'Justin Tekoppel': '0372', 'Shae Johnson': '0373', 'Renzo Weaver': '0374', 'Nicole Harris': '0375', 'Claudia Hopson': '0376', 'Todd Stevens': '0377'}

In [67]:
final_df.head()

,ClaimNo,DriverName,Department,AccidentDate,IncidentAccident,DOT Recordable,UnitNo,Description,GLDriverFault,NonGLDriverFault,GLEmployeeInjury,NonGLEmployeeInjury,InsNotified,ClaimType,JerrysGLBusRepair,Quote,CostForOtherVehicleRepair,Actual,PoliceReport,DriveCam,ClaimStatus,Year,InsClaimNo,GLRepairCost,3rdPartyCost,InsFee,Time,Location,Weather,Lighting,RoadSurface,RoadType,ControlDevice,DriverExperience,Raduis,DriverInfo,EmployeeId,DriverInjured,OpInjured,GLBusEstimate,GLBusRepair,GLFinalCost,OpRepairCost,OpInsPaid,InsDeductable,Total,DriverAction,Radius,Video,OpFault,Injury,GLEstimate,Final,CityState,ClaimAdj,Notes,VMSAccidentNo,LossOfBonus,Coaching,FinalJerrysEstimate,Estimate,Prev,AccidentDateFormatted,NewClaimNo,Prevent,City,State,DriverId
0,010318-533,Brittney Patterson,School Bus,2018-01-04,Incident,N,533,"Driver hit a sign, no damage reported",X,NaN,N,N,N,In-House,NaN,NaN,NaN,NaN,N,N,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,010418,010418-533,Y,NaN,NaN,0001
1,010718-1015,Scott Wangrud,Charter,2018-01-07,Incident,N,1015,Supposedly hit an Anchor Bus' mirror,X,NaN,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,N,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,010718,010718-1015,Y,NaN,NaN,0002
2,011518-1021,Thomas House,Charter,2018-01-15,Accident,N,1021,Driver hit a sign,X,NaN,N,N,N,In-House,3185.35,NaN,NaN,NaN,N,N,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,011518,011518-1021,Y,NaN,NaN,0003
3,011618-1015,David Armstrong,Charter,2018-01-16,Accident,N,1015,Bus slid into concrete light pole. Parking lot...,NaN,X,N,N,N,In-House,NaN,NaN,NaN,NaN,N,N,Closed,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,011618,011618-1015,N,NaN,NaN,0004
4,011918-232,William Moncrief,Tour,2018-01-19,Accident,N,232,Our bus was hit by Freeman Trucking. Right sid...,NaN,X,N,N,N,OP Ins,NaN,NaN,NaN,NaN,Y,N,Open,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,011918,011918-232,N,NaN,NaN,0005

In [68]:
graylinefleetrenamed_df_selected = graylinefleetrenamed_df[['FleetNo', 'Department']]
#final_df = pd.concat([df1, graylinefleetrenamed_df_selected], ignore_index=True, axis=0)
final_df1 = final_df.merge(graylinefleetrenamed_df_selected, how='left', left_on='UnitNo', right_on='FleetNo')
#result = df1.merge(df2, how='left', left_on='id1', right_on='id2')

In [69]:
final_df1.columns

Index(['ClaimNo', 'DriverName', 'Department_x', 'AccidentDate',
       'IncidentAccident', 'DOT Recordable', 'UnitNo', 'Description',
       'GLDriverFault', 'NonGLDriverFault', 'GLEmployeeInjury',
       'NonGLEmployeeInjury', 'InsNotified', 'ClaimType', 'JerrysGLBusRepair',
       'Quote', 'CostForOtherVehicleRepair', 'Actual', 'PoliceReport',
       'DriveCam', 'ClaimStatus', 'Year', 'InsClaimNo', 'GLRepairCost',
       '3rdPartyCost', 'InsFee', 'Time', 'Location', 'Weather', 'Lighting',
       'RoadSurface', 'RoadType', 'ControlDevice', 'DriverExperience',
       'Raduis', 'DriverInfo', 'EmployeeId', 'DriverInjured', 'OpInjured',
       'GLBusEstimate', 'GLBusRepair', 'GLFinalCost', 'OpRepairCost',
       'OpInsPaid', 'InsDeductable', 'Total', 'DriverAction', 'Radius',
       'Video', 'OpFault', 'Injury', 'GLEstimate', 'Final', 'CityState',
       'ClaimAdj', 'Notes', 'VMSAccidentNo', 'LossOfBonus', 'Coaching',
       'FinalJerrysEstimate', 'Estimate', 'Prev', 'AccidentDateFormatted',
       'NewClaimNo', 'Prevent', 'City', 'State', 'DriverId', 'FleetNo',
       'Department_y'],
      dtype='object')

In [70]:
## Convert both to string, strip spaces
final_df['UnitNo'] = final_df['UnitNo'].astype(str).str.strip().str.lower()
graylinefleetrenamed_df_selected['FleetNo'] = graylinefleetrenamed_df_selected['FleetNo'].astype(str).str.strip().str.lower()

# Merge
final_df1 = final_df.merge(
    graylinefleetrenamed_df_selected,
    how='left',
    left_on='UnitNo',
    right_on='FleetNo'
)

In [71]:
##Fixing the multiple column values of 'Department' column
final_df1['Depart'] = final_df1['Department_x'].combine_first(final_df1['Department_y'])
final_df1['Depart'] = final_df1['Depart'].str.strip().replace({'SB':'School Bus',
                                                            'SB ':'School Bus',
                                                           'SS':'Sightseeing',
                                                   'BC':'Black Car',
                                                   'charter':'Charter',
                                                   'C':'Charter',
                                                   'Sightseeing (Downtown/Tours)':'Sightseeing',
                                                   'SS Trolley':'Sightseeing',
                                                   'SS DoubleD':'Sightseeing',
                                                   'Tours':'Tour',
                                                   'school bus driver':'School Bus',
                                                   'Tour Guide':'Tour'})

In [72]:
last_df = final_df1.drop(columns=['Department_x', 'Department_y', 'FleetNo']).rename(columns={'Depart':'Department'})

In [73]:
last_df.columns

Index(['ClaimNo', 'DriverName', 'AccidentDate', 'IncidentAccident',
       'DOT Recordable', 'UnitNo', 'Description', 'GLDriverFault',
       'NonGLDriverFault', 'GLEmployeeInjury', 'NonGLEmployeeInjury',
       'InsNotified', 'ClaimType', 'JerrysGLBusRepair', 'Quote',
       'CostForOtherVehicleRepair', 'Actual', 'PoliceReport', 'DriveCam',
       'ClaimStatus', 'Year', 'InsClaimNo', 'GLRepairCost', '3rdPartyCost',
       'InsFee', 'Time', 'Location', 'Weather', 'Lighting', 'RoadSurface',
       'RoadType', 'ControlDevice', 'DriverExperience', 'Raduis', 'DriverInfo',
       'EmployeeId', 'DriverInjured', 'OpInjured', 'GLBusEstimate',
       'GLBusRepair', 'GLFinalCost', 'OpRepairCost', 'OpInsPaid',
       'InsDeductable', 'Total', 'DriverAction', 'Radius', 'Video', 'OpFault',
       'Injury', 'GLEstimate', 'Final', 'CityState', 'ClaimAdj', 'Notes',
       'VMSAccidentNo', 'LossOfBonus', 'Coaching', 'FinalJerrysEstimate',
       'Estimate', 'Prev', 'AccidentDateFormatted', 'NewClaimNo', 'Prevent',
       'City', 'State', 'DriverId', 'Department'],
      dtype='object')

In [74]:
last_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 774 entries, 0 to 773
Data columns (total 68 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ClaimNo                    768 non-null    object
 1   DriverName                 773 non-null    object
 2   AccidentDate               773 non-null    datetime64[ns]
 3   IncidentAccident           774 non-null    object
 4   DOT Recordable             774 non-null    object
 5   UnitNo                     774 non-null    object
 6   Description                769 non-null    object
 7   GLDriverFault              304 non-null    object
 8   NonGLDriverFault           239 non-null    object
 9   GLEmployeeInjury           323 non-null    object
 10  NonGLEmployeeInjury        319 non-null    object
 11  InsNotified                316 non-null    object
 12  ClaimType                  391 non-null    object
 13  JerrysGLBusRepair          137 non-null    object
 14  Quote                      38 non-null     object
 15  CostForOtherVehicleRepair  28 non-null     float64
 16  Actual                     0 non-null      float64
 17  PoliceReport               636 non-null    object
 18  DriveCam                   220 non-null    object
 19  ClaimStatus                566 non-null    object
 20  Year                       774 non-null    int64
 21  InsClaimNo                 424 non-null    object
 22  GLRepairCost               145 non-null    object
 23  3rdPartyCost               34 non-null     float64
 24  InsFee                     206 non-null    float64
 25  Time                       584 non-null    object
 26  Location                   572 non-null    object
 27  Weather                    595 non-null    object
 28  Lighting                   594 non-null    object
 29  RoadSurface                595 non-null    object
 30  RoadType                   594 non-null    object
 31  ControlDevice              80 non-null     object
 32  DriverExperience           203 non-null    object
 33  Raduis                     202 non-null    object
 34  DriverInfo                 64 non-null     object
 35  EmployeeId                 316 non-null    object
 36  DriverInjured              50 non-null     object
 37  OpInjured                  50 non-null     object
 38  GLBusEstimate              50 non-null     float64
 39  GLBusRepair                50 non-null     float64
 40  GLFinalCost                50 non-null     float64
 41  OpRepairCost               317 non-null    object
 42  OpInsPaid                  50 non-null     float64
 43  InsDeductable              50 non-null     float64
 44  Total                      395 non-null    object
 45  DriverAction               392 non-null    object
 46  Radius                     50 non-null     object
 47  Video                      311 non-null    object
 48  OpFault                    88 non-null     float64
 49  Injury                     341 non-null    object
 50  GLEstimate                 19 non-null     float64
 51  Final                      19 non-null     float64
 52  CityState                  291 non-null    object
 53  ClaimAdj                   249 non-null    object
 54  Notes                      268 non-null    object
 55  VMSAccidentNo              265 non-null    object
 56  LossOfBonus                247 non-null    object
 57  Coaching                   247 non-null    object
 58  FinalJerrysEstimate        247 non-null    object
 59  Estimate                   247 non-null    object
 60  Prev                       247 non-null    object
 61  AccidentDateFormatted      773 non-null    object
 62  NewClaimNo                 765 non-null    string
 63  Prevent                    529 non-null    object
 64  City                       291 non-null    object
 65  State                      254 non-null    object
 66  DriverId                   774 non-null    object
 67  Department                 769 non-null    object
dtypes: datetime64[ns](1), float64(12), int64(1), object(53), string(1)
memory usage: 411.3+ KB

In [75]:
# Changing all Nan to Not Registered as per client request.

finalcols=['ClaimNo', 'DriverName', 'AccidentDate', 'IncidentAccident',
       'DOT Recordable', 'UnitNo', 'Description', 'GLDriverFault', 'NonGLDriverFault',
       'GLEmployeeInjury', 'NonGLEmployeeInjury', 'InsNotified', 'ClaimType',
       'JerrysGLBusRepair', 'Quote', 'CostForOtherVehicleRepair', 'Actual',
       'PoliceReport', 'DriveCam', 'ClaimStatus', 'Year', 'InsClaimNo',
       'GLRepairCost', '3rdPartyCost', 'InsFee', 'Time', 'Location', 'Weather',
       'Lighting', 'RoadSurface', 'RoadType', 'ControlDevice',
       'DriverExperience', 'Raduis', 'DriverInfo', 'EmployeeId', 
       'DriverInjured', 'OpInjured', 'GLBusEstimate', 'GLBusRepair', 
       'GLFinalCost', 'OpRepairCost', 'OpInsPaid', 'InsDeductable', 'Total', 
       'DriverAction', 'Radius', 'Video', 'OpFault', 'Injury', 'GLEstimate', 
       'Final', 'CityState', 'ClaimAdj', 'Notes', 'VMSAccidentNo', 
       'LossOfBonus', 'Coaching', 'FinalJerrysEstimate', 'Estimate', 
       'Prev', 'AccidentDateFormatted', 'NewClaimNo', 'Prevent','City', 'State', 'DriverId', 'Department']

last_df[finalcols] = last_df[finalcols].fillna("NA")
last_df['AccidentDate'] = pd.to_datetime(last_df['AccidentDate'], errors='coerce')

In [76]:
# Changing all Numeric/float values to '0' as per client request.

last_df['JerrysGLBusRepair'] = last_df['JerrysGLBusRepair'].replace({'NA': 0})
last_df['Quote'] = last_df['Quote'].replace({'NA': 0})
last_df['CostForOtherVehicleRepair'] = last_df['CostForOtherVehicleRepair'].replace({'NA': 0})
last_df['Actual'] = last_df['Actual'].replace({'N/A': 0})
#last_df['GLRepairCost'] = last_df['GLRepairCost'].replace({'Not Registered': 0})
#last_df['3rdPartyCost'] = last_df['3rdPartyCost'].replace({'Not Registered': 0})
last_df['GLBusEstimate'] = last_df['GLBusEstimate'].replace({'NA': 0})
last_df['GLBusRepair'] = last_df['GLBusRepair'].replace({'NA': 0})
last_df['GLFinalCost'] = last_df['GLFinalCost'].replace({'NA': 0})
last_df['OpRepairCost'] = last_df['OpRepairCost'].replace({'NA': 0})
last_df['InsFee'] = last_df['InsFee'].replace({'NA': 0})
last_df['DriverId'] = last_df['DriverId'].replace({'NA': 0})
last_df['OpInsPaid'] = last_df['OpInsPaid'].replace({'NA': 0})
last_df['OpFault'] = last_df['OpFault'].replace({'NA': 0})
last_df['GLEstimate'] = last_df['GLEstimate'].replace({'NA': 0})
last_df['Final'] = last_df['Final'].replace({'NA': 0})
last_df['InsDeductable'] = last_df['InsDeductable'].replace({'NA': 0})
last_df['Total'] = last_df['Total'].replace({'NA': 0})
last_df['FinalJerrysEstimate'] = last_df['FinalJerrysEstimate'].replace({'NA': 0})
last_df['Estimate'] = last_df['Estimate'].replace({'NA': 0})

In [77]:
last_df['GLDriverFault'] =last_df['GLDriverFault'].replace({'X': 'Y', 'x':'Y'})
last_df['GLDriverFault'] =last_df['GLDriverFault'].replace({'Not Registered': 'N'})
last_df['GLEmployeeInjury'] =last_df['GLEmployeeInjury'].replace({'X': 'Y', 'x':'Y'})
last_df['NonGLDriverFault'] =last_df['NonGLDriverFault'].replace({'X': 'Y'})
last_df['NonGLDriverFault'] =last_df['NonGLDriverFault'].replace({'Not Registered': 'N'})
last_df['PoliceReport'] =last_df['PoliceReport'].replace({'Not Registered': 'N'})
last_df['DriveCam'] =last_df['DriveCam'].replace({'Not Registered': 'N'})

In [78]:
last_df['NonGLDriverFault'] =last_df['NonGLDriverFault'].replace({'Not Registered': 'N'})

In [79]:
last_df['UnitNo'] = last_df['UnitNo'].apply(lambda x: x.split('/')[0] if '/' in x else x)
last_df['UnitNo'] = last_df['UnitNo'].apply(lambda x: x.split(',')[0] if ',' in x else x)
last_df['UnitNo'] = last_df['UnitNo'].apply(lambda x: x.split(' - ')[1] if ' - ' in x else x)
last_df['UnitNo'] = last_df['UnitNo'].apply(lambda x: x.split(' ')[0] if ' ' in x else x)
last_df['UnitNo'] = last_df['UnitNo'].str.replace("-", "")
last_df['UnitNo'] = last_df['UnitNo'].replace('nan', '')
last_df['UnitNo'] = last_df['UnitNo'].replace('n', '')

In [80]:
last_df['NewClaimNo'] = (
    last_df['AccidentDateFormatted'] + '-' + last_df['UnitNo'].astype('string'))
# Remove '.0' at the end of each string
last_df['NewClaimNo'] = last_df['NewClaimNo'].str.replace(r'\.0$', '', regex=True)

In [81]:
last_df = last_df.drop(columns=['ClaimNo', 'AccidentDateFormatted']).rename(columns={'NewClaimNo':'ClaimNo'})

In [82]:
last_df = last_df.drop_duplicates(keep='first')

In [83]:
last_df = last_df.rename(columns = {'DOT Recordable':'DOTRecordable'})

In [84]:
roadtype_clean = {
    'Bus Station ':'Bus Station',
    'Patking Lot':'Parking Lot',
    'parking Lot': 'Parking Lot',
    'Patking Log':'Parking Lot',
    'Turning into church parking lot': 'Parking Lot',
    'nan': 'Not Provided',
    'NaN': 'Not Provided',
    'Residential Driveway': 'Residential Street',
    'interstate': 'Interstate',
    'Divided ': 'Divided',
    'divided': 'Divided',
    'divided ': 'Divided',
    'two lane st': '2 Lane St',
    '21st Ave & Medical Center': 'Residential or City Street',
    'paved ': 'Paved',
    'paved': 'Paved',
    'Asphalt': 'Paved',
    'Gravel': 'Unpaved',
    'Dirt Road': 'Unpaved',
    'Lebanon Pike or Shop Parking Lot': 'Shop Lot',
    'Dickerson pik shop ': 'Shop Lot',
    'Downtown - Nashville': 'Downtown',
    'Dickerson pike by school ': 'Highway',
    'Was unloading': 'Other',
    'Under stadium ': 'Other',
    'Straight': 'Other',
    'N': 'Other',
    'Upgrade': 'Other',
    'Level': 'Other',
    'level': 'Other',
    'Inn at Opryland': 'Other',
    'Golf club': 'Other',
    'Not Registered': 'Not Provided',
}
final_df['RoadTypeUpdate'] = final_df['RoadType'].map(roadtype_clean).fillna(final_df['RoadType'])

last_df['RoadType'] = last_df['RoadType'].replace({'Not Registered':'NA', 'Straight':'Commercial',
                                                   'N':'NA', 'Level':'Commercial',
                                                   'Paved':'Commercial', 'paved':'Commercial',
                                                   'Parking Lot':'Commercial', 'Upgrade':'Commercial',
                                                   'Divided':'Commercial', 'Asphalt':'Commercial',
                                                   'Road Side/Curb/Ditch':'Commercial', 'Other':'Commercial',
                                                   'Interstate':'Interstate', 'Residential Street':'Residential',
                                                   'two lane st':'Commercial', 'Street':'Commercial',
                                                   'Train Station':'Commercial', '4 lane st':'Commercial',
                                                   'Roundabout':'Commercial', 'Shop Lot':'Commercial',
                                                   'Downtown':'Commercial', 'Dirt Road':'Commercial',
                                                   'Highway':'Interstate', 'interstate':'Interstate',
                                                   'parking Lot':'Commercial', 'Inn at Opryland':'Commercial',
                                                   'Private Rd':'Residential', 'Downtown - Nashville':'Commercial',
                                                   'Lebanon Pike or Shop Parking Lot':'Commercial',
                                                   'Golf club':'Commercial', 'Dickerson pike by school ':'Commercial',
                                                   'Gas station':'Commercial', 'Was unloading':'Commercial',
                                                   'Under stadium ':'Commercial', '21st Ave & Medical Center':'Commercial',
                                                   'Residential Driveway':'Residential', 'Turning into church parking lot':'Commercial',
                                                   'Interstate/Highway':'Interstate', 'Dickerson pik shop ':'Commercial',
                                                   'Loading Zone or Bus Lane':'Commercial', 'WeGo Central ':'Commercial',
                                                   'Bus Station ':'Commercial', 'Music City Central':'Commercial',
                                                   'Parking Lot (NOT Gray Line TN)':'Commercial', 'Bus Station':'Commercial',
                                                   'Divided ':'Divided', 'divided':'Divided', 'Roundabout ':'Roundabout'
                                                  })

last_df['RoadType'].value_counts()

# To see all the columns
pd.set_option('display.max_columns', None)

In [85]:
last_df.head()

,DriverName,AccidentDate,IncidentAccident,DOTRecordable,UnitNo,Description,GLDriverFault,NonGLDriverFault,GLEmployeeInjury,NonGLEmployeeInjury,InsNotified,ClaimType,JerrysGLBusRepair,Quote,CostForOtherVehicleRepair,Actual,PoliceReport,DriveCam,ClaimStatus,Year,InsClaimNo,GLRepairCost,3rdPartyCost,InsFee,Time,Location,Weather,Lighting,RoadSurface,RoadType,ControlDevice,DriverExperience,Raduis,DriverInfo,EmployeeId,DriverInjured,OpInjured,GLBusEstimate,GLBusRepair,GLFinalCost,OpRepairCost,OpInsPaid,InsDeductable,Total,DriverAction,Radius,Video,OpFault,Injury,GLEstimate,Final,CityState,ClaimAdj,Notes,VMSAccidentNo,LossOfBonus,Coaching,FinalJerrysEstimate,Estimate,Prev,ClaimNo,Prevent,City,State,DriverId,Department
0,Brittney Patterson,2018-01-04,Incident,N,533,"Driver hit a sign, no damage reported",Y,NA,N,N,N,In-House,0,0,0.0,NA,N,N,Closed,2018,NA,NA,NA,0.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0.0,0.0,0.0,0,0.0,0.0,0,NA,NA,NA,0.0,NA,0.0,0.0,NA,NA,NA,NA,NA,NA,0,0,NA,010418-533,Y,NA,NA,0001,School Bus
1,Scott Wangrud,2018-01-07,Incident,N,1015,Supposedly hit an Anchor Bus' mirror,Y,NA,N,N,N,NA,0,0,0.0,NA,NA,N,Closed,2018,NA,NA,NA,0.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0.0,0.0,0.0,0,0.0,0.0,0,NA,NA,NA,0.0,NA,0.0,0.0,NA,NA,NA,NA,NA,NA,0,0,NA,010718-1015,Y,NA,NA,0002,Charter
2,Thomas House,2018-01-15,Accident,N,1021,Driver hit a sign,Y,NA,N,N,N,In-House,3185.35,0,0.0,NA,N,N,Closed,2018,NA,NA,NA,0.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0.0,0.0,0.0,0,0.0,0.0,0,NA,NA,NA,0.0,NA,0.0,0.0,NA,NA,NA,NA,NA,NA,0,0,NA,011518-1021,Y,NA,NA,0003,Charter
3,David Armstrong,2018-01-16,Accident,N,1015,Bus slid into concrete light pole. Parking lot...,NA,Y,N,N,N,In-House,0,0,0.0,NA,N,N,Closed,2018,NA,NA,NA,0.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0.0,0.0,0.0,0,0.0,0.0,0,NA,NA,NA,0.0,NA,0.0,0.0,NA,NA,NA,NA,NA,NA,0,0,NA,011618-1015,N,NA,NA,0004,Charter
4,William Moncrief,2018-01-19,Accident,N,232,Our bus was hit by Freeman Trucking. Right sid...,NA,Y,N,N,N,OP Ins,0,0,0.0,NA,Y,N,Open,2018,NA,NA,NA,0.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0.0,0.0,0.0,0,0.0,0.0,0,NA,NA,NA,0.0,NA,0.0,0.0,NA,NA,NA,NA,NA,NA,0,0,NA,011918-232,N,NA,NA,0005,Tour

last_df = last_df[['Year', 'ClaimNo', 'DriverId', 'DriverName', 'Department','AccidentDate', 'IncidentAccident', 'UnitNo', 'Description',\
'DOTRecordable', 'DriveCam', 'GLDriverFault', 'NonGLDriverFault', 'GLEmployeeInjury', 'NonGLEmployeeInjury', 'DriverInjured', 'OpInjured', 'Injury', \ 'DriverAction', 'PoliceReport', 'InsNotified', 'ClaimType', 'ClaimStatus',\
'Preventable', 'Weather', 'Lighting', 'Location', 'CityState', 'RoadSurface', 'RoadType', 'Time',  ]]

In [86]:
last_df.to_excel('data/finaloutput.xlsx', index=False)